using BrandVue.EntityFramework.MetaData;
using BrandVue.EntityFramework.MetaData.VariableDefinitions;
using static BrandVue.SourceData.AutoGeneration.AutoGenerationConstants;

namespace BrandVue.SourceData.AutoGeneration;

public class BucketedMetricConfigurationCreator
{
    private readonly IMetricConfigurationRepository _metricConfigurationRepository;
    private readonly IProductContext _context;

    public BucketedMetricConfigurationCreator(IMetricConfigurationRepository metricConfigurationRepository, IProductContext context)
    {
        _metricConfigurationRepository = metricConfigurationRepository;
        _context = context;
    }
    
    public MetricConfiguration CreateBucketedMetricConfiguration(NumericFieldData numericFieldData, VariableConfiguration bucketedVariableConfiguration)
    {
        var field = numericFieldData.GetFieldDefinitionModel();
        var bucketedNumericMetricConfiguration = new MetricConfigurationBuilder(_context.SubProductId, "yn")
            .WithName(numericFieldData.GetUniqueName())
            .WithHelpText(field.QuestionModel.QuestionText)
            .WithProductShortCode(_context.ShortCode)
            .WithVarCode(field.FullV2VarCode)
            .WithDisplayName(field.FullV2VarCode)
            .WithField(field.Name)
            .WithSubsetIds(numericFieldData.GetMetricConfigurationSubsetIdList())
            .WithVariableConfigurationId(bucketedVariableConfiguration.Id)
            .AutoGeneratedFromNumeric()
            .Build();
        _metricConfigurationRepository.Create(bucketedNumericMetricConfiguration, false);
        return bucketedNumericMetricConfiguration;
    }
}