using System.Text.RegularExpressions;
using BrandVue.EntityFramework.Answers.Model;
using BrandVue.EntityFramework.MetaData;
using BrandVue.SourceData.AnswersMetadata;
using BrandVue.SourceData.Import;

namespace BrandVue.SourceData.AutoGeneration;

public class NumericFieldDefinitionCollector
{
    private readonly IReadableMetricConfigurationRepository _metricConfigurationRepository;
    private readonly IResponseFieldManager _responseFieldManager;
    private readonly ISubsetRepository _subsetRepository;
    protected readonly IAnswerDbContextFactory _answersContextFactory;

    public NumericFieldDefinitionCollector(IReadableMetricConfigurationRepository metricConfigurationRepository,
        IResponseFieldManager responseFieldManager,
        ISubsetRepository subsetRepository,
        IAnswerDbContextFactory answerDbContextFactory)
    {
        _metricConfigurationRepository = metricConfigurationRepository;
        _responseFieldManager = responseFieldManager;
        _subsetRepository = subsetRepository;
        _answersContextFactory = answerDbContextFactory;
    }
    
    public IEnumerable<NumericFieldData> GetAllNewNumericFields(Dictionary<int, bool> questionIdHasAnswersLookup)
    {
        var metrics = _metricConfigurationRepository.GetAll().ToList();
        var existingBaseNumerics = metrics
            .Where(metricConfig => metricConfig.IsAutoGenerated == AutoGenerationType.CreatedFromNumeric)
            .Select(metricConfig => metricConfig.Field).ToHashSet();
        
        var responseFields = _responseFieldManager.GetAllFields()
            .OrderBy(field => field.Name).ToList();

        var fieldDefinitions = new Dictionary<string,NumericFieldData>();
        var allQuestions = new List<Question>();

        foreach (var subset in _subsetRepository)
        {
            foreach (var responseField in responseFields)
            {
                var field = responseField.GetDataAccessModelOrNull(subset.Id);
                var questionId = field?.QuestionModel?.QuestionId;
                if (field == null || questionId == null)
                {
                    continue;
                }

                questionIdHasAnswersLookup.TryGetValue(questionId.Value, out var hasAnswers);
                if (!hasAnswers)
                {
                    continue;
                }

                allQuestions.Add(field.QuestionModel);

                bool hasEntityCombinations = responseField.EntityCombination.Any();
                if (hasEntityCombinations || !IsNumeric(field) || HasAlreadyBeenCreated(field, existingBaseNumerics))
                    continue;
                
                string uniqueIdentifier = NumericFieldData.GetUniqueIdentifier(field);
                if (fieldDefinitions.ContainsKey(uniqueIdentifier))
                {
                    fieldDefinitions[uniqueIdentifier].AddSubset(subset.Id);
                }
                else
                {
                    fieldDefinitions.Add(uniqueIdentifier, new NumericFieldData(field, subset.Id));
                }
            }
        }

        AddOriginalMetricNamesToNumericFieldDataFromQuestions(fieldDefinitions.Values, allQuestions, metrics);
        return fieldDefinitions.Values;
    }

    private void AddOriginalMetricNamesToNumericFieldDataFromQuestions(IEnumerable<NumericFieldData> fieldDefinitions, IEnumerable<Question> allQuestions, IList<MetricConfiguration> metrics)
    {
        var nameGenerator = new NameGenerator(allQuestions);
        foreach (var numericFieldData in fieldDefinitions)
        {
            var question = numericFieldData.GetFieldDefinitionModel().QuestionModel;
            string originalMetricName = nameGenerator.GenerateMeasureName(question, new HashSet<string>(StringComparer.OrdinalIgnoreCase));
            numericFieldData.SetOriginalMetricName(originalMetricName);
            var duplicatedNameRegex = new Regex($"{numericFieldData.GetUniqueName()}(?:_[0-9]+)?");
            int duplicatedCount = metrics.Count(m => duplicatedNameRegex.IsMatch(m.Name));
            if (duplicatedCount > 0)
            {
                numericFieldData.IsDuplicate(duplicatedCount);
            }
        }
    }
        
    private bool IsNumeric(FieldDefinitionModel field)
    {
        return field.QuestionModel?.IsNumeric ?? false;
    }

    private bool HasAlreadyBeenCreated(FieldDefinitionModel field, HashSet<string> existingBaseNumerics)
    {
        return existingBaseNumerics.Contains(field.Name);
    }
}
