apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: snowflake-agent-beta-private-key
  namespace: beta
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: azure-store
    kind: ClusterSecretStore
  target:
    name: snowflake-agent-beta-private-key
  data:
  - secretKey: snowflake-agent-beta-private-key
    remoteRef:
      key: AKS-AIRFLOW-SNOWFLAKE-AGENT-BETA-PRIVATE-KEY