DELETE FROM [VariableDependencies] WHERE DependentUponVariableId IN (SELECT Id FROM [VariableConfigurations] WHERE ProductShortCode = 'brandvue' AND Definition LIKE '%BaseFieldVariableExpressionDefinition%')
GO
DELETE FROM [VariableDependencies] WHERE VariableId IN (SELECT Id FROM [VariableConfigurations] WHERE ProductShortCode = 'brandvue' AND Definition LIKE '%BaseFieldVariableExpressionDefinition%')
GO
DELETE FROM [VariableConfigurations] WHERE ProductShortCode = 'brandvue' AND Definition LIKE '%BaseFieldVariableExpressionDefinition%'
GO

INSERT INTO [VariableConfigurations] VALUES('brandvue', null, 'Brand advantage asked base', '{"ResultEntityTypeNames":["brand"],"Expression":"any(response.Brand_advantage_asked (brand = result.brand))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'Brand advantage asked_base')
INSERT INTO [VariableConfigurations] VALUES('brandvue', null, 'Brand affinity asked base', '{"ResultEntityTypeNames":["brand"],"Expression":"any(response.Brand_affinity_asked (brand = result.brand))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'Brand affinity asked_base')
INSERT INTO [VariableConfigurations] VALUES('brandvue', null, 'Recommendation all base', '{"ResultEntityTypeNames":["brand"],"Expression":"any(response.Recommendation_all (brand = result.brand))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'Recommendation all_base')
INSERT INTO [VariableConfigurations] VALUES('brandvue', null, 'Penetration (L12M) base','{"ResultEntityTypeNames":["brand"],"Expression":"any(response.Consumer_segment(brand = result.brand, segment = [4]))","discriminator":"BaseFieldExpressionVariableDefinition"}','L12M_base')


-- Multi-entity definitions
-- INSERT INTO [VariableConfigurations] VALUES('brandvue360', null, ' HSQ4 base', '{"ResultEntityTypeNames":["HSQ4Statements,HSQ4StatmentsToAsk"],"Expression":"any(response._HSQ4 (HSQ4Statements = result.HSQ4Statements,HSQ4StatmentsToAsk = result.HSQ4StatmentsToAsk))","discriminator":"BaseFieldExpressionVariableDefinition"}', '_HSQ4_base')
-- INSERT INTO [VariableConfigurations] VALUES('brandvue360', null, 'attitudes towards switching HSQ7 base', '{"ResultEntityTypeNames":["HSQ2ANSWERED,HSQ7Answers"],"Expression":"any(response.attitudes_towards_switching_HSQ7 (HSQ2ANSWERED = result.HSQ2ANSWERED,HSQ7Answers = result.HSQ7Answers))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'attitudes_towards_switching_HSQ7_base')
-- INSERT INTO [VariableConfigurations] VALUES('brandvue360', null, 'average frequently done TTQ2 base', '{"ResultEntityTypeNames":["TTQ2CarouselContent,TTQ2CarouselOptions"],"Expression":"any(response.average_frequently_done_TTQ2 (TTQ2CarouselContent = result.TTQ2CarouselContent,TTQ2CarouselOptions = result.TTQ2CarouselOptions))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'average_frequently_done_TTQ2_base')
-- INSERT INTO [VariableConfigurations] VALUES('brandvue360', null, 'Brand advantage base', '{"ResultEntityTypeNames":["brand,BrandAdvantage"],"Expression":"any(response.Brand_advantage (brand = result.brand,BrandAdvantage = result.BrandAdvantage))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'Brand_advantage_base')
-- INSERT INTO [VariableConfigurations] VALUES('brandvue360', null, 'Brand affinity base', '{"ResultEntityTypeNames":["Affinity,brand"],"Expression":"any(response.Brand_affinity (Affinity = result.Affinity,brand = result.brand))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'Brand_affinity_base')
-- INSERT INTO [VariableConfigurations] VALUES('brandvue360', null, 'Consumer segment base', '{"ResultEntityTypeNames":["brand,ShopperSegment"],"Expression":"any(response.Consumer_segment (brand = result.brand,ShopperSegment = result.ShopperSegment))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'Consumer_segment_base')
-- INSERT INTO [VariableConfigurations] VALUES('brandvue360', null, 'Drivers base', '{"ResultEntityTypeNames":["brand,Drivers"],"Expression":"any(response.Drivers (brand = result.brand,Drivers = result.Drivers))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'Drivers_base')
-- INSERT INTO [VariableConfigurations] VALUES('brandvue360', null, 'extent households energy HSQ12 base', '{"ResultEntityTypeNames":["HSQ12Answers,HSQ12Statements"],"Expression":"any(response.extent_households_energy_HSQ12 (HSQ12Answers = result.HSQ12Answers,HSQ12Statements = result.HSQ12Statements))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'extent_households_energy_HSQ12_base')
-- INSERT INTO [VariableConfigurations] VALUES('brandvue360', null, 'FMCG Q9 base', '{"ResultEntityTypeNames":["FMCGQ9Answers,OneThroughEight"],"Expression":"any(response.FMCG_Q9 (FMCGQ9Answers = result.FMCGQ9Answers,OneThroughEight = result.OneThroughEight))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'FMCG_Q9_base')
-- INSERT INTO [VariableConfigurations] VALUES('brandvue360', null, 'frequently media platforms QP605 base', '{"ResultEntityTypeNames":["QP605Answers,QP605Statements"],"Expression":"any(response.frequently_media_platforms_QP605 (QP605Answers = result.QP605Answers,QP605Statements = result.QP605Statements))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'frequently_media_platforms_QP605_base')
-- INSERT INTO [VariableConfigurations] VALUES('brandvue360', null, 'frequently platform week QP604 base', '{"ResultEntityTypeNames":["Q604Answers,QP603Answers"],"Expression":"any(response.frequently_platform_week_QP604 (Q604Answers = result.Q604Answers,QP603Answers = result.QP603Answers))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'frequently_platform_week_QP604_base')
-- INSERT INTO [VariableConfigurations] VALUES('brandvue360', null, 'Image base', '{"ResultEntityTypeNames":["brand,ImageAttributes"],"Expression":"any(response.Image (brand = result.brand,ImageAttributes = result.ImageAttributes))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'Image_base')
-- INSERT INTO [VariableConfigurations] VALUES('brandvue360', null, 'important uses internet HSQ11 base', '{"ResultEntityTypeNames":["HSQ11Answers,OneThroughEight"],"Expression":"any(response.important_uses_internet_HSQ11 (HSQ11Answers = result.HSQ11Answers,OneThroughEight = result.OneThroughEight))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'important_uses_internet_HSQ11_base')
-- INSERT INTO [VariableConfigurations] VALUES('brandvue360', null, 'likely adopt technologies HSQ6 base', '{"ResultEntityTypeNames":["HSQ6Answers,HSQ6Statements"],"Expression":"any(response.likely_adopt_technologies_HSQ6 (HSQ6Answers = result.HSQ6Answers,HSQ6Statements = result.HSQ6Statements))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'likely_adopt_technologies_HSQ6_base')
-- INSERT INTO [VariableConfigurations] VALUES('brandvue360', null, 'Logo 5 base', '{"ResultEntityTypeNames":["brand,BrandsImageTag"],"Expression":"any(response.Logo_5 (brand = result.brand,BrandsImageTag = result.BrandsImageTag))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'Logo_5_base')
-- INSERT INTO [VariableConfigurations] VALUES('brandvue360', null, 'Logo Image base', '{"ResultEntityTypeNames":["brand,BrandsImageTag"],"Expression":"any(response.Logo_Image (brand = result.brand,BrandsImageTag = result.BrandsImageTag))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'Logo_Image_base')
-- INSERT INTO [VariableConfigurations] VALUES('brandvue360', null, 'many holiday had QP501 base', '{"ResultEntityTypeNames":["QP501CarouselContent,QP501CarouselOptions"],"Expression":"any(response.many_holiday_had_QP501 (QP501CarouselContent = result.QP501CarouselContent,QP501CarouselOptions = result.QP501CarouselOptions))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'many_holiday_had_QP501_base')
-- INSERT INTO [VariableConfigurations] VALUES('brandvue360', null, 'more less same PLQ4 base', '{"ResultEntityTypeNames":["PLQ1Categories,PLQ4Answers"],"Expression":"any(response.more_less_same_PLQ4 (PLQ1Categories = result.PLQ1Categories,PLQ4Answers = result.PLQ4Answers))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'more_less_same_PLQ4_base')
-- INSERT INTO [VariableConfigurations] VALUES('brandvue360', null, 'options behaviour categories PLQ1 base', '{"ResultEntityTypeNames":["PLQ1CarouselOptions,PLQ1Categories"],"Expression":"any(response.options_behaviour_categories_PLQ1 (PLQ1CarouselOptions = result.PLQ1CarouselOptions,PLQ1Categories = result.PLQ1Categories))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'options_behaviour_categories_PLQ1_base')
-- INSERT INTO [VariableConfigurations] VALUES('brandvue360', null, 'pay for pagechoicealt HSQ3 base', '{"ResultEntityTypeNames":["HSQ2ANSWERED,HSQ3AnswersTag"],"Expression":"any(response.pay_for_pagechoicealt_HSQ3 (HSQ2ANSWERED = result.HSQ2ANSWERED,HSQ3AnswersTag = result.HSQ3AnswersTag))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'pay_for_pagechoicealt_HSQ3_base')
-- INSERT INTO [VariableConfigurations] VALUES('brandvue360', null, 'QP106Hours base', '{"ResultEntityTypeNames":["QP106Answers,QP106HoursAnswers"],"Expression":"any(response.QP106Hours (QP106Answers = result.QP106Answers,QP106HoursAnswers = result.QP106HoursAnswers))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'QP106Hours_base')
-- INSERT INTO [VariableConfigurations] VALUES('brandvue360', null, 'QP106Minutes base', '{"ResultEntityTypeNames":["QP106Answers,QP106MinutesAnswers"],"Expression":"any(response.QP106Minutes (QP106Answers = result.QP106Answers,QP106MinutesAnswers = result.QP106MinutesAnswers))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'QP106Minutes_base')
-- INSERT INTO [VariableConfigurations] VALUES('brandvue360', null, 'rank order cool TTQ5 base', '{"ResultEntityTypeNames":["TTQ4Answers,TTQ4Ranks"],"Expression":"any(response.rank_order_cool_TTQ5 (TTQ4Answers = result.TTQ4Answers,TTQ4Ranks = result.TTQ4Ranks))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'rank_order_cool_TTQ5_base')
-- INSERT INTO [VariableConfigurations] VALUES('brandvue360', null, 'rank order environmentallyfriendly TTQ4 base', '{"ResultEntityTypeNames":["TTQ4Answers,TTQ4Ranks"],"Expression":"any(response.rank_order_environmentallyfriendly_TTQ4 (TTQ4Answers = result.TTQ4Answers,TTQ4Ranks = result.TTQ4Ranks))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'rank_order_environmentallyfriendly_TTQ4_base')
-- INSERT INTO [VariableConfigurations] VALUES('brandvue360', null, 'Spont Aware Coded base', '{"ResultEntityTypeNames":["BrandsCoding,OneThroughEight"],"Expression":"any(response.Spont_Aware_Coded (BrandsCoding = result.BrandsCoding,OneThroughEight = result.OneThroughEight))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'Spont_Aware_Coded_base')
-- INSERT INTO [VariableConfigurations] VALUES('brandvue360', null, 'these sports follow QP103 base', '{"ResultEntityTypeNames":["QP103Answers,QP103Statements"],"Expression":"any(response.these_sports_follow_QP103 (QP103Answers = result.QP103Answers,QP103Statements = result.QP103Statements))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'these_sports_follow_QP103_base')
-- INSERT INTO [VariableConfigurations] VALUES('brandvue360', null, 'typically feel pagechoice TTQ6 base', '{"ResultEntityTypeNames":["TTQ6Answers,TTQ6Loop"],"Expression":"any(response.typically_feel_pagechoice_TTQ6 (TTQ6Answers = result.TTQ6Answers,TTQ6Loop = result.TTQ6Loop))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'typically_feel_pagechoice_TTQ6_base')
