DELETE FROM [VariableDependencies] WHERE DependentUponVariableId IN (SELECT Id FROM [VariableConfigurations] WHERE ProductShortCode = 'retail' AND Definition LIKE '%BaseFieldVariableExpressionDefinition%')
GO
DELETE FROM [VariableDependencies] WHERE VariableId IN (SELECT Id FROM [VariableConfigurations] WHERE ProductShortCode = 'retail' AND Definition LIKE '%BaseFieldVariableExpressionDefinition%')
GO
DELETE FROM [VariableConfigurations] WHERE ProductShortCode = 'retail' AND Definition LIKE '%BaseFieldVariableExpressionDefinition%'
GO

INSERT INTO [VariableConfigurations] VALUES('retail', null, 'Advertising awareness base', '{"ResultEntityTypeNames":["brand"],"Expression":"any(response.Advertising_awareness (brand = result.brand))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'Advertising awareness_base')
INSERT INTO [VariableConfigurations] VALUES('retail', null, 'Bought other base', '{"ResultEntityTypeNames":["brand"],"Expression":"any(response.Bought_other (brand = result.brand))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'Bought other_base')
INSERT INTO [VariableConfigurations] VALUES('retail', null, 'Brand advantage base', '{"ResultEntityTypeNames":["brand"],"Expression":"any(response.Brand_advantage (brand = result.brand))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'Brand advantage_base')
INSERT INTO [VariableConfigurations] VALUES('retail', null, 'Brand affinity base', '{"ResultEntityTypeNames":["brand"],"Expression":"any(response.Brand_affinity (brand = result.brand))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'Brand affinity_base')
INSERT INTO [VariableConfigurations] VALUES('retail', null, 'Consider base', '{"ResultEntityTypeNames":["brand"],"Expression":"any(response.Consider (brand = result.brand))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'Consider_base')
INSERT INTO [VariableConfigurations] VALUES('retail', null, 'Frequency instore base', '{"ResultEntityTypeNames":["brand"],"Expression":"any(response.Frequency_instore (brand = result.brand))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'Frequency instore_base')
INSERT INTO [VariableConfigurations] VALUES('retail', null, 'Frequency online base', '{"ResultEntityTypeNames":["brand"],"Expression":"any(response.Frequency_online (brand = result.brand))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'Frequency online_base')
INSERT INTO [VariableConfigurations] VALUES('retail', null, 'Image: Convenient base', '{"ResultEntityTypeNames":["brand"],"Expression":"any(response.Image_evaluation_convenient (brand = result.brand))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'Image evaluation: convenient_base')
INSERT INTO [VariableConfigurations] VALUES('retail', null, 'Image: Easy to find base', '{"ResultEntityTypeNames":["brand"],"Expression":"any(response.Image_evaluation_easy_to_find (brand = result.brand))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'Image evaluation: easy to find_base')
INSERT INTO [VariableConfigurations] VALUES('retail', null, 'Image: Environmentally friendly base', '{"ResultEntityTypeNames":["brand"],"Expression":"any(response.Image_evaluation_environmentally_friendly (brand = result.brand))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'Image evaluation: environmentally friendly_base')
INSERT INTO [VariableConfigurations] VALUES('retail', null, 'Image: Ethical base', '{"ResultEntityTypeNames":["brand"],"Expression":"any(response.Image_evaluation_ethical (brand = result.brand))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'Image evaluation: ethical_base')
INSERT INTO [VariableConfigurations] VALUES('retail', null, 'Image: Exciting base', '{"ResultEntityTypeNames":["brand"],"Expression":"any(response.Image_evaluation_exciting (brand = result.brand))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'Image evaluation: exciting_base')
INSERT INTO [VariableConfigurations] VALUES('retail', null, 'Image: For people like me base', '{"ResultEntityTypeNames":["brand"],"Expression":"any(response.Image_evaluation_for_people_like_me (brand = result.brand))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'Image evaluation: for people like me_base')
INSERT INTO [VariableConfigurations] VALUES('retail', null, 'Image: Friendly base', '{"ResultEntityTypeNames":["brand"],"Expression":"any(response.Image_evaluation_friendly (brand = result.brand))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'Image evaluation: friendly_base')
INSERT INTO [VariableConfigurations] VALUES('retail', null, 'Image: Good service base', '{"ResultEntityTypeNames":["brand"],"Expression":"any(response.Image_evaluation_good_service (brand = result.brand))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'Image evaluation: good service_base')
INSERT INTO [VariableConfigurations] VALUES('retail', null, 'Image: Good value base', '{"ResultEntityTypeNames":["brand"],"Expression":"any(response.Image_evaluation_good_value (brand = result.brand))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'Image evaluation: good value_base')
INSERT INTO [VariableConfigurations] VALUES('retail', null, 'Image: Premium base', '{"ResultEntityTypeNames":["brand"],"Expression":"any(response.Image_evaluation_premium (brand = result.brand))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'Image evaluation: premium_base')
INSERT INTO [VariableConfigurations] VALUES('retail', null, 'Image: Quality base', '{"ResultEntityTypeNames":["brand"],"Expression":"any(response.Image_evaluation_quality (brand = result.brand))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'Image evaluation: quality_base')
INSERT INTO [VariableConfigurations] VALUES('retail', null, 'Image: Stylish base', '{"ResultEntityTypeNames":["brand"],"Expression":"any(response.Image_evaluation_stylish (brand = result.brand))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'Image evaluation: stylish_base')
INSERT INTO [VariableConfigurations] VALUES('retail', null, 'Image: Trusted base', '{"ResultEntityTypeNames":["brand"],"Expression":"any(response.Image_evaluation_trusted (brand = result.brand))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'Image evaluation: trusted_base')
INSERT INTO [VariableConfigurations] VALUES('retail', null, 'Image: Wide range base', '{"ResultEntityTypeNames":["brand"],"Expression":"any(response.Image_evaluation_wide_range (brand = result.brand))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'Image evaluation: wide range_base')
INSERT INTO [VariableConfigurations] VALUES('retail', null, 'Satisfaction in-store base', '{"ResultEntityTypeNames":["brand"],"Expression":"any(response.In_store_satisfaction (brand = result.brand))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'In store satisfaction_base')
INSERT INTO [VariableConfigurations] VALUES('retail', null, 'Loyalty scheme: Awareness base', '{"ResultEntityTypeNames":["brand"],"Expression":"any(response.Loyalty_Card_Awareness (brand = result.brand))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'Loyalty Card: Awareness_base')
INSERT INTO [VariableConfigurations] VALUES('retail', null, 'Loyalty scheme: Usage base', '{"ResultEntityTypeNames":["brand"],"Expression":"any(response.Loyalty_Card_Usage (brand = result.brand))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'Loyalty Card: Usage_base')
INSERT INTO [VariableConfigurations] VALUES('retail', null, 'Buzz: Negative buzz base', '{"ResultEntityTypeNames":["brand"],"Expression":"any(response.Negative_buzz (brand = result.brand))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'Negative buzz_base')
INSERT INTO [VariableConfigurations] VALUES('retail', null, 'Not consider base', '{"ResultEntityTypeNames":["brand"],"Expression":"any(response.Not_consider (brand = result.brand))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'Not consider_base')
INSERT INTO [VariableConfigurations] VALUES('retail', null, 'Satisfaction online base', '{"ResultEntityTypeNames":["brand"],"Expression":"any(response.Online_satisfaction (brand = result.brand))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'Online satisfaction_base')
INSERT INTO [VariableConfigurations] VALUES('retail', null, 'Buzz: Positive buzz base', '{"ResultEntityTypeNames":["brand"],"Expression":"any(response.Positive_buzz (brand = result.brand))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'Positive buzz_base')
INSERT INTO [VariableConfigurations] VALUES('retail', null, 'Preference base', '{"ResultEntityTypeNames":["brand"],"Expression":"any(response.Preference (brand = result.brand))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'Preference_base')
INSERT INTO [VariableConfigurations] VALUES('retail', null, 'Recommendation base', '{"ResultEntityTypeNames":["brand"],"Expression":"any(response.Recommendation (brand = result.brand))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'Recommendation_base')
INSERT INTO [VariableConfigurations] VALUES('retail', null, 'Penetration (L12M) base','{"ResultEntityTypeNames":["brand"],"Expression":"any(response.Consumer_segment(brand = result.brand, segment = [4,5,6]))","discriminator":"BaseFieldExpressionVariableDefinition"}','L12M_base')
INSERT INTO [VariableConfigurations] VALUES('retail', null, 'Penetration (L3M) base','{"ResultEntityTypeNames":["brand"],"Expression":"any(response.Consumer_segment(brand = result.brand, segment = [5,6]))","discriminator":"BaseFieldExpressionVariableDefinition"}','L3M_base')
INSERT INTO [VariableConfigurations] VALUES('retail', null, 'Penetration (LM) base','{"ResultEntityTypeNames":["brand"],"Expression":"any(response.Consumer_segment(brand = result.brand, segment = [6]))","discriminator":"BaseFieldExpressionVariableDefinition"}','LM_base')

UPDATE pg
SET pg.DefaultBase = 'L12M_base'
FROM Pages pg
JOIN Panes pn
ON (pn.PageName = pg.Name AND pn.ProductShortCode = pg.ProductShortCode)
WHERE pg.[ProductShortCode] = 'retail'
AND PaneType = 'AudienceProfile'

-- Multi-entity definitions
-- INSERT INTO [VariableConfigurations] VALUES('retail', null, 'Consider product base', '{"ResultEntityTypeNames":["brand,product"],"Expression":"any(response.Consider_product (brand = result.brand,product = result.product))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'Consider_product_base')
-- INSERT INTO [VariableConfigurations] VALUES('retail', null, 'Consumer segment entity base', '{"ResultEntityTypeNames":["brand,segment"],"Expression":"any(response.Consumer_segment_entity (brand = result.brand,segment = result.segment))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'Consumer_segment_entity_base')
-- INSERT INTO [VariableConfigurations] VALUES('retail', null, 'Driver ratings base', '{"ResultEntityTypeNames":["driver,product"],"Expression":"any(response.Driver_ratings (driver = result.driver,product = result.product))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'Driver_ratings_base')
-- INSERT INTO [VariableConfigurations] VALUES('retail', null, 'Image evaluation base', '{"ResultEntityTypeNames":["brand,image"],"Expression":"any(response.Image_evaluation (brand = result.brand,image = result.image))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'Image_evaluation_base')
-- INSERT INTO [VariableConfigurations] VALUES('retail', null, 'Never consider product base', '{"ResultEntityTypeNames":["brand,product"],"Expression":"any(response.Never_consider_product (brand = result.brand,product = result.product))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'Never_consider_product_base')
-- INSERT INTO [VariableConfigurations] VALUES('retail', null, 'Preference product base', '{"ResultEntityTypeNames":["brand,product"],"Expression":"any(response.Preference_product (brand = result.brand,product = result.product))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'Preference_product_base')
-- INSERT INTO [VariableConfigurations] VALUES('retail', null, 'Product awareness coded base', '{"ResultEntityTypeNames":["brand,product,spontaneousposition"],"Expression":"any(response.Product_awareness_coded (brand = result.brand,product = result.product,spontaneousposition = result.spontaneousposition))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'Product_awareness_coded_base')
-- INSERT INTO [VariableConfigurations] VALUES('retail', null, 'Reasons for choosing base', '{"ResultEntityTypeNames":["product,reason"],"Expression":"any(response.Reasons_for_choosing (product = result.product,reason = result.reason))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'Reasons_for_choosing_base')
-- INSERT INTO [VariableConfigurations] VALUES('retail', null, 'Sources of influence base', '{"ResultEntityTypeNames":["influence,product"],"Expression":"any(response.Sources_of_influence (influence = result.influence,product = result.product))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'Sources_of_influence_base')
-- INSERT INTO [VariableConfigurations] VALUES('retail', null, 'Sources of influence most important base', '{"ResultEntityTypeNames":["influence,product"],"Expression":"any(response.Sources_of_influence_most_important (influence = result.influence,product = result.product))","discriminator":"BaseFieldExpressionVariableDefinition"}', 'Sources_of_influence_most_important_base')
