namespace BrandVue.EntityFramework.MetaData
{
    public class MetricConfigurationBuilder
    {
        private MetricConfiguration _metricConfiguration = new ();

        public MetricConfigurationBuilder(string subProductId, string calcType)
        {
            _metricConfiguration.SubProductId = subProductId;
            _metricConfiguration.CalcType = calcType;
        }

        public MetricConfigurationBuilder WithName(string name)
        {
            _metricConfiguration.Name = name;
            return this;
        }

        public MetricConfigurationBuilder WithHelpText(string helpText)
        {
            _metricConfiguration.HelpText = helpText;
            return this;
        }

        public MetricConfigurationBuilder WithVariableConfigurationId(int? variableId)
        {
            _metricConfiguration.VariableConfigurationId = variableId;
            return this;
        }

        public MetricConfigurationBuilder AutoGeneratedFromNumeric()
        {
            _metricConfiguration.EligibleForCrosstabOrAllVue = true;
            _metricConfiguration.CalcType = "yn";
            _metricConfiguration.NumFormat = "0%";
            _metricConfiguration.IsAutoGenerated = AutoGenerationType.CreatedFromNumeric;
            return this;
        }

        public MetricConfigurationBuilder WithProductShortCode(string productShortCode)
        {
            _metricConfiguration.ProductShortCode = productShortCode;
            return this;
        }
        
        public MetricConfigurationBuilder WithVarCode(string varCode)
        {
            _metricConfiguration.VarCode = varCode;
            return this;
        }

        public MetricConfigurationBuilder WithDisplayName(string displayName)
        {
            _metricConfiguration.DisplayName = displayName;
            return this;
        }

        public MetricConfigurationBuilder WithSubsetIds(string subsetIds)
        {
            _metricConfiguration.Subset = subsetIds;
            return this;
        }
        
        public MetricConfigurationBuilder WithField(string fieldName)
        {
            _metricConfiguration.Field = fieldName;
            return this;
        }

        public MetricConfiguration Build()
        {
            if (_metricConfiguration.Name == null)
            {
                throw new Exception("Metric configuration builder is missing required property: Name");
            }

            if (_metricConfiguration.CalcType == null)
            {
                throw new Exception("Metric configuration builder is missing required property: CalcType");
            }

            return _metricConfiguration;
        }
    }
}