using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using BrandVue.EntityFramework.MetaData.VariableDefinitions;
using CsvHelper.Configuration.Attributes;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using NJsonSchema.Annotations;

namespace BrandVue.EntityFramework.MetaData
{
    /// <summary>
    /// This object is a close to 1-1 representation of the Metrics tab in the map file.
    /// It is required because the Measure domain model contains a lot of calculation objects so it's not suitable for configuration editing.
    /// </summary>
    /// <remarks>Ordering is shown in the UI, try to keep related things together and more important stuff near the top (as we'd want in C# anyway)</remarks>
    [Table("MetricConfigurations")]
    public class MetricConfiguration
    {
        public int Id { get; set; }
        public string ProductShortCode { get; set; }
        [MaxLength(SqlTypeConstants.DefaultVarcharLength)]
        public string SubProductId { get; set; }
        [Required]
        public string Name { get; set; }
        public string DisplayName { get; set; }
        public int? VariableConfigurationId { get; set; }
        [Required]
        public string CalcType { get; set; }
        public string Subset { get; set; }
        [Newtonsoft.Json.JsonIgnore, System.Text.Json.Serialization.JsonIgnore, Ignore]
        public VariableConfiguration VariableConfiguration { get; set; }
        [CanBeNull][NotMapped] public string? PrimaryVariableIdentifier => VariableConfiguration?.Identifier;
        [Obsolete("A FieldExpressionVariableDefinition can be created instead of using this property")]
        public string FieldExpression { get; set; }
        public string Field { get; set; }
        public string Field2 { get; set; }
        public string FieldOp { get; set; }
        public string TrueVals { get; set; }
        public int? BaseVariableConfigurationId { get; set; }
        [Newtonsoft.Json.JsonIgnore, System.Text.Json.Serialization.JsonIgnore, Ignore]
        public VariableConfiguration BaseVariableConfiguration { get; set; }
        public string BaseExpression { get; set; }
        public string BaseField { get; set; }
        public string BaseVals { get; set; }
        public string HelpText { get; set; }
        public string NumFormat { get; set; }
        public int? Min { get; set; }
        public int? Max { get; set; }
        public DateTime? StartDate { get; set; }
        public bool DisableMeasure { get; set; }
        public bool EligibleForMetricComparison { get; set; }
        public bool EligibleForCrosstabOrAllVue { get; set; }
        public bool DownIsGood { get; set; }
        [MaxLength(450)]
        public string DefaultSplitByEntityType { get; set; }
        public AutoGenerationType IsAutoGenerated { get; set; }
        public bool DisableFilter { get; set; }
        public bool FilterMulti { get; set; }
        public string FilterValueMapping { get; set; }
        //Users can be manually set this property to true meaning it does not necessarily reflect what is in the database
        public bool HasData { get; set; }
        [CanBeNull]
        public string? OriginalMetricName { get; set; }
        public int? ExcludeWaves { get; set; }
        [CanBeNull]
        public string? EntityInstanceIdMeanCalculationValueMapping { get; set; }
        public double? ScaleFactor { get; set; }
        public string Measure { get; set; }
        public string VarCode { get; set; }
        public string FilterGroup { get; set; }
        public int? PreNormalisationMinimum { get; set; }
        public int? PreNormalisationMaximum { get; set; }

        // Generally not used

        public string ExcludeList { get; set; }
        [Obsolete("Never used - was intended to allow weighted average across entities using a randomly sampled measure (consumer_segment) to avoid sample bias in the current measure")]
        public string MarketAverageBaseMeasure { get; set; }
        [Obsolete("Long gone map file feature")]
        public string KeyImage { get; set; }
        public MetricConfiguration ShallowCopy()
        {
            return (MetricConfiguration)MemberwiseClone();
        }
    }

    public class MetricConfigurationConfiguration : IEntityTypeConfiguration<MetricConfiguration>
    {
        public void Configure(EntityTypeBuilder<MetricConfiguration> builder)
        {
            builder.Property(m => m.ProductShortCode).IsRequired();
            builder.HasKey(m => m.Id);
            builder.HasIndex(m => new {m.Name, m.ProductShortCode, m.SubProductId}).IsUnique();
            builder.Property(m => m.EntityInstanceIdMeanCalculationValueMapping).HasJsonConversion();
        }
    }
}
