using BrandVue.EntityFramework.MetaData;
using BrandVue.EntityFramework.MetaData.BaseSizes;
using BrandVue.EntityFramework.MetaData.VariableDefinitions;
using BrandVue.SourceData.Measures;
using BrandVue.SourceData.Variable;

namespace BrandVue.SourceData.Calculation.Expressions
{
    public class BaseExpressionGenerator : IBaseExpressionGenerator
    {
        private readonly IReadableMetricConfigurationRepository _metricConfigRepository;
        private readonly IResponseFieldManager _responseFieldManager;
        private readonly IReadableVariableConfigurationRepository _variableConfigRepository;
        private readonly IFieldExpressionParser _fieldExpressionParser;

        public BaseExpressionGenerator(IReadableMetricConfigurationRepository metricConfigRepository, IResponseFieldManager responseFieldManager, IReadableVariableConfigurationRepository variableConfigRepository, IFieldExpressionParser fieldExpressionParser)
        {
            _metricConfigRepository = metricConfigRepository;
            _responseFieldManager = responseFieldManager;
            _variableConfigRepository = variableConfigRepository;
            _fieldExpressionParser = fieldExpressionParser;
        }

        public Measure GetMeasureWithOverriddenBaseExpression(Measure measure, BaseExpressionDefinition baseExpressionOverride)
        {
            if (baseExpressionOverride != null && !measure.HasCustomBase)
            {
                var measureCopy = measure.ShallowCopy();
                measureCopy.BaseExpressionString = GetPythonExpression(baseExpressionOverride, measure);
                measureCopy.BaseExpression = _fieldExpressionParser.ParseUserBooleanExpression(measureCopy.BaseExpressionString);
                measureCopy.BaseVariableConfigurationId = baseExpressionOverride.BaseVariableId;
                return measureCopy;
            }
            return measure;
        }

        private string GetPythonExpression(BaseExpressionDefinition baseDefinition, Measure measure)
        {
            if (baseDefinition.BaseVariableId.HasValue)
            {
                return GetBaseVariablePythonExpression(baseDefinition.BaseVariableId.Value,
                    baseDefinition.BaseType == BaseDefinitionType.SawThisChoice,
                    measure.PrimaryFieldEntityCombination.Select(t => t.Identifier).ToArray());
            }

            return baseDefinition.BaseType switch
            {
                BaseDefinitionType.AllRespondents => "1",
                BaseDefinitionType.SawThisQuestion => GetAnsweredThisQuestionPythonExpression(baseDefinition.BaseMeasureName, false),
                BaseDefinitionType.SawThisChoice => GetAnsweredThisQuestionPythonExpression(baseDefinition.BaseMeasureName, true),
                _ => throw new NotImplementedException(),
            };
        }

        public string GetBaseVariablePythonExpression(int baseVariableId, bool includeResultTypes, IEnumerable<string> primaryEntityTypeNames)
        {
            var variableConfig = _variableConfigRepository.Get(baseVariableId);
            return GetBaseVariablePythonExpression(variableConfig, includeResultTypes, primaryEntityTypeNames);
        }

        public static string GetBaseVariablePythonExpression(VariableConfiguration variableConfig, bool includeResultTypes, IEnumerable<string> primaryEntityTypeNames)
        {
            if (variableConfig.Definition is BaseGroupedVariableDefinition baseVariableDefinition)
            {
                if (baseVariableDefinition.ContainsPythonExpression())
                {
                    return baseVariableDefinition.Groups.Single().Component.GetPythonCondition(includeResultTypes, primaryEntityTypeNames);
                }
                else
                {
                    //Surveyid and DateRange variables have no python expression
                    return $"len(response.{variableConfig.Identifier}())";
                }
            }
            else if (variableConfig.Definition is BaseFieldExpressionVariableDefinition baseExpressionVariableDefinition)
            {
                return baseExpressionVariableDefinition.Expression;
            }
            throw new InvalidOperationException($"Variable ({variableConfig.Definition.GetType().Name}) must be of {nameof(BaseGroupedVariableDefinition)} or {nameof(BaseFieldExpressionVariableDefinition)} type to be used as base variable");
        }

        private string GetAnsweredThisQuestionPythonExpression(string measureName, bool includeResultTypes)
        {
            var metric = _metricConfigRepository.Get(measureName);
            if (metric.VariableConfigurationId.HasValue && (metric.IsAutoGenerated == AutoGenerationType.Original || metric.IsAutoGenerated == AutoGenerationType.CreatedFromNumeric))
            {
                return GetAnsweredQuestionPythonExpression(
                                includeResultTypes,
                                _variableConfigRepository.Get(metric.VariableConfigurationId.Value));
            }
            else
            {
                /* It would be better for this to reference BaseField instead of Field, but the _asked Fields aren't available
                 * in FieldExpressionParser currently. As these are likely to be replaced sometime soon this can be left as Field for now.
                 * This should only present odd data for specific custom metrics which reference a different question as the baseField
                 * https://github.com/MIG-Global/Vue/pull/3003/files#r802445242
                 * https://github.com/MIG-Global/Vue/pull/2994#issuecomment-1032470420
                 */
                var responseFieldName = $"response.{metric.Field}";

                string resultTypes = null;
                if (includeResultTypes)
                {
                    var baseField = _responseFieldManager.Get(metric.BaseField);
                    if (baseField.EntityCombination.Any())
                    {
                        resultTypes = string.Join(", ", baseField.EntityCombination.Select(t => $"{t.Identifier}=result.{t.Identifier}"));
                    }
                }

                return GetExistsConditionForIdentifier(responseFieldName, resultTypes);
            }
        }
        public string GetAnsweredQuestionPythonExpression(VariableConfiguration variableConfig)
        {
            return GetAnsweredQuestionPythonExpression(true, variableConfig);
        }

        private string GetAnsweredQuestionPythonExpression(bool includeResultTypes, VariableConfiguration variableConfig)
        {
            switch (variableConfig.Definition)
            {
                case FieldExpressionVariableDefinition:
                    // Determining whether someone has seen all the relevant choices of various questions to satisfy an arbitrary variable expression is very tricky.
                    // So use the meaning "respondent has some answers to this question", and make it the expression writer's job to return None when there is no answer.
                    return $"len(response.{variableConfig.Identifier}())";
                case SingleGroupVariableDefinition singleGroupVariableDefinition:
                    return BaseExpressionForAnyoneAskedThisQuestion(singleGroupVariableDefinition, includeResultTypes);
                case GroupedVariableDefinition groupedVariableDefinition:
                    return BaseExpressionForAnyoneAskedThisQuestion(groupedVariableDefinition, includeResultTypes);
                default:
                    return "";
            }
        }

        private string GetExistsConditionForIdentifier(string responseIdentifier, string resultTypes = null)
        {
            return $"len({responseIdentifier}({resultTypes ?? ""}))";
        }

        public string BaseExpressionForAnyoneAskedThisQuestion(SingleGroupVariableDefinition singleGroupDefinition, bool includeResultTypes)
        {
            var expression = BaseExpression(singleGroupDefinition.Group.Component, includeResultTypes);
            return string.IsNullOrEmpty(expression) ? "1" : expression;
        }

        public string BaseExpressionForAnyoneAskedThisQuestion(GroupedVariableDefinition groupedDefinition, bool includeResultTypes)
        {
            //
            // This looks for anyone who has been asked any of these questions (does not care if they have answered the items we want...)
            //
            // This will need to be extended for https://app.clubhouse.io/mig-global/story/51710/add-support-for-sample-size-by-filter
            //

            var identifiers = new List<string>();
            foreach (var group in groupedDefinition.Groups)
            {
                var expression = BaseExpression(group.Component, includeResultTypes);
                if (!string.IsNullOrEmpty(expression))
                {
                    identifiers.Add($"({expression})");
                }
            }
            var baseExpression = string.Join(" or ", identifiers.Distinct());
            return string.IsNullOrEmpty(baseExpression) ? "1" : baseExpression;
        }

        private string RawFieldExpression(string variableIdentifier, bool includeResultTypes, string resultTypes = null)
        {
            var variable = _variableConfigRepository.GetByIdentifier(variableIdentifier);
            if (variable?.Definition is GroupedVariableDefinition group)
            {
                return BaseExpressionForAnyoneAskedThisQuestion(group, includeResultTypes);
            }
            if (variable?.Definition is SingleGroupVariableDefinition singleGroupVariableDefinition)
            {
                return BaseExpressionForAnyoneAskedThisQuestion(singleGroupVariableDefinition, includeResultTypes);
            }
            var responseIdentifier = $"response.{variableIdentifier}";
            return GetExistsConditionForIdentifier(responseIdentifier, includeResultTypes ? resultTypes : null);
        }

        private string BaseExpression(VariableComponent component, bool includeResultTypes)
        {
            switch (component)
            {
                case InclusiveRangeVariableComponent inclusiveRangeVariableComponent:
                    return RawFieldExpression(inclusiveRangeVariableComponent.FromVariableIdentifier, includeResultTypes, inclusiveRangeVariableComponent.GetResultTypes());
                case InstanceListVariableComponent instanceListVariableComponent:
                    return RawFieldExpression(instanceListVariableComponent.FromVariableIdentifier, includeResultTypes, instanceListVariableComponent.GetResultTypes());
                case CompositeVariableComponent compositeVariableComponent:
                    {
                        var expressions = compositeVariableComponent.CompositeVariableComponents.Select(c => BaseExpression(c, includeResultTypes));
                        var myOperator = compositeVariableComponent.CompositeVariableSeparator == CompositeVariableSeparator.And ? " and " : " or ";
                        return "(" + string.Join(myOperator, expressions) + ")";
                    }
                case SurveyIdVariableComponent surveyIdVariableComponent:
                    return "1";
                default:
                    return null;
            }
        }
    }
}
