using BrandVue.EntityFramework.MetaData;
using BrandVue.EntityFramework.MetaData.BaseSizes;
using BrandVue.EntityFramework.MetaData.VariableDefinitions;
using BrandVue.SourceData.Calculation.Expressions;
using BrandVue.SourceData.Entity;
using BrandVue.SourceData.Measures;
using BrandVue.SourceData.Respondents;
using BrandVue.SourceData.Variable;
using NSubstitute;
using NUnit.Framework;

namespace Test.BrandVue.SourceData.Calculation
{
    [TestFixture]
    internal class BaseExpressionGeneratorTests
    {
        private Measure _measureWithAllRespondentsBase;
        private Measure _measureWithSawThisChoiceBase;
        private Measure _measureWithSawThisQuestionBase;
        private Measure _measureWithFieldExpressionBase;
        private Measure _measureCreatedByUser;
        private Measure _measureCreatedByUserWithNullVariableConfigurationId;

        private MetricConfiguration _metricWithAllRespondentsBase;
        private MetricConfiguration _metricWithSawThisChoiceBase;
        private MetricConfiguration _metricWithSawThisQuestionBase;
        private MetricConfiguration _metricWithFieldExpressionBase;
        private MetricConfiguration _metricCreatedByUser;
        private MetricConfiguration _metricCreatedByUserWithNullVariableConfigurationId;

        private IReadableMetricConfigurationRepository _metricConfigRepository;
        private IResponseFieldManager _responseFieldManager;
        private IReadableVariableConfigurationRepository _variableConfigRepository;
        private IFieldExpressionParser _fieldExpressionParser;

        private BaseExpressionGenerator _baseExpressionGenerator;

        private readonly int _baseVariableId = 1;
        private readonly int _customVariableId = 2;
        private readonly string customBaseFieldExpression = "any((answer != None and answer >= 0)";

        [OneTimeSetUp]
        public void OneTimeSetUp()
        {
            PopulateMeasureAndMetric("AllRespondents", ref _metricWithAllRespondentsBase, ref _measureWithAllRespondentsBase);

            const string sawThisChoiceBaseField = "SawThisChoice_asked";
            PopulateMeasureAndMetric("SawThisChoice", ref _metricWithSawThisChoiceBase, ref _measureWithSawThisChoiceBase, sawThisChoiceBaseField);
            PopulateMeasureAndMetric("SawThisQuestion", ref _metricWithSawThisQuestionBase, ref _measureWithSawThisQuestionBase);
            PopulateMeasureAndMetric("FieldExpressionBase", ref _metricWithFieldExpressionBase, ref _measureWithFieldExpressionBase);
            _measureWithFieldExpressionBase.BaseVariableConfigurationId = _baseVariableId;
            _metricWithFieldExpressionBase.BaseVariableConfigurationId = _baseVariableId;

            PopulateMeasureAndMetric("VariableCreatedByUser", ref _metricCreatedByUser, ref _measureCreatedByUser);
            _measureCreatedByUser.GenerationType = AutoGenerationType.Original;
            _measureCreatedByUser.VariableConfigurationId = _customVariableId;
            _metricCreatedByUser.IsAutoGenerated = AutoGenerationType.Original;
            _metricCreatedByUser.VariableConfigurationId = _customVariableId;

            PopulateMeasureAndMetric("VariableCreatedByUserWithNullVariableConfigurationId", ref _metricCreatedByUserWithNullVariableConfigurationId, ref _measureCreatedByUserWithNullVariableConfigurationId);
            _measureCreatedByUserWithNullVariableConfigurationId.GenerationType = AutoGenerationType.Original;
            _metricCreatedByUserWithNullVariableConfigurationId.IsAutoGenerated = AutoGenerationType.Original;

            _metricConfigRepository = Substitute.For<IReadableMetricConfigurationRepository>();
            _metricConfigRepository.Get(_measureWithAllRespondentsBase.Name).Returns(_metricWithAllRespondentsBase);
            _metricConfigRepository.Get(_measureWithFieldExpressionBase.Name).Returns(_metricWithFieldExpressionBase);
            _metricConfigRepository.Get(_measureWithSawThisChoiceBase.Name).Returns(_metricWithSawThisChoiceBase);
            _metricConfigRepository.Get(_measureWithSawThisQuestionBase.Name).Returns(_metricWithSawThisQuestionBase);
            _metricConfigRepository.Get(_measureCreatedByUser.Name).Returns(_metricCreatedByUser);
            _metricConfigRepository.Get(_measureCreatedByUserWithNullVariableConfigurationId.Name).Returns(_metricCreatedByUserWithNullVariableConfigurationId);

            var sawThisChoiceFieldEntity = new[] { new EntityType(sawThisChoiceBaseField, sawThisChoiceBaseField, sawThisChoiceBaseField) };
            ResponseFieldDescriptor sawThisChoiceField = new ResponseFieldDescriptor(sawThisChoiceBaseField, sawThisChoiceFieldEntity);

            _responseFieldManager = Substitute.For<IResponseFieldManager>();
            _responseFieldManager.Get("SawThisChoice_asked").Returns(sawThisChoiceField);
            _variableConfigRepository = Substitute.For<IReadableVariableConfigurationRepository>();
            var customBase = new VariableConfiguration()
            {
                Id = 1,
                Definition = new BaseFieldExpressionVariableDefinition()
                {
                    Expression = customBaseFieldExpression
                },
                DisplayName = "Custom base",
                Identifier = "CustomBase"
            };
            var customVariable = new VariableConfiguration()
            {
                Id = _customVariableId,
                Definition = new FieldExpressionVariableDefinition()
                {
                    Expression = customBaseFieldExpression
                },
                DisplayName = "Custom variable",
                Identifier = "CustomVariable"
            };

            _variableConfigRepository.Get(1).Returns(customBase);
            _variableConfigRepository.Get(_customVariableId).Returns(customVariable);

            _fieldExpressionParser = Substitute.For<IFieldExpressionParser>();

            _baseExpressionGenerator = new BaseExpressionGenerator(_metricConfigRepository, _responseFieldManager, _variableConfigRepository, _fieldExpressionParser);
        }

        private void PopulateMeasureAndMetric(string varCode, ref MetricConfiguration newMetric, ref Measure newMeasure, string baseField = null)
        {
            newMetric = new MetricConfiguration()
            {
                Name = varCode,
                VarCode = varCode,
                Field = varCode,
                IsAutoGenerated = AutoGenerationType.CreatedFromField,
                BaseField = baseField
            };

            newMeasure = new Measure()
            {
                Name = varCode,
                VarCode = varCode,
                GenerationType = AutoGenerationType.CreatedFromField,
            };
        }

        [Test]
        public void MeasureWithAllRespondentsBaseDefinitionShouldGetCorrectly()
        {
            var baseExpressionDefinition = new BaseExpressionDefinition() 
            {
               BaseType = BaseDefinitionType.AllRespondents,
               BaseMeasureName = _measureWithAllRespondentsBase.Name
            };
            var measure = _baseExpressionGenerator.GetMeasureWithOverriddenBaseExpression(_measureWithAllRespondentsBase, baseExpressionDefinition);

            Assert.That(measure.BaseExpressionString, Is.EqualTo("1"));
            Assert.That(measure.BaseVariableConfigurationId, Is.Null);
        }

        [Test]
        public void MeasureWithSawThisQuestionBaseDefinitionShouldGetCorrectly()
        {
            var baseExpressionDefinition = new BaseExpressionDefinition()
            {
               BaseType = BaseDefinitionType.SawThisQuestion,
               BaseMeasureName = _measureWithSawThisQuestionBase.Name
            };
            var measure = _baseExpressionGenerator.GetMeasureWithOverriddenBaseExpression(_measureWithSawThisQuestionBase, baseExpressionDefinition);

            Assert.That(measure.BaseExpressionString, Is.EqualTo("len(response.SawThisQuestion())"));
            Assert.That(measure.BaseVariableConfigurationId, Is.Null);
        }

        [Test]
        public void MeasureWithSawThisChoiceBaseDefinitionShouldGetCorrectly()
        {
            var baseExpressionDefinition = new BaseExpressionDefinition()
            {
               BaseType = BaseDefinitionType.SawThisChoice,
               BaseMeasureName = _measureWithSawThisChoiceBase.Name
            };
            var measure = _baseExpressionGenerator.GetMeasureWithOverriddenBaseExpression(_measureWithSawThisChoiceBase, baseExpressionDefinition);

            Assert.That(measure.BaseExpressionString, Is.EqualTo("len(response.SawThisChoice(SawThisChoice_asked=result.SawThisChoice_asked))"));
            Assert.That(measure.BaseVariableConfigurationId, Is.Null);
        }

        [Test]
        public void MeasureWithFieldExpressionBaseDefinitionShouldGetCorrectly()
        {
            var baseExpressionDefinition = new BaseExpressionDefinition()
            {
               BaseType = BaseDefinitionType.AllRespondents,
               BaseMeasureName = _measureWithFieldExpressionBase.Name,
               BaseVariableId = 1
            };
            var measure = _baseExpressionGenerator.GetMeasureWithOverriddenBaseExpression(_measureWithFieldExpressionBase, baseExpressionDefinition);

            Assert.That(measure.BaseExpressionString, Is.EqualTo(customBaseFieldExpression));
            Assert.That(measure.BaseVariableConfigurationId, Is.EqualTo(_baseVariableId));
        }

        [Test]
        [TestCase(BaseDefinitionType.AllRespondents, "1")]
        [TestCase(BaseDefinitionType.SawThisQuestion, "len(response.CustomVariable())")]
        public void VariableCreatedByUserBaseDefinitionShouldGetCorrectly(BaseDefinitionType baseType,
            string expectedBaseExpressionString)
        {
            var baseExpressionDefinition = new BaseExpressionDefinition()
            {
                BaseType = baseType,
                BaseMeasureName = _measureCreatedByUser.Name,
            };
            var measure = _baseExpressionGenerator.GetMeasureWithOverriddenBaseExpression(_measureCreatedByUser, baseExpressionDefinition);

            Assert.That(measure.BaseExpressionString, Is.EqualTo(expectedBaseExpressionString));
            Assert.That(measure.BaseVariableConfigurationId, Is.Null);
        }

        [Test]
        [TestCase(BaseDefinitionType.AllRespondents, "1")]
        [TestCase(BaseDefinitionType.SawThisQuestion, "len(response.VariableCreatedByUserWithNullVariableConfigurationId())")]
        public void MetricWithNullVariableConfigurationIdShouldGetCorrectly(BaseDefinitionType baseType,
            string expectedBaseExpressionString)
        {
            var baseExpressionDefinition = new BaseExpressionDefinition()
            {
                BaseType = baseType,
                BaseMeasureName = _measureCreatedByUserWithNullVariableConfigurationId.Name,
            };
            var measure = _baseExpressionGenerator.GetMeasureWithOverriddenBaseExpression(_measureCreatedByUserWithNullVariableConfigurationId, baseExpressionDefinition);

            Assert.That(measure.BaseExpressionString, Is.EqualTo(expectedBaseExpressionString));
            Assert.That(measure.BaseVariableConfigurationId, Is.Null);
        }
    }
}