// <auto-generated />
using BrandVue.EntityFramework.ResponseRepository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BrandVue.EntityFramework.Migrations
{
    [DbContext(typeof(ResponseDataContext))]
    [Migration("20181105164803_AllowProfileWordles")]
    partial class AllowProfileWordles
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BrandVue.EntityFramework.ResponseRepository.WeightedWordCount", b =>
                {
                    b.Property<string>("Text")
                        .ValueGeneratedOnAdd();

                    b.Property<float>("Result");

                    b.HasKey("Text");

                    b.ToTable("WeightedWordCounts");
                });
#pragma warning restore 612, 618
        }
    }
}
