apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-airflow-logs-azurefile-live
  namespace: live
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  resources:
    requests:
      storage: 5Gi