import React from "react";
import { Collapse } from 'reactstrap';
import style from "./MetricInsights.module.less";
import { useAppDispatch, useAppSelector } from "../state/store";
import { clearLlmInsightResults, fetchLlmInsightsResult, LlmInsightState } from "../state/llmInsightSlice";
import { ResultsState } from "../state/resultsSlice";
import { AnalysisDataState, getDataWrapper } from "./helpers/AnalysisHelper";
import { MixPanel } from './mixpanel/MixPanel';
import { getCurrentPageInfo } from "./helpers/PagesHelper";
import toast from 'react-hot-toast';
import { CorrectnessFeedbackSection } from "./CorrectnessFeedbackSection";
import {useLocation} from "react-router-dom";

const dataState = (llmInsights: LlmInsightState) => llmInsights.error ? AnalysisDataState.Error :
    llmInsights.loading ? AnalysisDataState.Loading : llmInsights.results == null ?
        AnalysisDataState.NoData :
        AnalysisDataState.Show;

interface LlmInsightsPanelProps {
    partId: number;
}

const LlmInsightsPanel: React.FunctionComponent<LlmInsightsPanelProps> = (props) => {
    const dispatch = useAppDispatch();
    const weightedDailyResults = useAppSelector((state) => state.results) as ResultsState;
    const llmInsights = useAppSelector((state) => state.llmInsights) as LlmInsightState;
    const location = useLocation();
    const currentPageInfo = getCurrentPageInfo(location);
    const selectedView = currentPageInfo.viewMenuItem ?? currentPageInfo.activeViews[0];

    const [showDisclaimer, setShowDisclaimer] = React.useState(true);
    const [openInsights, setOpenInsights] = React.useState<Record<number, boolean>>(() => {
        if (!llmInsights?.results) return {};
        return llmInsights.results.aiSummary.reduce((acc, _, index) => ({
            ...acc,
            [index]: true
        }), {});
    });

    React.useEffect(() => {
        const partResults = weightedDailyResults?.results[props.partId];
        const averageResults = weightedDailyResults?.averages?.[props.partId];
        if (weightedDailyResults?.results != null //store initialized
            && partResults
            && ((llmInsights.requested != null && partResults.requested > llmInsights.requested) || llmInsights.results == null) //ensure results actually need updating
            && (averageResults?.length ?? 0) >= (partResults.averagesSelected ?? 0)//all averages loaded
            && ((averageResults?.filter(ar => ar.requested!.getTime() >= partResults.requested!.getTime())?.length ?? 0) == (averageResults?.length ?? 0))
        ) {
            dispatch(fetchLlmInsightsResult({
                request: partResults.request,
                results: partResults.results,
                averages: averageResults,
            }));
            return;
        }
        // clear the results if not requesting insights and there are no results
        if (partResults == null && llmInsights.error == null) {
            dispatch(clearLlmInsightResults());
        }
    }, [weightedDailyResults?.results, weightedDailyResults?.averages, props.partId]);

    React.useEffect(() => {
        if (llmInsights?.results) {
            setOpenInsights(
                llmInsights.results.aiSummary.reduce((acc, _, index) => ({
                    ...acc,
                    [index]: true
                }), {})
            );
        }
    }, [llmInsights?.results]);

    const handleCloseDisclaimer = () => {
        setShowDisclaimer(false);
    };

    const toggleExpandInsight = (index: number) => {
        setOpenInsights(prev => ({
            ...prev,
            [index]: !prev[index]
        }));
    };

    const copyText = (text: string) => {
        navigator.clipboard.writeText(text);
        toast.success("Copied.");
    }

    return getDataWrapper(dataState(llmInsights), () => {

        MixPanel.track("swysOpened", { Part: currentPageInfo.pagePart, ChartType: selectedView.name });
        var sortedInsights = llmInsights?.results?.aiSummary?.slice().sort((a, b) => a.significance < b.significance ? 1 : -1);

        return (sortedInsights != null && sortedInsights.length > 0) ?
            <div id="llm-insight-results" className={style.metricInsightsCardList}>
                {showDisclaimer && (
                    <div className={style.warningBubble}>
                        <div className={style.ailaInfo}>
                            <i className="material-symbols-outlined">info</i>
                        </div>
                        <div>
                            <p className={style.ailaInfo}>This summary is&nbsp;
                                <a href="https://docs.savanta.com/vue/Content/BrandVue/Generating_AI_Summaries.html" target="_blank">
                                    <u>generated by AI.</u>
                                </a>
                            </p>
                            <p>We recommend verifying the key details.</p>
                        </div>
                        <div className="close-side-panel-button" onClick={handleCloseDisclaimer}>
                            <i className="material-symbols-outlined">close</i>
                        </div>
                    </div>
                )}
                {sortedInsights?.map((insight, index) =>
                    <div key={"insight" + index} className={style.metricInsightsCard}>
                        <div className={style.metricInsightsCardTitle}>
                            <i className="float-end align-top material-symbols-outlined clickable" onClick={() => toggleExpandInsight(index)}>
                                {openInsights[index] ? "keyboard_arrow_up" : "keyboard_arrow_down"}
                            </i>
                            <h4>{insight.title} <span className={"material-symbols-outlined clickable"} onClick={() => {
                                copyText(insight.insight)
                            }} role={"copy"}>content_copy</span></h4>
                        </div>
                        <Collapse isOpen={openInsights[index]}>
                            <div className={style.metricInsightsCardInsightList}>
                                <p>{insight.insight}</p>
                            </div>
                            <hr />
                            {llmInsights.results?.id && (
                                <CorrectnessFeedbackSection
                                    id={llmInsights.results.id}
                                    insight={insight}
                                />
                            )}
                        </Collapse>
                    </div>
                )}
            </div> : <div id="llm-insight-results" className={style.metricInsightsCardList}>
                <div className={style.metricInsightsCard}>Nothing of interest this time!</div>
            </div>;
    }, { showHal: true, errorText: llmInsights.error });
}
export default LlmInsightsPanel;