import {Metric} from '../../../metrics/metric';
import DisplayAverage from '../DisplayAverage';
import FiltersBar from '../Reports/Filtering/FiltersBar';
import CrosstabExcelDownload from './CrosstabExcelDownload';
import AddFilterButton, {FilterButtonType} from '../Reports/Filtering/AddFilterButton';
import {CuratedFilters} from '../../../filter/CuratedFilters';
import {
    IAverageDescriptor,
    AverageType,
    CrosstabRequestModel,
    CuratedResultsModel,
    IEntityType,
    IApplicationUser,
    ReportOrder
} from '../../../BrandVueApi';
import {ApplicationConfiguration} from '../../../ApplicationConfiguration';
import {useFilterStateContext} from '../../../filter/FilterStateContext';
import CrosstabLowSampleWarning from './CrosstabLowSampleWarning';
import EntitySetDropdownSelector from '../../EntitySetDropdownSelector';
import { IGoogleTagManager } from "../../../googleTagManager";
import {EntitySet} from "../../../entity/EntitySet";
import {EntityInstance} from "../../../entity/EntityInstance";
import DropdownSelector from '../../../components/dropdown/DropdownSelector';
import FixedPeriodFilterMenus from '../../filters/FixedPeriodFilterMenus';
import {PageHandler} from '../../PageHandler';
import {useEntityConfigurationStateContext} from '../../../entity/EntityConfigurationStateContext';
import FilterDescriptionReadOnly from '../../filters/FilterDescriptionReadOnly';
import {stripHtmlTagsFromHelpText} from '../../helpers/SurveyVueUtils';
import {useDispatch} from "react-redux";
import {
    setActiveEntityInstance,
    setActiveEntitySet,
    setSplitBy
} from "../../../state/entitySelectionSlice";
import { throwIfNullish } from '../../../components/helpers/ThrowHelper';

interface ICrosstabTitleProps {
    selectedMetric: Metric | undefined;
    curatedFilters: CuratedFilters;
    splitByEntityType: IEntityType | undefined;
    user: IApplicationUser | null;
    applicationConfiguration: ApplicationConfiguration;
    resultSortingOrder: ReportOrder;
    includeCounts: boolean;
    highlightLowSample: boolean;
    decimalPlaces:number;
    isLowSample: boolean;
    isSurveyVue: boolean;
    googleTagManager: IGoogleTagManager;
    activeEntitySet: EntitySet | undefined;
    focusInstance: EntityInstance | undefined;
    secondaryEntitySets: EntitySet[];
    numTables: number;
    getRequestModel(): CrosstabRequestModel | CuratedResultsModel | undefined;
    canExportData: boolean;
    averages: IAverageDescriptor[];
    averageTypes: AverageType[];
    pageHandler: PageHandler;
    activeMetrics: Metric[];
    displayMeanValues: boolean;
    hideTotalColumn: boolean;
    showMultipleTablesAsSingle: boolean;
    calculateIndexScores: boolean;
    lowSampleThreshold: number;
    setCreateNewReportModalVisibility(isVisible: boolean, preSelectedMetric?: Metric): void;
    showAddToReportModal(): void;
}

const CrosstabTitle = (props: ICrosstabTitleProps) => {
    const { filters } = useFilterStateContext();
    const { entityConfiguration } = useEntityConfigurationStateContext();
    const dispatch = useDispatch();
    const getQuestionText = () => {
        if (props.selectedMetric) {
            let displayText = props.isSurveyVue ? props.selectedMetric.helpText : props.selectedMetric.measure ?? props.selectedMetric.name;
            displayText = props.selectedMetric.isAutoGeneratedNumeric() ? "Auto grouped: " + displayText : displayText;
            return (
                <div className="question-text bg-transparent">
                    {props.isSurveyVue ?
                        <span>{stripHtmlTagsFromHelpText(displayText)}</span>
                        :
                        <span dangerouslySetInnerHTML={{ __html: displayText }}></span>
                    }
                    {!props.selectedMetric?.eligibleForCrosstabOrAllVue &&
                        <i className="material-symbols-outlined hidden-question-icon"
                           title="This table is only visible to admin users">visibility_off</i>
                    }
                </div>
            );
        }
    }

    const getExportButton = () => {
        return (
            <CrosstabExcelDownload
                selectedMetric={props.selectedMetric}
                numTables={props.numTables}
                getRequestModel={props.getRequestModel}
                canDownload={props.canExportData}
                averages={props.averageTypes}
                displayMeanValues={props.displayMeanValues}
                setCreateNewReportModalVisibility={(isVisible, preSelectedMetric) => {props.setCreateNewReportModalVisibility(isVisible, preSelectedMetric)}}
                showAddToReportModal={() => props.showAddToReportModal()}
            />
        )
    }

    if (filters.length > 0) {
        return (
            <>
                <div className="header-right-flex">
                    {getQuestionText()}
                    <DisplayAverage average={props.curatedFilters.average}
                        metric={props.selectedMetric} />
                </div>
                <div className="header-right-flex">
                    <FiltersBar
                        user={props.user}
                        separateVariables={true}
                        buttonType={FilterButtonType.ShowVariableModal}
                    />
                    <div className="right-hand-section-buttons">
                        <CrosstabLowSampleWarning isLowSample={props.highlightLowSample && props.isLowSample} lowSampleThreshold={props.lowSampleThreshold} />
                        {getExportButton()}
                    </div>
                </div>
            </>
        );
    }

    /*
        We show an entity set picker for every type in the table.
        For example, if a table had a type of "social_media_used" and also applied breaks for a Brand and a Product metric,
        we would show selectors for all three types.

        The rows on the table are considered the "active" entity set, while the sets for the breaks are "secondary"

        If the rows and breaks share a type, we should use the entity set chosen for the rows
    */
    const getEntitySetSelectors = () => {
        if (!props.splitByEntityType) {
            return null;
        }
        const activeAvailableSets = entityConfiguration.getSetsFor(props.splitByEntityType!);
        const availableActiveInstances = entityConfiguration.getAllEnabledInstancesForType(props.splitByEntityType!);

        let primarySelector: JSX.Element | undefined = undefined;
        if (props.activeEntitySet && activeAvailableSets.length > 1) {
            primarySelector = <EntitySetDropdownSelector
                key="primary-entityset-selector"
                googleTagManager={props.googleTagManager}
                pageHandler={props.pageHandler}
                activeEntitySet={props.activeEntitySet}
                focusInstance={throwIfNullish(props.focusInstance, "Focus instance should not be null")}
                updateFocusInstance={(e) => { dispatch(setActiveEntityInstance({ instance : e, entityType: props.splitByEntityType!}));}}
                updateActiveEntitySet={(e) => { dispatch(setActiveEntitySet({entitySet: e}));}}
                availableEntitySets={activeAvailableSets}
                availableInstances={availableActiveInstances}
                entityType={props.splitByEntityType!}
                asButton={true}
                showLabel={false}
                materialIcon={props.activeEntitySet.GetEntitySetIcon()}
            />
        }

        const secondarySelectors = props.secondaryEntitySets.map((set: EntitySet) => {
            const availableSets = entityConfiguration.getSetsFor(set.type);
            const availableInstances = entityConfiguration.getAllEnabledInstancesForType(set.type);

            if (availableSets.length > 1) {
                return <EntitySetDropdownSelector
                    key="secondary-entityset-selector"
                    googleTagManager={props.googleTagManager}
                    pageHandler={props.pageHandler}
                    activeEntitySet={set}
                    //TODO: Handle how columns should update the focus brand
                    focusInstance={EntityInstance.AllInstances}
                    updateFocusInstance={(e) => { dispatch(setActiveEntityInstance({ instance : e, entityType: set.type}));}}
                    updateActiveEntitySet={(e) => { dispatch(setActiveEntitySet({entitySet: e}));}}
                    availableEntitySets={availableSets}
                    availableInstances={availableInstances}
                    entityType={set.type}
                    asButton={true}
                    showLabel={false}
                    materialIcon={set.GetEntitySetIcon()}
                />
            }
        });

        const allSelectors = [primarySelector].concat(secondarySelectors)
        allSelectors.sort((a, b) => {
            const typeA = a?.props.entityType;
            const typeB = b?.props.entityType;

            if (props.selectedMetric) {
                const entityCombination = props.selectedMetric.entityCombination;
                const indexOfTypeA = entityCombination.findIndex(t => t.identifier === typeA.name);
                const indexOfTypeB = entityCombination.findIndex(t => t.identifier === typeB.name);
                if (indexOfTypeA === -1 && indexOfTypeB === -1) {
                    return 0;
                }

                if (indexOfTypeA === -1) {
                    return 1;
                }

                if (indexOfTypeB === -1) {
                    return -1;
                }

                return indexOfTypeA - indexOfTypeB;
            }
            return 0;
        });
        return allSelectors;
    };

    const getCrosstabTitleClassName = () => {
        let className = 'header-right-flex'
        className = props.isSurveyVue ? className : className + " column";
        return props.selectedMetric ? className : className + " disable-page";
    }
    return (
        <div className={getCrosstabTitleClassName()}>
            {getQuestionText()}
            <div className={`right-hand-section${!props.isSurveyVue ? " full-width" : ""}`}>
                {props.isSurveyVue && <DisplayAverage average={props.curatedFilters.average} metric={props.selectedMetric} />}
                <div className={`right-hand-section-buttons${!props.isSurveyVue ? " spaced" : ""}`}>
                    <div className="right-hand-section-buttons-left">
                    {!props.isSurveyVue &&
                        <div className="right-hand-section-buttons-left">
                            {getEntitySetSelectors()}
                                {props.selectedMetric && props.selectedMetric.entityCombination.length > 1 && props.splitByEntityType &&
                                    <DropdownSelector<IEntityType>
                                        label="splitBy"
                                        items={props.selectedMetric.entityCombination}
                                        selectedItem={props.splitByEntityType}
                                        onSelected={(item) => { dispatch(setSplitBy(item))  }}
                                        itemDisplayText={e => `Split by ${e.displayNameSingular.toLocaleLowerCase()}`}
                                        asButton={true}
                                        showLabel={false}
                                        itemKey={e => e.identifier}
                                        materialIcon = "call_split"
                                        textOverride = {props.splitByEntityType?.displayNameSingular}
                                    />
                                }
                                <FixedPeriodFilterMenus userVisibleAverages={props.averages}
                                    pageHandler={props.pageHandler}
                                    activeMetrics={props.selectedMetric ? [props.selectedMetric] : []}
                                    curatedFilters={props.curatedFilters}
                                    applicationConfiguration={props.applicationConfiguration}
                                    googleTagManager={props.googleTagManager}
                                    className={"crosstab-title-date-selector"}
                                    buttonAttr={{ className: "hollow-button" }}
                                    showRollingAverages={true}
                                />
                        </div>
                    }
                    </div>
                    <div className="right-hand-section-buttons-right">
                        {props.isSurveyVue &&
                            <AddFilterButton
                                end={true}
                                separateVariables={true}
                                buttonType={FilterButtonType.ShowVariableModal}
                            />
                        }
                        <CrosstabLowSampleWarning isLowSample={props.highlightLowSample && props.isLowSample} lowSampleThreshold={props.lowSampleThreshold} />
                        {getExportButton()}
                    </div>
                </div>
            </div>
            {!props.isSurveyVue &&
                <FilterDescriptionReadOnly pageHandler={props.pageHandler} />
            }
        </div>
    );
};

export default CrosstabTitle;