export const SET_METRIC_ENABLED = "SET_METRIC_ENABLED";
export const SET_METRIC_FILTER_ENABLED = "SET_METRIC_FILTER_ENABLED";
export const SET_ELIGIBLE_FOR_CROSSTAB_OR_ALLVUE = "SET_ELIGIBLE_FOR_CROSSTAB_OR_ALLVUE";
export const UPDATE_METRIC_DEFAULT_SPLIT_BY = "UPDATE_METRIC_DEFAULT_SPLIT_BY";
export const UPDATE_CALCULATION_TYPE = "UPDATE_CALCULATION_TYPE";
export const UPDATE_BASE_VARIABLE = "UPDATE_BASE_VARIABLE";
export const RELOAD_METRICS = "RELOAD_METRICS";
export const UPDATE_MODAL_DATA = "UPDATE_MODAL_DATA";