import { metricsThatMatchSearchText, separateMetricsByGenerationType } from "./metricHelper";
import { Metric } from "./metric";
import { DropdownItem } from "reactstrap";
import { getMetricDisplayName } from "../components/helpers/SurveyVueUtils";

export const getMatchedMetrics = (metrics: Metric[],
    searchQuery: string,
    groupCustomVariables: boolean,
    addBreak: (metric: Metric) => void,
    hasWarning: boolean) => {        

    let matchedMetrics = metrics;

    if (searchQuery && searchQuery.trim() != '') {
        matchedMetrics = metricsThatMatchSearchText(searchQuery, matchedMetrics);
    }

    if (!groupCustomVariables) {
        return (
            <div className={hasWarning ? "variable-has-warning" : ""}>
                {matchedMetrics.map(metric => getMetricElement(metric, groupCustomVariables, addBreak))}
            </div>
        );
    }

    const [customMetrics, standardMetrics, autoGeneratedNumericMetrics] = separateMetricsByGenerationType(matchedMetrics);

    return (
        <div className={hasWarning ? "variable-has-warning" : ""}>
            {customMetrics.length > 0 && <div className="dropdown-item title">Custom variables</div>}
            {customMetrics.map(metric => getMetricElement(metric, groupCustomVariables, addBreak))}
            {autoGeneratedNumericMetrics.length > 0 && <div className="dropdown-item title">Automatically generated</div>}
            {autoGeneratedNumericMetrics.map(metric => getMetricElement(metric, groupCustomVariables, addBreak))}
            {standardMetrics.length > 0 && <div className="dropdown-item title">Questions</div>}
            {standardMetrics.map(metric => getMetricElement(metric, groupCustomVariables, addBreak))}
        </div>
    )
}

const getDisplayName = (metric: Metric, groupCustomVariables: boolean) => {
    if (!groupCustomVariables) {
        return metric.displayName;
    }

    return getMetricDisplayName(metric);
}

const getMetricElement = (metric: Metric, groupCustomVariables: boolean, addBreak: (m:Metric) => void) => {
    const displayText = getDisplayName(metric, groupCustomVariables,);
    return (
        <DropdownItem key={metric.name} onClick={() => addBreak(metric)} title={metric.displayName} className="tabbed">
            <div className="name-container">
                {((groupCustomVariables && (!metric.isBasedOnCustomVariable || metric.isAutoGeneratedNumeric()))) && <span className='var-name'>{metric.displayName}</span>}
                <span className='title' title={displayText}>{displayText}</span>
            </div>
        </DropdownItem>
    );
}