using BrandVue.EntityFramework.MetaData;
using Microsoft.EntityFrameworkCore;
using BrandVue.EntityFramework.Exceptions;
using Microsoft.Extensions.Logging;
using BrandVue.EntityFramework.MetaData.VariableDefinitions;

namespace BrandVue.SourceData.Measures
{
    public class MetricConfigurationRepositorySql : IMetricConfigurationRepository
    {
        private readonly IDbContextFactory<MetaDataContext> _dbContextFactory;
        private readonly IProductContext _productContext;
        private readonly IMetricFactory _metricFactory;
        private readonly ILogger<IMetricConfigurationRepository> _logger;

        public MetricConfigurationRepositorySql(IDbContextFactory<MetaDataContext> dbContextFactory,
            IProductContext productContext, IMetricFactory metricFactory,
            ILogger<IMetricConfigurationRepository> logger)
        {
            _dbContextFactory = dbContextFactory;
            _productContext = productContext;
            _metricFactory = metricFactory;
            _logger = logger;
        }

        public IReadOnlyCollection<MetricConfiguration> GetAll()
        {
            using var dbContext = _dbContextFactory.CreateDbContext();
            return ForProductContext(dbContext).ToArray();
        }

        public MetricConfiguration Get(int id)
        {
            using var dbContext = _dbContextFactory.CreateDbContext();
            return ForProductContext(dbContext).FirstOrDefault(mc => mc.Id == id);
        }

        public MetricConfiguration Get(string name)
        {
            using var dbContext = _dbContextFactory.CreateDbContext();
            return ForProductContext(dbContext).FirstOrDefault(mc => mc.Name == name );
        }

        public void CreateMany(IReadOnlyCollection<MetricConfiguration> metricConfigurations)
        {
            var metricsToInsert = new List<MetricConfiguration>(metricConfigurations.Count);
            using var dbContext = _dbContextFactory.CreateDbContext();
            // PERF: Load all one time, rather than query in loop
            ForProductContext(dbContext).Load();
            var forProductContext = dbContext.MetricConfigurations.Local.AsQueryable().ForProductContext(_productContext);

            foreach (var metricConfiguration in metricConfigurations)
            {
                var validationError = GetValidationErrorOrNull(metricConfiguration, true, forProductContext);
                if (string.IsNullOrEmpty(validationError))
                {
                    metricsToInsert.Add(metricConfiguration);
                }
                else
                {
                    _logger.LogError(validationError);
                }
            }

            foreach (var metric in metricsToInsert)
            {
                dbContext.Entry(metric).State = EntityState.Added;
            }
            dbContext.SaveChanges();
        }

        public HashSet<string> GetDirectlyUsedVariableIdentifiers(IEnumerable<VariableConfiguration> questionVariableDefinitions)
        {
            using var dbContext = _dbContextFactory.CreateDbContext();

            var validMetricConfigurations = ForProductContext(dbContext)
                .AsEnumerable();

            var variableDefinitions = new List<QuestionVariableDefinition>();
            foreach (var metric in validMetricConfigurations.Where(metric => metric.VariableConfigurationId != null))
            {
                var variable = questionVariableDefinitions.FirstOrDefault(q => q.Id == metric.VariableConfigurationId);
                if (variable?.Definition is QuestionVariableDefinition qvd)
                {
                    variableDefinitions.Add(qvd);
                }
            }

            var fieldNameAsQueryable = validMetricConfigurations
                .Where(mc => mc.IsAutoGenerated != AutoGenerationType.CreatedFromNumeric)
                .Where(mc => !string.IsNullOrEmpty(mc.Field)).Select(mc => mc.Field)
                .Union(validMetricConfigurations.Where(mc => !string.IsNullOrEmpty(mc.Field2)).Select(mc => mc.Field2))
                .Union(validMetricConfigurations.Where(mc => !string.IsNullOrEmpty(mc.BaseField)).Select(mc => mc.BaseField))
                .Union(variableDefinitions.Select(v => v.QuestionVarCode));

            return fieldNameAsQueryable.ToHashSet();
        }

        public void Create(MetricConfiguration metricConfiguration, bool shouldValidate=true)
        {
            ValidateMetricConfiguration(metricConfiguration, true, shouldValidate);

            using var dbContext = _dbContextFactory.CreateDbContext();
            dbContext.MetricConfigurations.Entry(metricConfiguration).State = EntityState.Added;
            dbContext.SaveChanges();
        }

        public void Update(MetricConfiguration metricConfiguration, bool shouldValidate = true)
        {
            ValidateMetricConfiguration(metricConfiguration, false, shouldValidate);

            using var dbContext = _dbContextFactory.CreateDbContext();
            // It is assumed the primary key is present so we can attach
            dbContext.MetricConfigurations.Update(metricConfiguration);
            dbContext.SaveChanges();
        }

        public void Delete(MetricConfiguration metricConfiguration) => Delete(metricConfiguration.Id);

        public void Delete(int metricConfigurationId)
        {
            if (metricConfigurationId <= 0)
            {
                ThrowValidationException("Invalid metric configuration id");
            }

            using var dbContext = _dbContextFactory.CreateDbContext();
            // Set the primary key to be able to track
            var metricToDelete = new MetricConfiguration { Id = metricConfigurationId };
            dbContext.MetricConfigurations.Remove(metricToDelete);
            dbContext.SaveChanges();
        }

        private void ValidateMetricConfiguration(MetricConfiguration metricConfiguration, bool forInsert, bool shouldValidate=true)
        {
            using var dbContext = _dbContextFactory.CreateDbContext();
            var validationError = GetValidationErrorOrNull(metricConfiguration, forInsert, ForProductContext(dbContext), shouldValidate);
            if (validationError != null) ThrowValidationException(validationError);
        }

        private string GetValidationErrorOrNull(MetricConfiguration metricConfiguration, bool forInsert, IQueryable<MetricConfiguration> existing, bool shouldValidate=true)
        {
            if (forInsert ^ metricConfiguration.Id == 0)
            {
                return $"Id field {(forInsert ? "must not" : "must")} have value";
            }

            if (forInsert && NameAlreadyExists(existing, metricConfiguration))
            {
                return $"Metric already exists with name: {metricConfiguration.Name}";
            }

            if (string.IsNullOrEmpty(metricConfiguration.ProductShortCode))
            {
                metricConfiguration.ProductShortCode = _productContext.ShortCode;
            }
            if (string.IsNullOrEmpty(metricConfiguration.SubProductId) && !string.IsNullOrEmpty(_productContext.SubProductId))
            {
                metricConfiguration.SubProductId = _productContext.SubProductId;
            }

            if (metricConfiguration.ProductShortCode != _productContext.ShortCode)
            {
                return $"ProductShortCode field value must be empty or equal to current Vue's product short code: {_productContext.ShortCode}";
            }

            if (shouldValidate && !_metricFactory.TryCreateMetric(metricConfiguration, out var _, out var failureMessage))
            {
                return failureMessage;
            }

            if (!string.IsNullOrEmpty(metricConfiguration.MarketAverageBaseMeasure))
            {
                using var dbContext = _dbContextFactory.CreateDbContext();
                var marketAverageBaseMeasure = ForProductContext(dbContext).SingleOrDefault(mc => mc.Name == metricConfiguration.MarketAverageBaseMeasure);
                if (marketAverageBaseMeasure == null)
                {
                    return "MarketAverageBaseMeasure with that name not found in database";
                }
            }

            return null;
        }

        private bool NameAlreadyExists(IQueryable<MetricConfiguration> allExisting,
            MetricConfiguration metricConfiguration) =>
            allExisting.Any(mc => mc.Name == metricConfiguration.Name);

        public IQueryable<MetricConfiguration> ForProductContext(MetaDataContext dbContext) => dbContext.MetricConfigurations.ForProductContext(_productContext);

        private static void ThrowValidationException(string message) => throw new BadRequestException(message);
    }
}
