create or alter table raw_survey.surveys (
    survey_id number(10, 0) not null,
    survey_structure_id number(10, 0),
    company_id number(10, 0),
    start_date timestamp_ntz(3) not null,
    end_date timestamp_ntz(3),
    status number(10, 0),
    initiated_date timestamp_ntz(3) not null,
    unique_survey_id varchar(50),
    custom_survey_tags varchar(16777216),
    salt varchar(36) not null,
    pii_cleansed_date timestamp_ntz(3),
    period_type number(10, 0) not null,
    period_number number(10, 0),
    period_start_time timestamp_ntz(3),
    file_download_guid varchar(36) not null,
    auto_close boolean not null,
    auth_company_id varchar(50),
    survey_type number(10, 0) not null,
    portal_id number(10, 0),
    portal_visible boolean not null,
    portal_name varchar(200),
    notification_emails varchar(1000),
    name varchar(100),
    kimble_proposal_id varchar(100),
    email_server_name varchar(50),
    brand_id number(10, 0) not null
);
