// <auto-generated />
using System;
using BrandVue.EntityFramework.MetaData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BrandVue.EntityFramework.Migrations.MetaData
{
    [DbContext(typeof(MetaDataContext))]
    [Migration("20200529132641_AddColourConfiguration")]
    partial class AddColourConfiguration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.Bookmark", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AppBase")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("CreatedByIpAddress")
                        .IsRequired();

                    b.Property<string>("CreatedByUserName")
                        .IsRequired();

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateLastGenerated");

                    b.Property<DateTime?>("DateLastUsed");

                    b.Property<long>("GenerationCount");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1600)
                        .IsUnicode(false);

                    b.Property<long>("UseCount");

                    b.HasKey("Id");

                    b.HasIndex("AppBase", "Url")
                        .IsUnique();

                    b.ToTable("Bookmarks");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.ColourConfiguration", b =>
                {
                    b.Property<string>("ProductShortCode")
                        .HasMaxLength(20);

                    b.Property<string>("Organisation")
                        .HasMaxLength(20);

                    b.Property<string>("EntityType")
                        .HasMaxLength(40);

                    b.Property<int>("EntityInstanceId");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasMaxLength(7);

                    b.HasKey("ProductShortCode", "Organisation", "EntityType", "EntityInstanceId");

                    b.ToTable("ColourConfigurations");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.SupportableUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated");

                    b.Property<string>("FreshchatConversationId");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("SupportableUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
