// <auto-generated />
using System;
using BrandVue.EntityFramework.MetaData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BrandVue.EntityFramework.Migrations.MetaData
{
    [DbContext(typeof(MetaDataContext))]
    [Migration("20201001165632_AddPageConfiguration")]
    partial class AddPageConfiguration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.Bookmark", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AppBase")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("CreatedByIpAddress")
                        .IsRequired();

                    b.Property<string>("CreatedByUserName")
                        .IsRequired();

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateLastGenerated");

                    b.Property<DateTime?>("DateLastUsed");

                    b.Property<long>("GenerationCount");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1600)
                        .IsUnicode(false);

                    b.Property<long>("UseCount");

                    b.HasKey("Id");

                    b.HasIndex("AppBase", "Url")
                        .IsUnique();

                    b.ToTable("Bookmarks");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.ChartConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsDraft");

                    b.Property<string>("MetricDefinition")
                        .IsRequired();

                    b.Property<string>("ProductShortCode")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("ChartConfigurations");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.ColourConfiguration", b =>
                {
                    b.Property<string>("ProductShortCode")
                        .HasMaxLength(20);

                    b.Property<string>("Organisation")
                        .HasMaxLength(50);

                    b.Property<string>("EntityType")
                        .HasMaxLength(40);

                    b.Property<int>("EntityInstanceId");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasMaxLength(7);

                    b.HasKey("ProductShortCode", "Organisation", "EntityType", "EntityInstanceId");

                    b.ToTable("ColourConfigurations");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.MetricConfig.DbMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BaseField");

                    b.Property<string>("BaseVals");

                    b.Property<string>("CalType");

                    b.Property<string>("Category");

                    b.Property<bool>("DisableFilter");

                    b.Property<bool>("DisableMeasure");

                    b.Property<bool>("EligibleForMetricComparison");

                    b.Property<string>("ExcludeList");

                    b.Property<int?>("ExcludeWaves");

                    b.Property<string>("Field");

                    b.Property<string>("Field2");

                    b.Property<string>("FieldExpression");

                    b.Property<string>("FieldOp");

                    b.Property<string>("FilterGroup");

                    b.Property<bool>("FilterMulti");

                    b.Property<string>("FilterValueMapping");

                    b.Property<string>("HelpText");

                    b.Property<bool>("InversedTargetValue");

                    b.Property<string>("KeyImage");

                    b.Property<string>("MarketAverageBaseMeasure");

                    b.Property<int?>("Max");

                    b.Property<string>("Measure");

                    b.Property<int?>("Min");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("NumFormat");

                    b.Property<int?>("PreNormalisationMaximum");

                    b.Property<int?>("PreNormalisationMinimum");

                    b.Property<string>("ProductShortCode")
                        .IsRequired();

                    b.Property<DateTime>("StartDate");

                    b.Property<string>("SubCategory");

                    b.Property<string>("Subset");

                    b.Property<string>("TrueVals");

                    b.HasKey("Id");

                    b.HasIndex("Name", "ProductShortCode")
                        .IsUnique();

                    b.ToTable("Metrics");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.Page.DbPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AverageGroup");

                    b.Property<string>("ChildPages");

                    b.Property<string>("DisplayName");

                    b.Property<string>("HelpText");

                    b.Property<string>("Layout");

                    b.Property<string>("MenuIcon");

                    b.Property<int>("MinUserLevel");

                    b.Property<string>("Name");

                    b.Property<string>("PageTitle");

                    b.Property<string>("PageType");

                    b.Property<string>("ProductShortCode");

                    b.Property<bool>("StartPage");

                    b.Property<string>("Subset");

                    b.HasKey("Id");

                    b.ToTable("Pages");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.Page.DbPane", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Height");

                    b.Property<string>("PageName");

                    b.Property<string>("PaneId");

                    b.Property<string>("PaneType");

                    b.Property<string>("ProductShortCode");

                    b.Property<string>("Spec");

                    b.Property<string>("Spec2");

                    b.Property<string>("Subset");

                    b.Property<int>("View");

                    b.HasKey("Id");

                    b.ToTable("Panes");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.Page.DbPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AutoMetrics");

                    b.Property<string>("AutoPanes");

                    b.Property<string>("Colours");

                    b.Property<string>("DefaultSplitBy");

                    b.Property<bool?>("Disabled");

                    b.Property<string>("Filters");

                    b.Property<string>("HelpText");

                    b.Property<string>("Ordering");

                    b.Property<string>("OrderingDirection");

                    b.Property<string>("PaneId");

                    b.Property<string>("PartType");

                    b.Property<string>("ProductShortCode");

                    b.Property<string>("Sections");

                    b.Property<string>("Spec1");

                    b.Property<string>("Spec2");

                    b.Property<string>("Spec3");

                    b.Property<string>("XRange");

                    b.Property<string>("YRange");

                    b.HasKey("Id");

                    b.ToTable("Parts");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.SupportableUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated");

                    b.Property<string>("FreshchatConversationId");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("SupportableUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
