namespace BrandVue.EntityFramework.Migrations.MetaData
{
    public partial class UpdateInvalidFieldNames : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            /* 
             * Our autogenerated field names are invalid python variable names because they contain brackets.
             * Generated names used to be of the format "{word}_{word}_{word} ({varCode})"
             * And we want the new format to be "{word}_{word}_{word}_{varCode}".
             * 
             * Additionally, python variables cannot start with numbers, so if we have any fields where the first character is numeric we just prepend an "_" to make it valid.
             */
            migrationBuilder.Sql(@"
UPDATE [dbo].[MetricConfigurations]
SET Field = REPLACE(REPLACE(Field, ' (', '_'), ')', '')
WHERE Field LIKE '%(%'
 
UPDATE [dbo].[MetricConfigurations]
SET Field = CONCAT('_', Field)
WHERE ISNUMERIC(SUBSTRING(LTRIM(Field), 1, 1)) = 1 

UPDATE [dbo].[MetricConfigurations]
SET BaseField = REPLACE(REPLACE(BaseField, ' (', '_'), ')', '')
WHERE BaseField LIKE '%(%'

UPDATE [dbo].[MetricConfigurations]
SET BaseField = CONCAT('_', BaseField)
WHERE ISNUMERIC(SUBSTRING(LTRIM(BaseField), 1, 1)) = 1");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
