// <auto-generated />
using System;
using BrandVue.EntityFramework.MetaData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BrandVue.EntityFramework.Migrations.MetaData
{
    [DbContext(typeof(MetaDataContext))]
    [Migration("20210323151406_AddSubsetColumnToDbPane")]
    partial class AddSubsetColumnToDbPane
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.Bookmark", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AppBase")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CreatedByIpAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByUserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateLastGenerated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastUsed")
                        .HasColumnType("datetime2");

                    b.Property<long>("GenerationCount")
                        .HasColumnType("bigint");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1600)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1600)");

                    b.Property<long>("UseCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AppBase", "Url")
                        .IsUnique();

                    b.ToTable("Bookmarks");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.ColourConfiguration", b =>
                {
                    b.Property<string>("ProductShortCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Organisation")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EntityType")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("EntityInstanceId")
                        .HasColumnType("int");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.HasKey("ProductShortCode", "Organisation", "EntityType", "EntityInstanceId");

                    b.ToTable("ColourConfigurations");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.MappedFields.InstanceMapping", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("FromValuesExpression")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ToEntityInstanceId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("ToEntityInstanceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeMappingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TypeMappingId");

                    b.ToTable("InstanceMappings");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.MappedFields.MappedField", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OriginalFieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductShortCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ProductShortCode", "FieldName")
                        .IsUnique();

                    b.ToTable("MappedFields");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.MappedFields.TypeMapping", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("FromEntityTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFromEntityType")
                        .HasColumnType("bit");

                    b.Property<int>("MappedFieldId")
                        .HasColumnType("int");

                    b.Property<string>("ToEntityTypeDisplayNamePlural")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToEntityTypeDisplayNameSingular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToEntityTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MappedFieldId");

                    b.ToTable("TypeMappings");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.MetricConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("BaseExpression")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BaseField")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BaseVals")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CalcType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DisableFilter")
                        .HasColumnType("bit");

                    b.Property<bool>("DisableMeasure")
                        .HasColumnType("bit");

                    b.Property<bool>("DownIsGood")
                        .HasColumnType("bit");

                    b.Property<bool>("EligibleForMetricComparison")
                        .HasColumnType("bit");

                    b.Property<string>("ExcludeList")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExcludeWaves")
                        .HasColumnType("int");

                    b.Property<string>("Field")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Field2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldExpression")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldOp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilterGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FilterMulti")
                        .HasColumnType("bit");

                    b.Property<string>("FilterValueMapping")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HelpText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InversedTargetValue")
                        .HasColumnType("bit");

                    b.Property<string>("KeyImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarketAverageBaseMeasure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Max")
                        .HasColumnType("int");

                    b.Property<string>("Measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Min")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NumFormat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PreNormalisationMaximum")
                        .HasColumnType("int");

                    b.Property<int?>("PreNormalisationMinimum")
                        .HasColumnType("int");

                    b.Property<string>("ProductShortCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<float?>("ScaleFactor")
                        .HasColumnType("real");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Subset")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrueVals")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name", "ProductShortCode", "SubProductId")
                        .IsUnique()
                        .HasFilter("[SubProductId] IS NOT NULL");

                    b.ToTable("MetricConfigurations");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.Page.DbPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("AverageGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HelpText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Layout")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MenuIcon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MinUserLevel")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("PageDisplayIndex")
                        .HasColumnType("int");

                    b.Property<string>("PageTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PageType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("ProductShortCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Roles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("StartPage")
                        .HasColumnType("bit");

                    b.Property<string>("Subset")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductShortCode", "Name")
                        .IsUnique()
                        .HasFilter("[ProductShortCode] IS NOT NULL AND [Name] IS NOT NULL");

                    b.ToTable("Pages");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.Page.DbPane", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<string>("PageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaneId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PaneType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductShortCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Spec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Spec2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subset")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("View")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductShortCode", "PaneId")
                        .IsUnique()
                        .HasFilter("[ProductShortCode] IS NOT NULL AND [PaneId] IS NOT NULL");

                    b.ToTable("Panes");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.Page.DbPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("AutoMetrics")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AutoPanes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Colours")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultAverageId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultSplitBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Filters")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HelpText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ordering")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderingDirection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaneId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PartType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductShortCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Sections")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Spec1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Spec2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Spec3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XRange")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YRange")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductShortCode", "PaneId");

                    b.ToTable("Parts");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.SupportableUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("FreshchatConversationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("SupportableUsers");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.Weighting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("FieldGroupToFieldNameToMapping")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("QuotaCellKeyToWeighting")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SubsetId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "SubProductId", "SubsetId")
                        .IsUnique()
                        .HasFilter("[ProductId] IS NOT NULL AND [SubProductId] IS NOT NULL AND [SubsetId] IS NOT NULL");

                    b.ToTable("Weightings");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.MappedFields.InstanceMapping", b =>
                {
                    b.HasOne("BrandVue.EntityFramework.MetaData.MappedFields.TypeMapping", null)
                        .WithMany("InstanceMappings")
                        .HasForeignKey("TypeMappingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.MappedFields.TypeMapping", b =>
                {
                    b.HasOne("BrandVue.EntityFramework.MetaData.MappedFields.MappedField", null)
                        .WithMany("TypeMappings")
                        .HasForeignKey("MappedFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.MappedFields.MappedField", b =>
                {
                    b.Navigation("TypeMappings");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.MappedFields.TypeMapping", b =>
                {
                    b.Navigation("InstanceMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
