namespace BrandVue.EntityFramework.Migrations.MetaData
{
    public partial class AddIsAutoGeneratedToMetricConfiguration : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<bool>(
                name: "IsAutoGenerated",
                table: "MetricConfigurations",
                type: "bit",
                nullable: false,
                defaultValue: true);

            const string sql = "UPDATE MetricConfigurations " +
                                "SET isAutoGenerated = 0 " +
                                "WHERE " +
                                    "ProductShortCode <> 'survey' " +
                                "OR " +
                                "(" +
                                    "ProductShortCode = 'survey' " +
                                    "AND " +
                                    "( " +
                                        "FieldExpression IS NOT NULL " +
                                        "OR VariableConfigurationId IS NOT NULL " +
                                        "OR Category IS NOT NULL " +
                                    ")" +
                                ")";
                
            migrationBuilder.Sql(sql);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "IsAutoGenerated",
                table: "MetricConfigurations");
        }
    }
}
