#nullable disable

namespace BrandVue.EntityFramework.Migrations.MetaData
{
    public partial class ChangeMetricConfigurationAutoGenerationTypeToEnum : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<byte>(
                name: "IsAutoGenerated",
                table: "MetricConfigurations",
                type: "tinyint",
                nullable: false,
                oldClrType: typeof(int),
                oldType: "int");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<int>(
                name: "IsAutoGenerated",
                table: "MetricConfigurations",
                type: "int",
                nullable: false,
                oldClrType: typeof(byte),
                oldType: "tinyint");
        }
    }
}
