// <auto-generated />
using System;
using BrandVue.EntityFramework.MetaData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BrandVue.EntityFramework.Migrations.MetaData
{
    [DbContext(typeof(MetaDataContext))]
    [Migration("20220318072635_AddAverageConfigurationTable")]
    partial class AddAverageConfigurationTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.Averages.AverageConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("AllowPartial")
                        .HasColumnType("bit");

                    b.Property<string>("AverageId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<byte>("AverageStrategy")
                        .HasColumnType("tinyint");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IncludeResponseIds")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<byte>("MakeUpTo")
                        .HasColumnType("tinyint");

                    b.Property<int>("NumberOfPeriodsInAverage")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("ProductShortCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SubProductId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SubsetIds")
                        .HasColumnType("varchar(max)");

                    b.Property<byte>("TotalisationPeriodUnit")
                        .HasColumnType("tinyint");

                    b.Property<byte>("WeightAcross")
                        .HasColumnType("tinyint");

                    b.Property<byte>("WeightingMethod")
                        .HasColumnType("tinyint");

                    b.Property<byte>("WeightingPeriodUnit")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("ProductShortCode", "SubProductId", "AverageId")
                        .IsUnique()
                        .HasFilter("[SubProductId] IS NOT NULL");

                    b.ToTable("Averages");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.Bookmark", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AppBase")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CreatedByIpAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByUserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateLastGenerated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastUsed")
                        .HasColumnType("datetime2");

                    b.Property<long>("GenerationCount")
                        .HasColumnType("bigint");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1600)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1600)");

                    b.Property<long>("UseCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AppBase", "Url")
                        .IsUnique();

                    b.ToTable("Bookmarks");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.ColourConfiguration", b =>
                {
                    b.Property<string>("ProductShortCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Organisation")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EntityType")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("EntityInstanceId")
                        .HasColumnType("int");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.HasKey("ProductShortCode", "Organisation", "EntityType", "EntityInstanceId");

                    b.ToTable("ColourConfigurations");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.CustomPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Organisation")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProductShortCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubProductId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ProductShortCode", "SubProductId", "Organisation", "Name")
                        .IsUnique();

                    b.ToTable("CustomPeriods");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.DefaultBreaksForSubProduct", b =>
                {
                    b.Property<string>("SubProductId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("SavedBreakCombinationId")
                        .HasColumnType("int");

                    b.HasKey("SubProductId");

                    b.HasIndex("SavedBreakCombinationId");

                    b.HasIndex("SubProductId")
                        .IsUnique();

                    b.ToTable("DefaultBreaksForSubProducts", "SavedBreaks");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.EntityInstanceConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EntityTypeIdentifier")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("GeneratedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ProductShortCode")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("StartDateBySubset")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("SubProductId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("SurveyChoiceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EntityInstanceConfigurations");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.EntitySetConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Instances")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFallback")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSectorSet")
                        .HasColumnType("bit");

                    b.Property<string>("KeyInstances")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MainInstance")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Organisation")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProductShortCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SubProductId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Subset")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("EntitySetConfigurations");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.EntityTypeConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DisplayNamePlural")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("DisplayNameSingular")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Identifier")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ProductShortCode")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SubProductId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SurveyChoiceSetNames")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Id");

                    b.ToTable("EntityTypeConfigurations");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.MetricConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BaseExpression")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BaseField")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BaseVals")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CalcType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultSplitByEntityType")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("DisableFilter")
                        .HasColumnType("bit");

                    b.Property<bool>("DisableMeasure")
                        .HasColumnType("bit");

                    b.Property<bool>("DownIsGood")
                        .HasColumnType("bit");

                    b.Property<bool>("EligibleForCrosstabOrAllVue")
                        .HasColumnType("bit");

                    b.Property<bool>("EligibleForMetricComparison")
                        .HasColumnType("bit");

                    b.Property<string>("ExcludeList")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExcludeWaves")
                        .HasColumnType("int");

                    b.Property<string>("Field")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Field2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldExpression")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldOp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilterGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FilterMulti")
                        .HasColumnType("bit");

                    b.Property<string>("FilterValueMapping")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HelpText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAutoGenerated")
                        .HasColumnType("bit");

                    b.Property<string>("KeyImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarketAverageBaseMeasure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Max")
                        .HasColumnType("int");

                    b.Property<string>("Measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Min")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NumFormat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PreNormalisationMaximum")
                        .HasColumnType("int");

                    b.Property<int?>("PreNormalisationMinimum")
                        .HasColumnType("int");

                    b.Property<string>("ProductShortCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<float?>("ScaleFactor")
                        .HasColumnType("real");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubProductId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Subset")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrueVals")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VariableConfigurationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name", "ProductShortCode", "SubProductId")
                        .IsUnique()
                        .HasFilter("[SubProductId] IS NOT NULL");

                    b.ToTable("MetricConfigurations");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.Page.DbPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AverageGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HelpText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Layout")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MenuIcon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MinUserLevel")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("PageDisplayIndex")
                        .HasColumnType("int");

                    b.Property<string>("PageTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PageType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("ProductShortCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Roles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("StartPage")
                        .HasColumnType("bit");

                    b.Property<string>("SubProductId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Subset")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductShortCode", "SubProductId", "Name")
                        .IsUnique();

                    b.ToTable("Pages");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.Page.DbPane", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<string>("PageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaneId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PaneType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductShortCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Spec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Spec2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubProductId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Subset")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("View")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductShortCode", "SubProductId", "PaneId");

                    b.ToTable("Panes");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.Page.DbPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AutoMetrics")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AutoPanes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BaseExpressionOverride")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Breaks")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Colours")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultAverageId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultSplitBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Filters")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HelpText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MultipleEntitySplitByAndMain")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Ordering")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderingDirection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OverrideReportBreaks")
                        .HasColumnType("bit");

                    b.Property<string>("PaneId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PartType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductShortCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ReportOrder")
                        .HasColumnType("int");

                    b.Property<string>("Sections")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ShowTop")
                        .HasColumnType("int");

                    b.Property<string>("Spec1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Spec2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Spec3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubProductId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("XRange")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YRange")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductShortCode", "SubProductId", "PaneId");

                    b.ToTable("Parts");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.Reports.DefaultSavedReport", b =>
                {
                    b.Property<string>("ProductShortCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SubProductId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.HasKey("ProductShortCode", "SubProductId");

                    b.HasIndex("ReportId");

                    b.ToTable("DefaultSavedReports", "Reports");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.Reports.SavedReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<byte?>("BaseTypeOverride")
                        .HasColumnType("tinyint");

                    b.Property<string>("Breaks")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DecimalPlaces")
                        .HasColumnType("int");

                    b.Property<string>("DefaultFilters")
                        .HasColumnType("varchar(max)");

                    b.Property<bool>("ExcludeDontKnows")
                        .HasColumnType("bit");

                    b.Property<bool>("HideEmptyRows")
                        .HasColumnType("bit");

                    b.Property<bool>("HighlightLowSample")
                        .HasColumnType("bit");

                    b.Property<bool>("HighlightSignificance")
                        .HasColumnType("bit");

                    b.Property<bool>("IncludeCounts")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDataWeighted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsShared")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Order")
                        .HasColumnType("tinyint");

                    b.Property<string>("ProductShortCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ReportPageId")
                        .HasColumnType("int");

                    b.Property<int>("ReportType")
                        .HasColumnType("int");

                    b.Property<int>("SignificanceType")
                        .HasColumnType("int");

                    b.Property<bool>("SinglePageExport")
                        .HasColumnType("bit");

                    b.Property<string>("SubProductId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ReportPageId");

                    b.HasIndex("ProductShortCode", "SubProductId");

                    b.ToTable("SavedReports", "Reports");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.SavedBreakCombination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Breaks")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsShared")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SubProductId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("SavedBreakCombinations", "SavedBreaks");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.SubsetConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Alias")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("DisplayNameShort")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("EnableRawDataApiAccess")
                        .HasColumnType("bit");

                    b.Property<string>("Identifier")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Iso2LetterCountryCode")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("ProductShortCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SubProductId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SurveyIdToAllowedSegmentNames")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Id");

                    b.ToTable("SubsetConfigurations");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.SupportableUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("FreshchatConversationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("SupportableUsers");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.VariableDefinitions.VariableConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Definition")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductShortCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SubProductId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ProductShortCode", "SubProductId", "DisplayName")
                        .IsUnique()
                        .HasFilter("[SubProductId] IS NOT NULL");

                    b.ToTable("VariableConfigurations");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.VariableDefinitions.VariableDependency", b =>
                {
                    b.Property<int>("VariableId")
                        .HasColumnType("int");

                    b.Property<int>("DependentUponVariableId")
                        .HasColumnType("int");

                    b.HasKey("VariableId", "DependentUponVariableId");

                    b.HasIndex("DependentUponVariableId");

                    b.ToTable("VariableDependencies");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.Weightings.WeightingScheme", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<int?>("FilterMetricEntityId")
                        .HasColumnType("int");

                    b.Property<string>("WeightingSchemeDetails")
                        .HasColumnType("varchar(max)");

                    b.Property<int>("WeightingStrategyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WeightingStrategyId", "FilterMetricEntityId")
                        .IsUnique();

                    b.ToTable("WeightingSchemes");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.Weightings.WeightingStrategy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FilterMetricName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProductShortCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SubProductId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SubsetId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProductShortCode", "SubProductId", "Name")
                        .IsUnique();

                    b.HasIndex("ProductShortCode", "SubProductId", "SubsetId")
                        .IsUnique();

                    b.ToTable("WeightingStrategies");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.DefaultBreaksForSubProduct", b =>
                {
                    b.HasOne("BrandVue.EntityFramework.MetaData.SavedBreakCombination", "SavedBreakCombination")
                        .WithMany()
                        .HasForeignKey("SavedBreakCombinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SavedBreakCombination");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.Reports.DefaultSavedReport", b =>
                {
                    b.HasOne("BrandVue.EntityFramework.MetaData.Reports.SavedReport", "Report")
                        .WithMany()
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.Reports.SavedReport", b =>
                {
                    b.HasOne("BrandVue.EntityFramework.MetaData.Page.DbPage", "ReportPage")
                        .WithMany()
                        .HasForeignKey("ReportPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportPage");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.VariableDefinitions.VariableDependency", b =>
                {
                    b.HasOne("BrandVue.EntityFramework.MetaData.VariableDefinitions.VariableConfiguration", "DependentUponVariable")
                        .WithMany("VariablesDependingOnThis")
                        .HasForeignKey("DependentUponVariableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BrandVue.EntityFramework.MetaData.VariableDefinitions.VariableConfiguration", "Variable")
                        .WithMany("VariableDependencies")
                        .HasForeignKey("VariableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DependentUponVariable");

                    b.Navigation("Variable");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.Weightings.WeightingScheme", b =>
                {
                    b.HasOne("BrandVue.EntityFramework.MetaData.Weightings.WeightingStrategy", null)
                        .WithMany("WeightingSchemes")
                        .HasForeignKey("WeightingStrategyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.VariableDefinitions.VariableConfiguration", b =>
                {
                    b.Navigation("VariableDependencies");

                    b.Navigation("VariablesDependingOnThis");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.Weightings.WeightingStrategy", b =>
                {
                    b.Navigation("WeightingSchemes");
                });
#pragma warning restore 612, 618
        }
    }
}
