#nullable disable

namespace BrandVue.EntityFramework.Migrations.MetaData
{
    public partial class RemoveBrandAnalysisBasedOnPart : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            var sql = @"
DELETE
FROM [Parts]
WHERE PartType = 'BrandAnalysisBasedOn'";
            migrationBuilder.Sql(sql);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            var sql = @"
INSERT INTO [dbo].[Parts] ([ProductShortCode],[PaneId],[PartType],[Spec1],[Spec2],[Spec3]) VALUES ('eatingout', 'BrandAdvocacyUK',	'BrandAnalysisBasedOn',			'Promoters',	'Advocacy', '{""metrics"":[{""key"":""gender"",""metricName"":""Gender (Analysis)"",""requestType"":""crossbreak""},{""key"":""region"",""metricName"":""Region (Grouped)"",""requestType"":""crossbreak""},{""key"":""segment"",""metricName"":""Segment (Analysis)"",""requestType"":""competition""},{""key"":""affinity"",""metricName"":""Affinity (Analysis)"", ""includePrimaryMetricFilter"":false ,""requestType"":""competition""}]}')
INSERT INTO [dbo].[Parts] ([ProductShortCode],[PaneId],[PartType],[Spec1],[Spec2],[Spec3]) VALUES ('eatingout', 'BrandBuzzUK',		'BrandAnalysisBasedOn',			'Positive buzz',	'Buzz', '{""metrics"":[{""key"":""gender"",""metricName"":""Gender (Analysis)"",""requestType"":""crossbreak""},{""key"":""region"",""metricName"":""Region (Grouped)"",""requestType"":""crossbreak""},{""key"":""segment"",""metricName"":""Segment (Analysis)"",""requestType"":""competition""},{""key"":""affinity"",""metricName"":""Affinity (Analysis)"", ""includePrimaryMetricFilter"":false ,""requestType"":""competition""}]}')
INSERT INTO [dbo].[Parts] ([ProductShortCode],[PaneId],[PartType],[Spec1],[Spec2],[Spec3]) VALUES ('eatingout', 'BrandLoveUK',		'BrandAnalysisBasedOn',			'Brand Love',	'Love', '{""metrics"":[{""key"":""gender"",""metricName"":""Gender (Analysis)"",""requestType"":""crossbreak""},{""key"":""region"",""metricName"":""Region (Grouped)"",""requestType"":""crossbreak""},{""key"":""segment"",""metricName"":""Segment (Analysis)"",""requestType"":""competition""},{""key"":""affinity"",""metricName"":""Affinity (Analysis)"", ""includePrimaryMetricFilter"":false ,""requestType"":""competition""}]}')
INSERT INTO [dbo].[Parts] ([ProductShortCode],[PaneId],[PartType],[Spec1],[Spec2],[Spec3]) VALUES ('eatingout', 'BrandUsageUK',		'BrandAnalysisBasedOn',			'Penetration (L12M)',	'Usage', '{""metrics"":[{""key"":""gender"",""metricName"":""Gender (Analysis)"",""requestType"":""crossbreak""},{""key"":""region"",""metricName"":""Region (Grouped)"",""requestType"":""crossbreak""},{""key"":""segment"",""metricName"":""Segment (Analysis)"",""requestType"":""competition""},{""key"":""affinity"",""metricName"":""Affinity (Analysis)"", ""includePrimaryMetricFilter"":false ,""requestType"":""competition""}]}')
INSERT INTO [dbo].[Parts] ([ProductShortCode],[PaneId],[PartType],[Spec1],[Spec2],[Spec3]) VALUES ('eatingout', 'BrandAdvocacyDE',	'BrandAnalysisBasedOn',			'Promoters',	'Advocacy', '{""metrics"":[{""key"":""gender"",""metricName"":""Gender (Analysis)"",""requestType"":""crossbreak""},{""key"":""region"",""metricName"":""Region (Grouped) DE"",""requestType"":""crossbreak""},{""key"":""segment"",""metricName"":""Segment (Analysis)"",""requestType"":""competition""},{""key"":""affinity"",""metricName"":""Affinity (Analysis)"", ""includePrimaryMetricFilter"":false ,""requestType"":""competition""}]}')
INSERT INTO [dbo].[Parts] ([ProductShortCode],[PaneId],[PartType],[Spec1],[Spec2],[Spec3]) VALUES ('eatingout', 'BrandBuzzDE',		'BrandAnalysisBasedOn',			'Positive buzz',	'Buzz', '{""metrics"":[{""key"":""gender"",""metricName"":""Gender (Analysis)"",""requestType"":""crossbreak""},{""key"":""region"",""metricName"":""Region (Grouped) DE"",""requestType"":""crossbreak""},{""key"":""segment"",""metricName"":""Segment (Analysis)"",""requestType"":""competition""},{""key"":""affinity"",""metricName"":""Affinity (Analysis)"", ""includePrimaryMetricFilter"":false ,""requestType"":""competition""}]}')
INSERT INTO [dbo].[Parts] ([ProductShortCode],[PaneId],[PartType],[Spec1],[Spec2],[Spec3]) VALUES ('eatingout', 'BrandLoveDE',		'BrandAnalysisBasedOn',			'Brand Love',	'Love', '{""metrics"":[{""key"":""gender"",""metricName"":""Gender (Analysis)"",""requestType"":""crossbreak""},{""key"":""region"",""metricName"":""Region (Grouped) DE"",""requestType"":""crossbreak""},{""key"":""segment"",""metricName"":""Segment (Analysis)"",""requestType"":""competition""},{""key"":""affinity"",""metricName"":""Affinity (Analysis)"", ""includePrimaryMetricFilter"":false ,""requestType"":""competition""}]}')
INSERT INTO [dbo].[Parts] ([ProductShortCode],[PaneId],[PartType],[Spec1],[Spec2],[Spec3]) VALUES ('eatingout', 'BrandUsageDE',		'BrandAnalysisBasedOn',			'Penetration (L12M)',	'Usage', '{""metrics"":[{""key"":""gender"",""metricName"":""Gender (Analysis)"",""requestType"":""crossbreak""},{""key"":""region"",""metricName"":""Region (Grouped) DE"",""requestType"":""crossbreak""},{""key"":""segment"",""metricName"":""Segment (Analysis)"",""requestType"":""competition""},{""key"":""affinity"",""metricName"":""Affinity (Analysis)"", ""includePrimaryMetricFilter"":false ,""requestType"":""competition""}]}')
INSERT INTO [dbo].[Parts] ([ProductShortCode],[PaneId],[PartType],[Spec1],[Spec2],[Spec3]) VALUES ('eatingout', 'BrandAdvocacyES',	'BrandAnalysisBasedOn',			'Promoters',	'Advocacy', '{""metrics"":[{""key"":""gender"",""metricName"":""Gender (Analysis)"",""requestType"":""crossbreak""},{""key"":""region"",""metricName"":""Region (Grouped) ES"",""requestType"":""crossbreak""},{""key"":""segment"",""metricName"":""Segment (Analysis)"",""requestType"":""competition""},{""key"":""affinity"",""metricName"":""Affinity (Analysis)"", ""includePrimaryMetricFilter"":false ,""requestType"":""competition""}]}')
INSERT INTO [dbo].[Parts] ([ProductShortCode],[PaneId],[PartType],[Spec1],[Spec2],[Spec3]) VALUES ('eatingout', 'BrandBuzzES',		'BrandAnalysisBasedOn',			'Positive buzz',	'Buzz', '{""metrics"":[{""key"":""gender"",""metricName"":""Gender (Analysis)"",""requestType"":""crossbreak""},{""key"":""region"",""metricName"":""Region (Grouped) ES"",""requestType"":""crossbreak""},{""key"":""segment"",""metricName"":""Segment (Analysis)"",""requestType"":""competition""},{""key"":""affinity"",""metricName"":""Affinity (Analysis)"", ""includePrimaryMetricFilter"":false ,""requestType"":""competition""}]}')
INSERT INTO [dbo].[Parts] ([ProductShortCode],[PaneId],[PartType],[Spec1],[Spec2],[Spec3]) VALUES ('eatingout', 'BrandLoveES',		'BrandAnalysisBasedOn',			'Brand Love',	'Love', '{""metrics"":[{""key"":""gender"",""metricName"":""Gender (Analysis)"",""requestType"":""crossbreak""},{""key"":""region"",""metricName"":""Region (Grouped) ES"",""requestType"":""crossbreak""},{""key"":""segment"",""metricName"":""Segment (Analysis)"",""requestType"":""competition""},{""key"":""affinity"",""metricName"":""Affinity (Analysis)"", ""includePrimaryMetricFilter"":false ,""requestType"":""competition""}]}')
INSERT INTO [dbo].[Parts] ([ProductShortCode],[PaneId],[PartType],[Spec1],[Spec2],[Spec3]) VALUES ('eatingout', 'BrandUsageES',		'BrandAnalysisBasedOn',			'Penetration (L12M)',	'Usage', '{""metrics"":[{""key"":""gender"",""metricName"":""Gender (Analysis)"",""requestType"":""crossbreak""},{""key"":""region"",""metricName"":""Region (Grouped) ES"",""requestType"":""crossbreak""},{""key"":""segment"",""metricName"":""Segment (Analysis)"",""requestType"":""competition""},{""key"":""affinity"",""metricName"":""Affinity (Analysis)"", ""includePrimaryMetricFilter"":false ,""requestType"":""competition""}]}')
INSERT INTO [dbo].[Parts] ([ProductShortCode],[PaneId],[PartType],[Spec1],[Spec2],[Spec3]) VALUES ('eatingout', 'BrandAdvocacyUS',	'BrandAnalysisBasedOn',			'Promoters',	'Advocacy', '{""metrics"":[{""key"":""gender"",""metricName"":""Gender (Analysis)"",""requestType"":""crossbreak""},{""key"":""region"",""metricName"":""Region (Grouped) US"",""requestType"":""crossbreak""},{""key"":""segment"",""metricName"":""Segment (Analysis)"",""requestType"":""competition""},{""key"":""affinity"",""metricName"":""Affinity (Analysis)"", ""includePrimaryMetricFilter"":false ,""requestType"":""competition""}]}')
INSERT INTO [dbo].[Parts] ([ProductShortCode],[PaneId],[PartType],[Spec1],[Spec2],[Spec3]) VALUES ('eatingout', 'BrandBuzzUS',		'BrandAnalysisBasedOn',			'Positive buzz',	'Buzz', '{""metrics"":[{""key"":""gender"",""metricName"":""Gender (Analysis)"",""requestType"":""crossbreak""},{""key"":""region"",""metricName"":""Region (Grouped) US"",""requestType"":""crossbreak""},{""key"":""segment"",""metricName"":""Segment (Analysis)"",""requestType"":""competition""},{""key"":""affinity"",""metricName"":""Affinity (Analysis)"", ""includePrimaryMetricFilter"":false ,""requestType"":""competition""}]}')
INSERT INTO [dbo].[Parts] ([ProductShortCode],[PaneId],[PartType],[Spec1],[Spec2],[Spec3]) VALUES ('eatingout', 'BrandLoveUS',		'BrandAnalysisBasedOn',			'Brand Love',	'Love', '{""metrics"":[{""key"":""gender"",""metricName"":""Gender (Analysis)"",""requestType"":""crossbreak""},{""key"":""region"",""metricName"":""Region (Grouped) US"",""requestType"":""crossbreak""},{""key"":""segment"",""metricName"":""Segment (Analysis)"",""requestType"":""competition""},{""key"":""affinity"",""metricName"":""Affinity (Analysis)"", ""includePrimaryMetricFilter"":false ,""requestType"":""competition""}]}')
INSERT INTO [dbo].[Parts] ([ProductShortCode],[PaneId],[PartType],[Spec1],[Spec2],[Spec3]) VALUES ('eatingout', 'BrandUsageUS',		'BrandAnalysisBasedOn',			'Penetration (L12M)',	'Usage', '{""metrics"":[{""key"":""gender"",""metricName"":""Gender (Analysis)"",""requestType"":""crossbreak""},{""key"":""region"",""metricName"":""Region (Grouped) US"",""requestType"":""crossbreak""},{""key"":""segment"",""metricName"":""Segment (Analysis)"",""requestType"":""competition""},{""key"":""affinity"",""metricName"":""Affinity (Analysis)"", ""includePrimaryMetricFilter"":false ,""requestType"":""competition""}]}')
INSERT INTO [dbo].[Parts] ([ProductShortCode],[PaneId],[PartType],[Spec1],[Spec2],[Spec3]) VALUES ('eatingout', 'BrandAdvocacyFR',	'BrandAnalysisBasedOn',			'Promoters',	'Advocacy', '{""metrics"":[{""key"":""gender"",""metricName"":""Gender (Analysis)"",""requestType"":""crossbreak""},{""key"":""region"",""metricName"":""Region (Grouped)"",""requestType"":""crossbreak""},{""key"":""segment"",""metricName"":""Segment (Analysis)"",""requestType"":""competition""},{""key"":""affinity"",""metricName"":""Affinity (Analysis)"", ""includePrimaryMetricFilter"":false ,""requestType"":""competition""}]}')
INSERT INTO [dbo].[Parts] ([ProductShortCode],[PaneId],[PartType],[Spec1],[Spec2],[Spec3]) VALUES ('eatingout', 'BrandBuzzFR',		'BrandAnalysisBasedOn',			'Positive buzz',	'Buzz', '{""metrics"":[{""key"":""gender"",""metricName"":""Gender (Analysis)"",""requestType"":""crossbreak""},{""key"":""region"",""metricName"":""Region (Grouped)"",""requestType"":""crossbreak""},{""key"":""segment"",""metricName"":""Segment (Analysis)"",""requestType"":""competition""},{""key"":""affinity"",""metricName"":""Affinity (Analysis)"", ""includePrimaryMetricFilter"":false ,""requestType"":""competition""}]}')
INSERT INTO [dbo].[Parts] ([ProductShortCode],[PaneId],[PartType],[Spec1],[Spec2],[Spec3]) VALUES ('eatingout', 'BrandLoveFR',		'BrandAnalysisBasedOn',			'Brand Love',	'Love', '{""metrics"":[{""key"":""gender"",""metricName"":""Gender (Analysis)"",""requestType"":""crossbreak""},{""key"":""region"",""metricName"":""Region (Grouped)"",""requestType"":""crossbreak""},{""key"":""segment"",""metricName"":""Segment (Analysis)"",""requestType"":""competition""},{""key"":""affinity"",""metricName"":""Affinity (Analysis)"", ""includePrimaryMetricFilter"":false ,""requestType"":""competition""}]}')
INSERT INTO [dbo].[Parts] ([ProductShortCode],[PaneId],[PartType],[Spec1],[Spec2],[Spec3]) VALUES ('eatingout', 'BrandUsageFR',		'BrandAnalysisBasedOn',			'Penetration (L12M)',	'Usage', '{""metrics"":[{""key"":""gender"",""metricName"":""Gender (Analysis)"",""requestType"":""crossbreak""},{""key"":""region"",""metricName"":""Region (Grouped)"",""requestType"":""crossbreak""},{""key"":""segment"",""metricName"":""Segment (Analysis)"",""requestType"":""competition""},{""key"":""affinity"",""metricName"":""Affinity (Analysis)"", ""includePrimaryMetricFilter"":false ,""requestType"":""competition""}]}')

INSERT INTO [dbo].[Parts] ([ProductShortCode],[PaneId],[PartType],[Spec1],[Spec2],[Spec3]) VALUES ('brandvue', 'BrandAdvocacy',	'BrandAnalysisBasedOn',			'Promoters',	'Advocacy', '{""metrics"":[{""key"":""gender"",""metricName"":""Gender"",""requestType"":""crossbreak""},{""key"":""region"",""metricName"":""Region (Analysis)"",""requestType"":""crossbreak""},{""key"":""segment"",""metricName"":""Segment (Analysis)"",""requestType"":""competition""},{""key"":""affinity"",""metricName"":""Affinity (Analysis)"", ""includePrimaryMetricFilter"":false ,""requestType"":""competition""}]}')
INSERT INTO [dbo].[Parts] ([ProductShortCode],[PaneId],[PartType],[Spec1],[Spec2],[Spec3]) VALUES ('brandvue', 'BrandBuzz',		'BrandAnalysisBasedOn',			'Positive Buzz',	'Buzz', '{""metrics"":[{""key"":""gender"",""metricName"":""Gender"",""requestType"":""crossbreak""},{""key"":""region"",""metricName"":""Region (Analysis)"",""requestType"":""crossbreak""},{""key"":""segment"",""metricName"":""Segment (Analysis)"",""requestType"":""competition""},{""key"":""affinity"",""metricName"":""Affinity (Analysis)"", ""includePrimaryMetricFilter"":false ,""requestType"":""competition""}]}')
INSERT INTO [dbo].[Parts] ([ProductShortCode],[PaneId],[PartType],[Spec1],[Spec2],[Spec3]) VALUES ('brandvue', 'BrandLove',		'BrandAnalysisBasedOn',			'Brand Love',	'Love', '{""metrics"":[{""key"":""gender"",""metricName"":""Gender"",""requestType"":""crossbreak""},{""key"":""region"",""metricName"":""Region (Analysis)"",""requestType"":""crossbreak""},{""key"":""segment"",""metricName"":""Segment (Analysis)"",""requestType"":""competition""},{""key"":""affinity"",""metricName"":""Affinity (Analysis)"", ""includePrimaryMetricFilter"":false ,""requestType"":""competition""}]}')
INSERT INTO [dbo].[Parts] ([ProductShortCode],[PaneId],[PartType],[Spec1],[Spec2],[Spec3]) VALUES ('brandvue', 'BrandUsage',		'BrandAnalysisBasedOn',			'Penetration (L12M)',	'Usage', '{""metrics"":[{""key"":""gender"",""metricName"":""Gender"",""requestType"":""crossbreak""},{""key"":""region"",""metricName"":""Region (Analysis)"",""requestType"":""crossbreak""},{""key"":""segment"",""metricName"":""Segment (Analysis)"",""requestType"":""competition""},{""key"":""affinity"",""metricName"":""Affinity (Analysis)"", ""includePrimaryMetricFilter"":false ,""requestType"":""competition""}]}')

INSERT INTO [dbo].[Parts] ([ProductShortCode],[PaneId],[PartType],[Spec1],[Spec2],[Spec3]) VALUES ('charities', 'BrandAdvocacy',	'BrandAnalysisBasedOn',			'Promoters',	'Advocacy', '{""metrics"":[{""key"":""gender"",""metricName"":""Gender (Analysis)"",""requestType"":""crossbreak""},{""key"":""region"",""metricName"":""Region (Grouped)"",""requestType"":""crossbreak""},{""key"":""segment"",""metricName"":""Segment (Analysis)"",""requestType"":""competition""},{""key"":""affinity"",""metricName"":""Affinity (Analysis)"", ""includePrimaryMetricFilter"":false ,""requestType"":""competition""}],""pastTenseVerb"":""currently support""}')
INSERT INTO [dbo].[Parts] ([ProductShortCode],[PaneId],[PartType],[Spec1],[Spec2],[Spec3]) VALUES ('charities', 'BrandBuzz',		'BrandAnalysisBasedOn',			'Positive Buzz',	'Buzz', '{""metrics"":[{""key"":""gender"",""metricName"":""Gender (Analysis)"",""requestType"":""crossbreak""},{""key"":""region"",""metricName"":""Region (Grouped)"",""requestType"":""crossbreak""},{""key"":""segment"",""metricName"":""Segment (Analysis)"",""requestType"":""competition""},{""key"":""affinity"",""metricName"":""Affinity (Analysis)"", ""includePrimaryMetricFilter"":false ,""requestType"":""competition""}]}')
INSERT INTO [dbo].[Parts] ([ProductShortCode],[PaneId],[PartType],[Spec1],[Spec2],[Spec3]) VALUES ('charities', 'BrandLove',		'BrandAnalysisBasedOn',			'Love',	'Love', '{""metrics"":[{""key"":""gender"",""metricName"":""Gender (Analysis)"",""requestType"":""crossbreak""},{""key"":""region"",""metricName"":""Region (Grouped)"",""requestType"":""crossbreak""},{""key"":""segment"",""metricName"":""Segment (Analysis)"",""requestType"":""competition""},{""key"":""affinity"",""metricName"":""Affinity (Analysis)"", ""includePrimaryMetricFilter"":false ,""requestType"":""competition""}]}')
INSERT INTO [dbo].[Parts] ([ProductShortCode],[PaneId],[PartType],[Spec1],[Spec2],[Spec3]) VALUES ('charities', 'BrandUsage',		'BrandAnalysisBasedOn',			'Support Status:Support',	'Usage', '{""metrics"":[{""key"":""gender"",""metricName"":""Gender (Analysis)"",""requestType"":""crossbreak""},{""key"":""region"",""metricName"":""Region (Grouped)"",""requestType"":""crossbreak""},{""key"":""segment"",""metricName"":""Segment (Analysis)"",""requestType"":""competition""},{""key"":""affinity"",""metricName"":""Affinity (Analysis)"", ""includePrimaryMetricFilter"":false ,""requestType"":""competition""}],""pastTenseVerb"":""currently support""}')

INSERT INTO [dbo].[Parts] ([ProductShortCode],[PaneId],[PartType],[Spec1],[Spec2],[Spec3]) VALUES ('finance', 'BrandAdvocacy',	'BrandAnalysisBasedOn',			'Promotors Advocacy',	'Advocacy', '{""metrics"":[{""key"":""gender"",""metricName"":""Gender (Analysis)"",""requestType"":""crossbreak""},{""key"":""region"",""metricName"":""Region (Analysis)"",""requestType"":""crossbreak""},{""key"":""segment"",""metricName"":""Segment (Analysis)"",""requestType"":""competition""},{""key"":""affinity"",""metricName"":""Affinity (Analysis)"", ""includePrimaryMetricFilter"":false ,""requestType"":""competition""}],""pastTenseVerb"":""purchased from""}')
INSERT INTO [dbo].[Parts] ([ProductShortCode],[PaneId],[PartType],[Spec1],[Spec2],[Spec3]) VALUES ('finance', 'BrandBuzz',		'BrandAnalysisBasedOn',			'Positive Buzz',	'Buzz', '{""metrics"":[{""key"":""gender"",""metricName"":""Gender (Analysis)"",""requestType"":""crossbreak""},{""key"":""region"",""metricName"":""Region (Analysis)"",""requestType"":""crossbreak""},{""key"":""segment"",""metricName"":""Segment (Analysis)"",""requestType"":""competition""},{""key"":""affinity"",""metricName"":""Affinity (Analysis)"", ""includePrimaryMetricFilter"":false ,""requestType"":""competition""}]}')
INSERT INTO [dbo].[Parts] ([ProductShortCode],[PaneId],[PartType],[Spec1],[Spec2],[Spec3]) VALUES ('finance', 'BrandLove',		'BrandAnalysisBasedOn',			'Brand Affinity:Love',	'Love', '{""metrics"":[{""key"":""gender"",""metricName"":""Gender (Analysis)"",""requestType"":""crossbreak""},{""key"":""region"",""metricName"":""Region (Analysis)"",""requestType"":""crossbreak""},{""key"":""segment"",""metricName"":""Segment (Analysis)"",""requestType"":""competition""},{""key"":""affinity"",""metricName"":""Affinity (Analysis)"", ""includePrimaryMetricFilter"":false ,""requestType"":""competition""}]}')
INSERT INTO [dbo].[Parts] ([ProductShortCode],[PaneId],[PartType],[Spec1],[Spec2],[Spec3]) VALUES ('finance', 'BrandUsage',		'BrandAnalysisBasedOn',			'Penetration (L12M)',	'Usage', '{""metrics"":[{""key"":""gender"",""metricName"":""Gender (Analysis)"",""requestType"":""crossbreak""},{""key"":""region"",""metricName"":""Region (Analysis)"",""requestType"":""crossbreak""},{""key"":""segment"",""metricName"":""Segment (Analysis)"",""requestType"":""competition""},{""key"":""affinity"",""metricName"":""Affinity (Analysis)"", ""includePrimaryMetricFilter"":false ,""requestType"":""competition""}],""pastTenseVerb"":""purchased from""}')

INSERT INTO [dbo].[Parts] ([ProductShortCode],[PaneId],[PartType],[Spec1],[Spec2],[Spec3]) VALUES ('retail', 'BrandAdvocacy',	'BrandAnalysisBasedOn',			'Promoters',	'Advocacy', '{""metrics"":[{""key"":""gender"",""metricName"":""Gender (Analysis)"",""requestType"":""crossbreak""},{""key"":""region"",""metricName"":""Region (Analysis)"",""requestType"":""crossbreak""},{""key"":""segment"",""metricName"":""Segment (Analysis)"",""requestType"":""competition""},{""key"":""affinity"",""metricName"":""Affinity (Analysis)"", ""includePrimaryMetricFilter"":false ,""requestType"":""competition""}],""pastTenseVerb"":""purchased from""}')
INSERT INTO [dbo].[Parts] ([ProductShortCode],[PaneId],[PartType],[Spec1],[Spec2],[Spec3]) VALUES ('retail', 'BrandBuzz',		'BrandAnalysisBasedOn',			'Positive Buzz',	'Buzz', '{""metrics"":[{""key"":""gender"",""metricName"":""Gender (Analysis)"",""requestType"":""crossbreak""},{""key"":""region"",""metricName"":""Region (Analysis)"",""requestType"":""crossbreak""},{""key"":""segment"",""metricName"":""Segment (Analysis)"",""requestType"":""competition""},{""key"":""affinity"",""metricName"":""Affinity (Analysis)"", ""includePrimaryMetricFilter"":false ,""requestType"":""competition""}]}')
INSERT INTO [dbo].[Parts] ([ProductShortCode],[PaneId],[PartType],[Spec1],[Spec2],[Spec3]) VALUES ('retail', 'BrandLove',		'BrandAnalysisBasedOn',			'Brand Love',	'Love', '{""metrics"":[{""key"":""gender"",""metricName"":""Gender (Analysis)"",""requestType"":""crossbreak""},{""key"":""region"",""metricName"":""Region (Analysis)"",""requestType"":""crossbreak""},{""key"":""segment"",""metricName"":""Segment (Analysis)"",""requestType"":""competition""},{""key"":""affinity"",""metricName"":""Affinity (Analysis)"", ""includePrimaryMetricFilter"":false ,""requestType"":""competition""}]}')
INSERT INTO [dbo].[Parts] ([ProductShortCode],[PaneId],[PartType],[Spec1],[Spec2],[Spec3]) VALUES ('retail', 'BrandUsage',		'BrandAnalysisBasedOn',			'Penetration (L12M)',	'Usage', '{""metrics"":[{""key"":""gender"",""metricName"":""Gender (Analysis)"",""requestType"":""crossbreak""},{""key"":""region"",""metricName"":""Region (Analysis)"",""requestType"":""crossbreak""},{""key"":""segment"",""metricName"":""Segment (Analysis)"",""requestType"":""competition""},{""key"":""affinity"",""metricName"":""Affinity (Analysis)"", ""includePrimaryMetricFilter"":false ,""requestType"":""competition""}],""pastTenseVerb"":""purchased from""}')

INSERT INTO [dbo].[Parts] ([ProductShortCode],[PaneId],[PartType],[Spec1],[Spec2],[Spec3]) VALUES ('drinks', 'BrandBuzz',		'BrandAnalysisBasedOn',			'Positive Buzz',	'Buzz', '{""metrics"":[{""key"":""gender"",""metricName"":""Gender (Analysis)"",""requestType"":""crossbreak""},{""key"":""region"",""metricName"":""Region (Analysis)"",""requestType"":""crossbreak""},{""key"":""segment"",""metricName"":""Segment (Analysis)"",""requestType"":""competition""},{""key"":""affinity"",""metricName"":""Affinity (Analysis)"", ""includePrimaryMetricFilter"":false ,""requestType"":""competition""}]}')
INSERT INTO [dbo].[Parts] ([ProductShortCode],[PaneId],[PartType],[Spec1],[Spec2],[Spec3]) VALUES ('drinks', 'BrandLove',		'BrandAnalysisBasedOn',			'Love',	'Love', '{""metrics"":[{""key"":""gender"",""metricName"":""Gender (Analysis)"",""requestType"":""crossbreak""},{""key"":""region"",""metricName"":""Region (Analysis)"",""requestType"":""crossbreak""},{""key"":""segment"",""metricName"":""Segment (Analysis)"",""requestType"":""competition""},{""key"":""affinity"",""metricName"":""Affinity (Analysis)"", ""includePrimaryMetricFilter"":false ,""requestType"":""competition""}]}')
INSERT INTO [dbo].[Parts] ([ProductShortCode],[PaneId],[PartType],[Spec1],[Spec2],[Spec3]) VALUES ('drinks', 'BrandUsage',		'BrandAnalysisBasedOn',			'Penetration (L12M)',	'Usage', '{""metrics"":[{""key"":""gender"",""metricName"":""Gender (Analysis)"",""requestType"":""crossbreak""},{""key"":""region"",""metricName"":""Region (Analysis)"",""requestType"":""crossbreak""},{""key"":""segment"",""metricName"":""Segment (Analysis)"",""requestType"":""competition""},{""key"":""affinity"",""metricName"":""Affinity (Analysis)"", ""includePrimaryMetricFilter"":false ,""requestType"":""competition""}],""pastTenseVerb"":""purchased""}')";
            migrationBuilder.Sql(sql);
        }
    }
}
