// <auto-generated />
using System;
using BrandVue.EntityFramework.MetaData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BrandVue.EntityFramework.Migrations.MetaData
{
    [DbContext(typeof(MetaDataContext))]
    [Migration("20240422100457_AttachResponseWeightsToWeightingTargets")]
    partial class AttachResponseWeightsToWeightingTargets
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.AllVueConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsDataTabAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDocumentsTabAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsQuotaTabAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReportVueReportsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReportsTabAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("ProductShortCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ReportVueConfiguration")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("SubProductId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool?>("UseNewWeightingUI")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("SubProductId", "ProductShortCode")
                        .IsUnique()
                        .HasFilter("[SubProductId] IS NOT NULL AND [ProductShortCode] IS NOT NULL");

                    b.ToTable("AllVueConfigurations");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.Averages.AverageConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("AllowPartial")
                        .HasColumnType("bit");

                    b.Property<string>("AuthCompanyShortCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AverageId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("AverageStrategy")
                        .HasColumnType("tinyint");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Group")
                        .HasColumnType("varchar(max)");

                    b.Property<bool>("IncludeResponseIds")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<byte>("MakeUpTo")
                        .HasColumnType("tinyint");

                    b.Property<int>("NumberOfPeriodsInAverage")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("ProductShortCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SubProductId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SubsetIds")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<byte>("TotalisationPeriodUnit")
                        .HasColumnType("tinyint");

                    b.Property<byte>("WeightAcross")
                        .HasColumnType("tinyint");

                    b.Property<byte>("WeightingMethod")
                        .HasColumnType("tinyint");

                    b.Property<byte>("WeightingPeriodUnit")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("ProductShortCode", "SubProductId", "AverageId")
                        .IsUnique()
                        .HasFilter("[SubProductId] IS NOT NULL");

                    b.ToTable("Averages");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.Bookmark", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AppBase")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CreatedByIpAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByUserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateLastGenerated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastUsed")
                        .HasColumnType("datetime2");

                    b.Property<long>("GenerationCount")
                        .HasColumnType("bigint");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1600)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1600)");

                    b.Property<long>("UseCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AppBase", "Url")
                        .IsUnique();

                    b.ToTable("Bookmarks");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.ColourConfiguration", b =>
                {
                    b.Property<string>("ProductShortCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Organisation")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EntityType")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("EntityInstanceId")
                        .HasColumnType("int");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.HasKey("ProductShortCode", "Organisation", "EntityType", "EntityInstanceId");

                    b.ToTable("ColourConfigurations");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.CustomPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Organisation")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProductShortCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubProductId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ProductShortCode", "SubProductId", "Organisation", "Name")
                        .IsUnique();

                    b.ToTable("CustomPeriods");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.DefaultSavedBreaks", b =>
                {
                    b.Property<string>("ProductShortCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SubProductId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("SavedBreakCombinationId")
                        .HasColumnType("int");

                    b.HasKey("ProductShortCode", "SubProductId");

                    b.HasIndex("SavedBreakCombinationId");

                    b.ToTable("DefaultBreaksForSubProducts", "SavedBreaks");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.EntityInstanceConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EnabledBySubset")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("EntityTypeIdentifier")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("GeneratedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ProductShortCode")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("StartDateBySubset")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("SubProductId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("SurveyChoiceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("EntityInstanceConfigurations");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.EntitySetAverageMappingConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ChildEntitySetId")
                        .HasColumnType("int");

                    b.Property<int>("EntitySetConfigurationId")
                        .HasColumnType("int")
                        .HasColumnName("ParentEntitySetId");

                    b.Property<bool>("ExcludeMainInstance")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("EntitySetConfigurationId");

                    b.ToTable("EntitySetAverageMappingConfigurations");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.EntitySetConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Instances")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFallback")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSectorSet")
                        .HasColumnType("bit");

                    b.Property<string>("LastUpdatedUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MainInstance")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Organisation")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProductShortCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SubProductId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Subset")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("EntitySetConfigurations");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.EntityTypeConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CreatedFrom")
                        .HasColumnType("int");

                    b.Property<string>("DisplayNamePlural")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("DisplayNameSingular")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Identifier")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ProductShortCode")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SubProductId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SurveyChoiceSetNames")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Id");

                    b.ToTable("EntityTypeConfigurations");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.LinkedMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("LinkedMetricNames")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetricName")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductShortCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SubProductId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ProductShortCode", "MetricName");

                    b.ToTable("LinkedMetric", (string)null);
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.MetricAbout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AboutContent")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("AboutTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Editable")
                        .HasColumnType("bit");

                    b.Property<string>("MetricName")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductShortCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("User")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ProductShortCode", "MetricName");

                    b.ToTable("MetricAbout");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.MetricConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BaseExpression")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BaseField")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BaseVals")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BaseVariableConfigurationId")
                        .HasColumnType("int");

                    b.Property<string>("CalcType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultSplitByEntityType")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("DisableFilter")
                        .HasColumnType("bit");

                    b.Property<bool>("DisableMeasure")
                        .HasColumnType("bit");

                    b.Property<bool>("DownIsGood")
                        .HasColumnType("bit");

                    b.Property<bool>("EligibleForCrosstabOrAllVue")
                        .HasColumnType("bit");

                    b.Property<bool>("EligibleForMetricComparison")
                        .HasColumnType("bit");

                    b.Property<string>("ExcludeList")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExcludeWaves")
                        .HasColumnType("int");

                    b.Property<string>("Field")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Field2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldExpression")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldOp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilterGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FilterMulti")
                        .HasColumnType("bit");

                    b.Property<string>("FilterValueMapping")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HelpText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("IsAutoGenerated")
                        .HasColumnType("tinyint");

                    b.Property<string>("KeyImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarketAverageBaseMeasure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Max")
                        .HasColumnType("int");

                    b.Property<string>("Measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Min")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NumFormat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginalMetricName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PreNormalisationMaximum")
                        .HasColumnType("int");

                    b.Property<int?>("PreNormalisationMinimum")
                        .HasColumnType("int");

                    b.Property<string>("ProductShortCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<float?>("ScaleFactor")
                        .HasColumnType("real");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubProductId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Subset")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrueVals")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VarCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VariableConfigurationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name", "ProductShortCode", "SubProductId")
                        .IsUnique()
                        .HasFilter("[SubProductId] IS NOT NULL");

                    b.ToTable("MetricConfigurations");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.Page.DbPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AverageGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultBase")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DefaultPaneViewType")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HelpText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Layout")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MenuIcon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MinUserLevel")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("PageDisplayIndex")
                        .HasColumnType("int");

                    b.Property<string>("PageTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PageType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("ProductShortCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Roles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("StartPage")
                        .HasColumnType("bit");

                    b.Property<string>("SubProductId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Subset")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductShortCode", "SubProductId", "Name")
                        .IsUnique();

                    b.ToTable("Pages");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.Page.DbPane", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<string>("PageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaneId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PaneType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductShortCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Spec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Spec2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubProductId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Subset")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("View")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductShortCode", "SubProductId", "PaneId");

                    b.ToTable("Panes");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.Page.DbPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AutoMetrics")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AutoPanes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AverageType")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("BaseExpressionOverride")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Breaks")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Colours")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultAverageId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultSplitBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Filters")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HelpText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MultiBreakSelectedEntityInstance")
                        .HasColumnType("int");

                    b.Property<string>("MultipleEntitySplitByAndMain")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Ordering")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderingDirection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OverrideReportBreaks")
                        .HasColumnType("bit");

                    b.Property<string>("PaneId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PartType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductShortCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte?>("ReportOrder")
                        .HasColumnType("tinyint");

                    b.Property<string>("Sections")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SelectedEntityInstances")
                        .HasColumnType("varchar(max)");

                    b.Property<int?>("ShowTop")
                        .HasColumnType("int");

                    b.Property<string>("Spec1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Spec2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Spec3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubProductId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Waves")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("XRange")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YRange")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductShortCode", "SubProductId", "PaneId");

                    b.ToTable("Parts");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.PageAbout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AboutContent")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("AboutTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Editable")
                        .HasColumnType("bit");

                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.Property<string>("ProductShortCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("User")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ProductShortCode", "PageId");

                    b.ToTable("PageAbout");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.Reports.DefaultSavedReport", b =>
                {
                    b.Property<string>("ProductShortCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SubProductId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.HasKey("ProductShortCode", "SubProductId");

                    b.HasIndex("ReportId");

                    b.ToTable("DefaultSavedReports", "Reports");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.Reports.SavedReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<byte?>("BaseTypeOverride")
                        .HasColumnType("tinyint");

                    b.Property<int?>("BaseVariableId")
                        .HasColumnType("int");

                    b.Property<string>("Breaks")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DecimalPlaces")
                        .HasColumnType("int");

                    b.Property<string>("DefaultFilters")
                        .HasColumnType("varchar(max)");

                    b.Property<bool>("HideEmptyRows")
                        .HasColumnType("bit");

                    b.Property<bool>("HighlightLowSample")
                        .HasColumnType("bit");

                    b.Property<bool>("HighlightSignificance")
                        .HasColumnType("bit");

                    b.Property<bool>("IncludeCounts")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDataWeighted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsShared")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedGuid")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<byte>("Order")
                        .HasColumnType("tinyint");

                    b.Property<string>("ProductShortCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ReportPageId")
                        .HasColumnType("int");

                    b.Property<byte>("ReportType")
                        .HasColumnType("tinyint");

                    b.Property<byte>("SignificanceType")
                        .HasColumnType("tinyint");

                    b.Property<bool>("SinglePageExport")
                        .HasColumnType("bit");

                    b.Property<string>("SubProductId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Waves")
                        .HasColumnType("varchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ReportPageId");

                    b.HasIndex("ProductShortCode", "SubProductId");

                    b.ToTable("SavedReports", "Reports");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.ReportVue.ReportVueProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProductShortCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SubProductId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ProductShortCode", "SubProductId", "Name")
                        .IsUnique();

                    b.ToTable("Projects", "ReportVue");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.ReportVue.ReportVueProjectPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("BrandName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FilterId")
                        .HasColumnType("int");

                    b.Property<string>("FilterName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.Property<string>("PageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectReleaseId")
                        .HasColumnType("int");

                    b.Property<string>("SectionName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectReleaseId", "PageId", "FilterId", "BrandId")
                        .IsUnique();

                    b.ToTable("ProjectPages", "ReportVue");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.ReportVue.ReportVueProjectPageTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("ReportVueProjectPageId")
                        .HasColumnType("int");

                    b.Property<string>("TagName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TagValue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ReportVueProjectPageId");

                    b.ToTable("Tags", "ReportVue");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.ReportVue.ReportVueProjectRelease", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ParentProjectId")
                        .HasColumnType("int");

                    b.Property<string>("ReasonForRelease")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UniqueFolderName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserTextForBrandEntity")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("VersionOfRelease")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentProjectId");

                    b.HasIndex("UniqueFolderName")
                        .IsUnique();

                    b.ToTable("ProjectReleases", "ReportVue");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.SavedBreakCombination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AuthCompanyShortCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Breaks")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasMaxLength(750)
                        .HasColumnType("nvarchar(750)");

                    b.Property<bool>("IsShared")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProductShortCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SubProductId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ProductShortCode", "SubProductId", "AuthCompanyShortCode");

                    b.ToTable("SavedBreakCombinations", "SavedBreaks");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.SubsetConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Alias")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("AlwaysShowDataUpToCurrentDate")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("DisplayNameShort")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("EnableRawDataApiAccess")
                        .HasColumnType("bit");

                    b.Property<string>("Identifier")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Iso2LetterCountryCode")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("OverriddenStartDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ProductShortCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SubProductId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SurveyIdToAllowedSegmentNames")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Id");

                    b.ToTable("SubsetConfigurations");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.SupportableUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("FreshchatConversationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("SupportableUsers");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.VariableDefinitions.VariableConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Definition")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ProductShortCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SubProductId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ProductShortCode", "SubProductId", "DisplayName")
                        .IsUnique()
                        .HasFilter("[SubProductId] IS NOT NULL");

                    b.ToTable("VariableConfigurations");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.VariableDefinitions.VariableDependency", b =>
                {
                    b.Property<int>("VariableId")
                        .HasColumnType("int");

                    b.Property<int>("DependentUponVariableId")
                        .HasColumnType("int");

                    b.HasKey("VariableId", "DependentUponVariableId");

                    b.HasIndex("DependentUponVariableId");

                    b.ToTable("VariableDependencies");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.Weightings.ResponseWeight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("RespondentId")
                        .HasColumnType("int");

                    b.Property<int>("ResponseWeightingContextId")
                        .HasColumnType("int");

                    b.Property<decimal>("Weight")
                        .HasPrecision(20, 10)
                        .HasColumnType("decimal(20,10)");

                    b.HasKey("Id");

                    b.HasIndex("ResponseWeightingContextId");

                    b.ToTable("ResponseWeights");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.Weightings.ResponseWeightingContext", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ProductShortCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SubProductId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SubsetId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProductShortCode", "SubProductId", "SubsetId", "Context")
                        .IsUnique();

                    b.ToTable("ResponseWeightingContexts");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.Weightings.WeightingPlanConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsWeightingGroupRoot")
                        .HasColumnType("bit");

                    b.Property<int?>("ParentWeightingTargetId")
                        .HasColumnType("int");

                    b.Property<string>("ProductShortCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SubProductId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SubsetId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VariableIdentifier")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ParentWeightingTargetId");

                    b.HasIndex("ProductShortCode", "SubProductId", "SubsetId", "ParentWeightingTargetId", "VariableIdentifier")
                        .IsUnique();

                    b.ToTable("WeightingPlans");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.Weightings.WeightingScheme", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<int?>("FilterMetricEntityId")
                        .HasColumnType("int");

                    b.Property<string>("WeightingSchemeDetails")
                        .HasColumnType("varchar(max)");

                    b.Property<int>("WeightingStrategyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WeightingStrategyId", "FilterMetricEntityId")
                        .IsUnique();

                    b.ToTable("WeightingSchemes");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.Weightings.WeightingStrategy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FilterMetricName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProductShortCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SubProductId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SubsetId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProductShortCode", "SubProductId", "Name")
                        .IsUnique();

                    b.HasIndex("ProductShortCode", "SubProductId", "SubsetId")
                        .IsUnique();

                    b.ToTable("WeightingStrategies");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.Weightings.WeightingTargetConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("EntityInstanceId")
                        .HasColumnType("int");

                    b.Property<int>("ParentWeightingPlanId")
                        .HasColumnType("int");

                    b.Property<string>("ProductShortCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SubProductId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SubsetId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Target")
                        .HasPrecision(20, 10)
                        .HasColumnType("decimal(20,10)");

                    b.HasKey("Id");

                    b.HasIndex("ParentWeightingPlanId");

                    b.HasIndex("ProductShortCode", "SubProductId", "SubsetId", "ParentWeightingPlanId", "EntityInstanceId")
                        .IsUnique();

                    b.ToTable("WeightingTargets");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.DefaultSavedBreaks", b =>
                {
                    b.HasOne("BrandVue.EntityFramework.MetaData.SavedBreakCombination", "SavedBreakCombination")
                        .WithMany()
                        .HasForeignKey("SavedBreakCombinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SavedBreakCombination");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.EntitySetAverageMappingConfiguration", b =>
                {
                    b.HasOne("BrandVue.EntityFramework.MetaData.EntitySetConfiguration", null)
                        .WithMany("AverageMappings")
                        .HasForeignKey("EntitySetConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.Reports.DefaultSavedReport", b =>
                {
                    b.HasOne("BrandVue.EntityFramework.MetaData.Reports.SavedReport", "Report")
                        .WithMany()
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.Reports.SavedReport", b =>
                {
                    b.HasOne("BrandVue.EntityFramework.MetaData.Page.DbPage", "ReportPage")
                        .WithMany()
                        .HasForeignKey("ReportPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportPage");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.ReportVue.ReportVueProjectPage", b =>
                {
                    b.HasOne("BrandVue.EntityFramework.MetaData.ReportVue.ReportVueProjectRelease", "ProjectRelease")
                        .WithMany("ProjectPages")
                        .HasForeignKey("ProjectReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectRelease");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.ReportVue.ReportVueProjectPageTag", b =>
                {
                    b.HasOne("BrandVue.EntityFramework.MetaData.ReportVue.ReportVueProjectPage", null)
                        .WithMany("Tags")
                        .HasForeignKey("ReportVueProjectPageId");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.ReportVue.ReportVueProjectRelease", b =>
                {
                    b.HasOne("BrandVue.EntityFramework.MetaData.ReportVue.ReportVueProject", "Project")
                        .WithMany("ProjectReleases")
                        .HasForeignKey("ParentProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.VariableDefinitions.VariableDependency", b =>
                {
                    b.HasOne("BrandVue.EntityFramework.MetaData.VariableDefinitions.VariableConfiguration", "DependentUponVariable")
                        .WithMany("VariablesDependingOnThis")
                        .HasForeignKey("DependentUponVariableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BrandVue.EntityFramework.MetaData.VariableDefinitions.VariableConfiguration", "Variable")
                        .WithMany("VariableDependencies")
                        .HasForeignKey("VariableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DependentUponVariable");

                    b.Navigation("Variable");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.Weightings.ResponseWeight", b =>
                {
                    b.HasOne("BrandVue.EntityFramework.MetaData.Weightings.ResponseWeightingContext", null)
                        .WithMany("ResponseWeights")
                        .HasForeignKey("ResponseWeightingContextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.Weightings.WeightingPlanConfiguration", b =>
                {
                    b.HasOne("BrandVue.EntityFramework.MetaData.Weightings.WeightingTargetConfiguration", "ParentTarget")
                        .WithMany("ChildPlans")
                        .HasForeignKey("ParentWeightingTargetId");

                    b.Navigation("ParentTarget");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.Weightings.WeightingScheme", b =>
                {
                    b.HasOne("BrandVue.EntityFramework.MetaData.Weightings.WeightingStrategy", null)
                        .WithMany("WeightingSchemes")
                        .HasForeignKey("WeightingStrategyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.Weightings.WeightingTargetConfiguration", b =>
                {
                    b.HasOne("BrandVue.EntityFramework.MetaData.Weightings.WeightingPlanConfiguration", "ParentWeightingPlan")
                        .WithMany("ChildTargets")
                        .HasForeignKey("ParentWeightingPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentWeightingPlan");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.EntitySetConfiguration", b =>
                {
                    b.Navigation("AverageMappings");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.ReportVue.ReportVueProject", b =>
                {
                    b.Navigation("ProjectReleases");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.ReportVue.ReportVueProjectPage", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.ReportVue.ReportVueProjectRelease", b =>
                {
                    b.Navigation("ProjectPages");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.VariableDefinitions.VariableConfiguration", b =>
                {
                    b.Navigation("VariableDependencies");

                    b.Navigation("VariablesDependingOnThis");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.Weightings.ResponseWeightingContext", b =>
                {
                    b.Navigation("ResponseWeights");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.Weightings.WeightingPlanConfiguration", b =>
                {
                    b.Navigation("ChildTargets");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.Weightings.WeightingStrategy", b =>
                {
                    b.Navigation("WeightingSchemes");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.MetaData.Weightings.WeightingTargetConfiguration", b =>
                {
                    b.Navigation("ChildPlans");
                });
#pragma warning restore 612, 618
        }
    }
}
