// <auto-generated />
using System;
using BrandVue.EntityFramework.Answers;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BrandVue.EntityFramework.Migrations.AnswersDb
{
    [DbContext(typeof(AnswersDbContext))]
    [Migration("20210225084533_AddItemNumberToQuestion")]
    partial class AddItemNumberToQuestion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("vue")
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("BrandVue.EntityFramework.Answers.Model.Answer", b =>
                {
                    b.Property<int?>("AnswerChoiceId")
                        .HasColumnType("int");

                    b.Property<string>("AnswerText")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int?>("AnswerValue")
                        .HasColumnType("int");

                    b.Property<int?>("PageChoiceId")
                        .HasColumnType("int");

                    b.Property<int?>("QuestionChoiceId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("ResponseId")
                        .HasColumnType("int");

                    b.Property<int?>("SectionChoiceId")
                        .HasColumnType("int");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.Answers.Model.AnswerStat", b =>
                {
                    b.Property<int?>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("RespondentCount")
                        .HasColumnType("int");

                    b.HasIndex("QuestionId");

                    b.ToTable("AnswerStats");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.Answers.Model.Choice", b =>
                {
                    b.Property<int>("ChoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ChoiceSetId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SurveyChoiceId")
                        .HasColumnType("int");

                    b.Property<int>("SurveyId")
                        .HasColumnType("int");

                    b.HasKey("ChoiceId");

                    b.HasIndex("ChoiceSetId", "SurveyChoiceId")
                        .IsUnique();

                    b.ToTable("Choices");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.Answers.Model.ChoiceSet", b =>
                {
                    b.Property<int>("ChoiceSetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ParentChoiceSet1Id")
                        .HasColumnType("int");

                    b.Property<int?>("ParentChoiceSet2Id")
                        .HasColumnType("int");

                    b.Property<int>("SurveyId")
                        .HasColumnType("int");

                    b.HasKey("ChoiceSetId");

                    b.HasIndex("ParentChoiceSet1Id");

                    b.HasIndex("ParentChoiceSet2Id");

                    b.HasIndex("SurveyId", "Name")
                        .IsUnique();

                    b.ToTable("ChoiceSets");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.Answers.Model.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("AnswerChoiceSetId")
                        .HasColumnType("int");

                    b.Property<int?>("ItemNumber")
                        .HasColumnType("int");

                    b.Property<string>("MasterType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PageChoiceSetId")
                        .HasColumnType("int");

                    b.Property<int?>("QuestionChoiceSetId")
                        .HasColumnType("int");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("SectionChoiceSetId")
                        .HasColumnType("int");

                    b.Property<int>("SurveyId")
                        .HasColumnType("int");

                    b.Property<string>("VarCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("QuestionId");

                    b.HasIndex("AnswerChoiceSetId");

                    b.HasIndex("PageChoiceSetId");

                    b.HasIndex("QuestionChoiceSetId");

                    b.HasIndex("SectionChoiceSetId");

                    b.HasIndex("SurveyId", "VarCode")
                        .IsUnique();

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.Answers.Model.SurveyResponse", b =>
                {
                    b.Property<int>("ResponseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("responseId")
                        .UseIdentityColumn();

                    b.Property<int>("SegmentId")
                        .HasColumnType("int")
                        .HasColumnName("segmentId");

                    b.Property<int>("SurveyId")
                        .HasColumnType("int")
                        .HasColumnName("surveyId");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("datetime")
                        .HasColumnName("timestamp");

                    b.HasKey("ResponseId");

                    b.ToTable("SurveyResponse", "dbo");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.Answers.Model.SurveySegment", b =>
                {
                    b.Property<int>("SurveySegmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("surveySegmentId")
                        .UseIdentityColumn();

                    b.Property<string>("SegmentName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("segmentName");

                    b.HasKey("SurveySegmentId");

                    b.ToTable("surveySegments", "dbo");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.Answers.Model.SurveyStructures", b =>
                {
                    b.Property<int>("SurveyStructureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("surveyStructureId")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("SurveyStructureId");

                    b.ToTable("surveyStructures", "dbo");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.Answers.Model.Surveys", b =>
                {
                    b.Property<int>("SurveyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("surveyId")
                        .UseIdentityColumn();

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<int>("SurveyStructureId")
                        .HasColumnType("int")
                        .HasColumnName("surveyStructureId");

                    b.Property<string>("UniqueSurveyId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("uniqueSurveyId");

                    b.HasKey("SurveyId");

                    b.ToTable("surveys", "dbo");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.Answers.Model.Answer", b =>
                {
                    b.HasOne("BrandVue.EntityFramework.Answers.Model.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.Answers.Model.AnswerStat", b =>
                {
                    b.HasOne("BrandVue.EntityFramework.Answers.Model.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.Answers.Model.Choice", b =>
                {
                    b.HasOne("BrandVue.EntityFramework.Answers.Model.ChoiceSet", "ChoiceSet")
                        .WithMany("Choices")
                        .HasForeignKey("ChoiceSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChoiceSet");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.Answers.Model.ChoiceSet", b =>
                {
                    b.HasOne("BrandVue.EntityFramework.Answers.Model.ChoiceSet", "ParentChoiceSet1")
                        .WithMany("DirectDescendants")
                        .HasForeignKey("ParentChoiceSet1Id");

                    b.HasOne("BrandVue.EntityFramework.Answers.Model.ChoiceSet", "ParentChoiceSet2")
                        .WithMany("AddedDescendants")
                        .HasForeignKey("ParentChoiceSet2Id");

                    b.Navigation("ParentChoiceSet1");

                    b.Navigation("ParentChoiceSet2");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.Answers.Model.Question", b =>
                {
                    b.HasOne("BrandVue.EntityFramework.Answers.Model.ChoiceSet", "AnswerChoiceSet")
                        .WithMany()
                        .HasForeignKey("AnswerChoiceSetId");

                    b.HasOne("BrandVue.EntityFramework.Answers.Model.ChoiceSet", "PageChoiceSet")
                        .WithMany()
                        .HasForeignKey("PageChoiceSetId");

                    b.HasOne("BrandVue.EntityFramework.Answers.Model.ChoiceSet", "QuestionChoiceSet")
                        .WithMany()
                        .HasForeignKey("QuestionChoiceSetId");

                    b.HasOne("BrandVue.EntityFramework.Answers.Model.ChoiceSet", "SectionChoiceSet")
                        .WithMany()
                        .HasForeignKey("SectionChoiceSetId");

                    b.Navigation("AnswerChoiceSet");

                    b.Navigation("PageChoiceSet");

                    b.Navigation("QuestionChoiceSet");

                    b.Navigation("SectionChoiceSet");
                });

            modelBuilder.Entity("BrandVue.EntityFramework.Answers.Model.ChoiceSet", b =>
                {
                    b.Navigation("AddedDescendants");

                    b.Navigation("Choices");

                    b.Navigation("DirectDescendants");
                });
#pragma warning restore 612, 618
        }
    }
}
