namespace BrandVue.SourceData.Subsets
{
    public static class Iso2LetterCountryCodesLowercase
    {
        // ISO 3166-1 two-letter country codes
        // Sourced from: https://en.wikipedia.org/wiki/ISO_3166-1

        public const string AD = "ad";  //  Andorra
        public const string AE = "ae";  //  United Arab Emirates
        public const string AF = "af";  //  Afghanistan
        public const string AG = "ag";  //  Antigua and Barbuda
        public const string AI = "ai";  //  Anguilla
        public const string AL = "al";  //  Albania
        public const string AM = "am";  //  Armenia
        public const string AO = "ao";  //  Angola
        public const string AQ = "aq";  //  Antarctica
        public const string AR = "ar";  //  Argentina
        public const string AS = "as";  //  American Samoa
        public const string AT = "at";  //  Austria
        public const string AU = "au";  //  Australia
        public const string AW = "aw";  //  Aruba
        public const string AX = "ax";  //  Åland Islands
        public const string AZ = "az";  //  Azerbaijan
        public const string BA = "ba";  //  Bosnia and Herzegovina
        public const string BB = "bb";  //  Barbados
        public const string BD = "bd";  //  Bangladesh
        public const string BE = "be";  //  Belgium
        public const string BF = "bf";  //  Burkina Faso
        public const string BG = "bg";  //  Bulgaria
        public const string BH = "bh";  //  Bahrain
        public const string BI = "bi";  //  Burundi
        public const string BJ = "bj";  //  Benin
        public const string BL = "bl";  //  Saint Barthélemy
        public const string BM = "bm";  //  Bermuda
        public const string BN = "bn";  //  Brunei Darussalam
        public const string BO = "bo";  //  Bolivia (Plurinational State of)
        public const string BQ = "bq";  //  Bonaire, Sint Eustatius and Saba
        public const string BR = "br";  //  Brazil
        public const string BS = "bs";  //  Bahamas
        public const string BT = "bt";  //  Bhutan
        public const string BV = "bv";  //  Bouvet Island
        public const string BW = "bw";  //  Botswana
        public const string BY = "by";  //  Belarus
        public const string BZ = "bz";  //  Belize
        public const string CA = "ca";  //  Canada
        public const string CC = "cc";  //  Cocos (Keeling) Islands
        public const string CD = "cd";  //  Congo, Democratic Republic of the
        public const string CF = "cf";  //  Central African Republic
        public const string CG = "cg";  //  Congo
        public const string CH = "ch";  //  Switzerland
        public const string CI = "ci";  //  Côte d'Ivoire
        public const string CK = "ck";  //  Cook Islands
        public const string CL = "cl";  //  Chile
        public const string CM = "cm";  //  Cameroon
        public const string CN = "cn";  //  China
        public const string CO = "co";  //  Colombia
        public const string CR = "cr";  //  Costa Rica
        public const string CU = "cu";  //  Cuba
        public const string CV = "cv";  //  Cabo Verde
        public const string CW = "cw";  //  Curaçao
        public const string CX = "cx";  //  Christmas Island
        public const string CY = "cy";  //  Cyprus
        public const string CZ = "cz";  //  Czechia
        public const string DE = "de";  //  Germany
        public const string DJ = "dj";  //  Djibouti
        public const string DK = "dk";  //  Denmark
        public const string DM = "dm";  //  Dominica
        public const string DO = "do";  //  Dominican Republic
        public const string DZ = "dz";  //  Algeria
        public const string EC = "ec";  //  Ecuador
        public const string EE = "ee";  //  Estonia
        public const string EG = "eg";  //  Egypt
        public const string EH = "eh";  //  Western Sahara
        public const string ER = "er";  //  Eritrea
        public const string ES = "es";  //  Spain
        public const string ET = "et";  //  Ethiopia
        public const string FI = "fi";  //  Finland
        public const string FJ = "fj";  //  Fiji
        public const string FK = "fk";  //  Falkland Islands (Malvinas)
        public const string FM = "fm";  //  Micronesia (Federated States of)
        public const string FO = "fo";  //  Faroe Islands
        public const string FR = "fr";  //  France
        public const string GA = "ga";  //  Gabon
        public const string GB = "gb";  //  United Kingdom of Great Britain and Northern Ireland
        public const string GD = "gd";  //  Grenada
        public const string GE = "ge";  //  Georgia
        public const string GF = "gf";  //  French Guiana
        public const string GG = "gg";  //  Guernsey
        public const string GH = "gh";  //  Ghana
        public const string GI = "gi";  //  Gibraltar
        public const string GL = "gl";  //  Greenland
        public const string GM = "gm";  //  Gambia
        public const string GN = "gn";  //  Guinea
        public const string GP = "gp";  //  Guadeloupe
        public const string GQ = "gq";  //  Equatorial Guinea
        public const string GR = "gr";  //  Greece
        public const string GS = "gs";  //  South Georgia and the South Sandwich Islands
        public const string GT = "gt";  //  Guatemala
        public const string GU = "gu";  //  Guam
        public const string GW = "gw";  //  Guinea-Bissau
        public const string GY = "gy";  //  Guyana
        public const string HK = "hk";  //  Hong Kong
        public const string HM = "hm";  //  Heard Island and McDonald Islands
        public const string HN = "hn";  //  Honduras
        public const string HR = "hr";  //  Croatia
        public const string HT = "ht";  //  Haiti
        public const string HU = "hu";  //  Hungary
        public const string ID = "id";  //  Indonesia
        public const string IE = "ie";  //  Ireland
        public const string IL = "il";  //  Israel
        public const string IM = "im";  //  Isle of Man
        public const string IN = "in";  //  India
        public const string IO = "io";  //  British Indian Ocean Territory
        public const string IQ = "iq";  //  Iraq
        public const string IR = "ir";  //  Iran (Islamic Republic of)
        public const string IS = "is";  //  Iceland
        public const string IT = "it";  //  Italy
        public const string JE = "je";  //  Jersey
        public const string JM = "jm";  //  Jamaica
        public const string JO = "jo";  //  Jordan
        public const string JP = "jp";  //  Japan
        public const string KE = "ke";  //  Kenya
        public const string KG = "kg";  //  Kyrgyzstan
        public const string KH = "kh";  //  Cambodia
        public const string KI = "ki";  //  Kiribati
        public const string KM = "km";  //  Comoros
        public const string KN = "kn";  //  Saint Kitts and Nevis
        public const string KP = "kp";  //  Korea (Democratic People's Republic of)
        public const string KR = "kr";  //  Korea, Republic of
        public const string KW = "kw";  //  Kuwait
        public const string KY = "ky";  //  Cayman Islands
        public const string KZ = "kz";  //  Kazakhstan
        public const string LA = "la";  //  Lao People's Democratic Republic
        public const string LB = "lb";  //  Lebanon
        public const string LC = "lc";  //  Saint Lucia
        public const string LI = "li";  //  Liechtenstein
        public const string LK = "lk";  //  Sri Lanka
        public const string LR = "lr";  //  Liberia
        public const string LS = "ls";  //  Lesotho
        public const string LT = "lt";  //  Lithuania
        public const string LU = "lu";  //  Luxembourg
        public const string LV = "lv";  //  Latvia
        public const string LY = "ly";  //  Libya
        public const string MA = "ma";  //  Morocco
        public const string MC = "mc";  //  Monaco
        public const string MD = "md";  //  Moldova, Republic of
        public const string ME = "me";  //  Montenegro
        public const string MF = "mf";  //  Saint Martin (French part)
        public const string MG = "mg";  //  Madagascar
        public const string MH = "mh";  //  Marshall Islands
        public const string MK = "mk";  //  North Macedonia
        public const string ML = "ml";  //  Mali
        public const string MM = "mm";  //  Myanmar
        public const string MN = "mn";  //  Mongolia
        public const string MO = "mo";  //  Macao
        public const string MP = "mp";  //  Northern Mariana Islands
        public const string MQ = "mq";  //  Martinique
        public const string MR = "mr";  //  Mauritania
        public const string MS = "ms";  //  Montserrat
        public const string MT = "mt";  //  Malta
        public const string MU = "mu";  //  Mauritius
        public const string MV = "mv";  //  Maldives
        public const string MW = "mw";  //  Malawi
        public const string MX = "mx";  //  Mexico
        public const string MY = "my";  //  Malaysia
        public const string MZ = "mz";  //  Mozambique
        public const string NA = "na";  //  Namibia
        public const string NC = "nc";  //  New Caledonia
        public const string NE = "ne";  //  Niger
        public const string NF = "nf";  //  Norfolk Island
        public const string NG = "ng";  //  Nigeria
        public const string NI = "ni";  //  Nicaragua
        public const string NL = "nl";  //  Netherlands
        public const string NO = "no";  //  Norway
        public const string NP = "np";  //  Nepal
        public const string NR = "nr";  //  Nauru
        public const string NU = "nu";  //  Niue
        public const string NZ = "nz";  //  New Zealand
        public const string OM = "om";  //  Oman
        public const string PA = "pa";  //  Panama
        public const string PE = "pe";  //  Peru
        public const string PF = "pf";  //  French Polynesia
        public const string PG = "pg";  //  Papua New Guinea
        public const string PH = "ph";  //  Philippines
        public const string PK = "pk";  //  Pakistan
        public const string PL = "pl";  //  Poland
        public const string PM = "pm";  //  Saint Pierre and Miquelon
        public const string PN = "pn";  //  Pitcairn
        public const string PR = "pr";  //  Puerto Rico
        public const string PS = "ps";  //  Palestine, State of
        public const string PT = "pt";  //  Portugal
        public const string PW = "pw";  //  Palau
        public const string PY = "py";  //  Paraguay
        public const string QA = "qa";  //  Qatar
        public const string RE = "re";  //  Réunion
        public const string RO = "ro";  //  Romania
        public const string RS = "rs";  //  Serbia
        public const string RU = "ru";  //  Russian Federation
        public const string RW = "rw";  //  Rwanda
        public const string SA = "sa";  //  Saudi Arabia
        public const string SB = "sb";  //  Solomon Islands
        public const string SC = "sc";  //  Seychelles
        public const string SD = "sd";  //  Sudan
        public const string SE = "se";  //  Sweden
        public const string SG = "sg";  //  Singapore
        public const string SH = "sh";  //  Saint Helena, Ascension and Tristan da Cunha
        public const string SI = "si";  //  Slovenia
        public const string SJ = "sj";  //  Svalbard and Jan Mayen
        public const string SK = "sk";  //  Slovakia
        public const string SL = "sl";  //  Sierra Leone
        public const string SM = "sm";  //  San Marino
        public const string SN = "sn";  //  Senegal
        public const string SO = "so";  //  Somalia
        public const string SR = "sr";  //  Suriname
        public const string SS = "ss";  //  South Sudan
        public const string ST = "st";  //  Sao Tome and Principe
        public const string SV = "sv";  //  El Salvador
        public const string SX = "sx";  //  Sint Maarten (Dutch part)
        public const string SY = "sy";  //  Syrian Arab Republic
        public const string SZ = "sz";  //  Eswatini
        public const string TC = "tc";  //  Turks and Caicos Islands
        public const string TD = "td";  //  Chad
        public const string TF = "tf";  //  French Southern Territories
        public const string TG = "tg";  //  Togo
        public const string TH = "th";  //  Thailand
        public const string TJ = "tj";  //  Tajikistan
        public const string TK = "tk";  //  Tokelau
        public const string TL = "tl";  //  Timor-Leste
        public const string TM = "tm";  //  Turkmenistan
        public const string TN = "tn";  //  Tunisia
        public const string TO = "to";  //  Tonga
        public const string TR = "tr";  //  Turkey
        public const string TT = "tt";  //  Trinidad and Tobago
        public const string TV = "tv";  //  Tuvalu
        public const string TW = "tw";  //  Taiwan, Province of China[a]
        public const string TZ = "tz";  //  Tanzania, United Republic of
        public const string UA = "ua";  //  Ukraine
        public const string UG = "ug";  //  Uganda
        public const string UM = "um";  //  United States Minor Outlying Islands
        public const string US = "us";  //  United States of America
        public const string UY = "uy";  //  Uruguay
        public const string UZ = "uz";  //  Uzbekistan
        public const string VA = "va";  //  Holy See
        public const string VC = "vc";  //  Saint Vincent and the Grenadines
        public const string VE = "ve";  //  Venezuela (Bolivarian Republic of)
        public const string VG = "vg";  //  Virgin Islands (British)
        public const string VI = "vi";  //  Virgin Islands (U.S.)
        public const string VN = "vn";  //  Viet Nam
        public const string VU = "vu";  //  Vanuatu
        public const string WF = "wf";  //  Wallis and Futuna
        public const string WS = "ws";  //  Samoa
        public const string YE = "ye";  //  Yemen
        public const string YT = "yt";  //  Mayotte
        public const string ZA = "za";  //  South Africa
        public const string ZM = "zm";  //  Zambia
        public const string ZW = "zw";  //  Zimbabwe
    }
}
