using System.Collections.Generic;
using BrandVue.EntityFramework;
using BrandVue.EntityFramework.Answers.Model;
using BrandVue.EntityFramework.MetaData;
using BrandVue.EntityFramework.MetaData.VariableDefinitions;
using BrandVue.SourceData.AutoGeneration;
using BrandVue.SourceData.Respondents;
using BrandVue.SourceData.Subsets;
using NSubstitute;
using NUnit.Framework;

namespace Test.BrandVue.SourceData.AutoGeneration
{
    [TestFixture]
    public class BucketedMetricConfigurationCreatorTests
    {
        private readonly Subset _testSubset = new() {Id = "54321"};
        private readonly FieldDefinitionModel _field =
            new("Test", "", "", "", "", null, "", 0.0, "", false, null, new List<EntityFieldDefinitionModel>(), null)
            {
                QuestionModel = new Question
                {
                    QuestionText = "Test question text"
                }
            };


        private readonly VariableConfiguration _bucketedVariableConfig = new()
        {
            Id = 987
        };

        [Test]
        public void CreateBucketedMetricConfiguration_WithFieldAndVariable_CreatesNewMetric()
        {
            var productContext = Substitute.For<IProductContext>();
            productContext.ShortCode.Returns("TestShortcode");
            productContext.SubProductId.Returns("12345");
            var bucketedMetricCreator = new BucketedMetricConfigurationCreator(Substitute.For<IMetricConfigurationRepository>(), productContext);

            var numericFieldData = new NumericFieldData(_field, _testSubset.Id);
            numericFieldData.SetOriginalMetricName("Test");
            var bucketedMetric = bucketedMetricCreator.CreateBucketedMetricConfiguration(numericFieldData, _bucketedVariableConfig);

            Assert.That(bucketedMetric.Name.StartsWith(AutoGenerationConstants.NumericIdentifier + ": Test"), Is.True);
            Assert.That(bucketedMetric.HelpText, Is.EqualTo(_field.QuestionModel.QuestionText));
            Assert.That(bucketedMetric.VarCode, Is.EqualTo(_field.FullV2VarCode));
            Assert.That(bucketedMetric.SubProductId, Is.EqualTo("12345"));
            Assert.That(bucketedMetric.ProductShortCode, Is.EqualTo("TestShortcode"));
            Assert.That(bucketedMetric.CalcType, Is.EqualTo("yn"));
            Assert.That(bucketedMetric.NumFormat, Is.EqualTo("0%"));
            Assert.That(bucketedMetric.IsAutoGenerated, Is.EqualTo(AutoGenerationType.CreatedFromNumeric));
            Assert.That(bucketedMetric.VariableConfigurationId, Is.EqualTo(_bucketedVariableConfig.Id));
        }
    }
}