using System.Collections;
using System.Collections.Generic;
using System.Linq;
using BrandVue.EntityFramework.Answers.Model;
using BrandVue.EntityFramework.MetaData;
using BrandVue.SourceData.AutoGeneration;
using BrandVue.SourceData.Entity;
using BrandVue.SourceData.Respondents;
using BrandVue.SourceData.Subsets;
using NSubstitute;
using NUnit.Framework;
using Test.BrandVue.SourceData.AnswersMetadata;

namespace Test.BrandVue.SourceData.AutoGeneration
{
    [TestFixture]
    public class NumericFieldDefinitionCollectorTests
    {
        private static readonly Subset TestSubsetOne = new(){ Id = "123456"};
        private static readonly Subset TestSubsetTwo = new(){ Id = "78910"};

        internal class NumericDefinitionFieldCollectorTestParameterEnumerator : IEnumerable
        {
            private const string Slider = "SLIDER";
            private const string Radio = "RADIO";
            private static readonly FieldDefinitionModel SliderWithOutChoiceSet = GetStubbedFieldDefinitionModel("TestOne", Slider, false);
            private static readonly FieldDefinitionModel RadioWithOutChoiceSet = GetStubbedFieldDefinitionModel("TestTwo", Radio, false);
            private static readonly FieldDefinitionModel SliderWithChoiceSet = GetStubbedFieldDefinitionModel("TestThree", Slider, true);
            private static readonly FieldDefinitionModel SliderWithOutChoiceSetDifferentName = GetStubbedFieldDefinitionModel("TestFour", Slider, false);

            private class NumericDefinitionCollectorTestParameters
            {
                public IList<MetricConfiguration> ExistingMetrics { get; set; }
                public IList<ResponseFieldDescriptor> LoadedFields { get; set; }
                public IList<NumericFieldData> ExpectedNumericFieldDefinitions { get; set; }
                public IList<Subset> TestSubsets { get; set; }
            }

            private readonly NumericDefinitionCollectorTestParameters _singleNumericField = new()
            {
                ExistingMetrics = new List<MetricConfiguration>(),
                LoadedFields = new List<ResponseFieldDescriptor>
                {
                    GetStubbedResponseFieldDescriptor(0, "Test", SliderWithOutChoiceSet, TestSubsetOne)
                },
                ExpectedNumericFieldDefinitions = new List<NumericFieldData>
                {
                    GetStubbedNumericField(SliderWithOutChoiceSet, new(){TestSubsetOne})
                },
                TestSubsets = new List<Subset>{ TestSubsetOne }
            };
            
            private readonly NumericDefinitionCollectorTestParameters _singleRadioField = new()
            {
                ExistingMetrics = new List<MetricConfiguration>(),
                LoadedFields = new List<ResponseFieldDescriptor>
                {
                    GetStubbedResponseFieldDescriptor(0, "Test", RadioWithOutChoiceSet, TestSubsetOne)
                },
                ExpectedNumericFieldDefinitions = new List<NumericFieldData>(),
                TestSubsets = new List<Subset>{ TestSubsetOne }
            };
            
            private readonly NumericDefinitionCollectorTestParameters _singleNumericFieldWithEntity = new()
            {
                ExistingMetrics = new List<MetricConfiguration>(),
                LoadedFields = new List<ResponseFieldDescriptor>
                {
                    GetStubbedResponseFieldDescriptor(1, "Test", SliderWithChoiceSet, TestSubsetOne)
                },
                ExpectedNumericFieldDefinitions = new List<NumericFieldData>(),
                TestSubsets = new List<Subset>{ TestSubsetOne }
            };
            
            private readonly NumericDefinitionCollectorTestParameters _multipleField = new()
            {
                ExistingMetrics = new List<MetricConfiguration>(),
                LoadedFields = new List<ResponseFieldDescriptor>
                {
                    GetStubbedResponseFieldDescriptor(0, "Test", RadioWithOutChoiceSet, TestSubsetOne),
                    GetStubbedResponseFieldDescriptor(0, "Test", SliderWithOutChoiceSet, TestSubsetOne),
                    GetStubbedResponseFieldDescriptor(1, "Test", SliderWithChoiceSet, TestSubsetOne)
                },
                ExpectedNumericFieldDefinitions = new List<NumericFieldData>
                {
                    GetStubbedNumericField(SliderWithOutChoiceSet, new(){TestSubsetOne})
                },
                TestSubsets = new List<Subset>{ TestSubsetOne }
            };
            
            private readonly NumericDefinitionCollectorTestParameters _numericFieldAlreadyExists = new()
            {
                ExistingMetrics = new List<MetricConfiguration>
                {
                    new() { IsAutoGenerated = AutoGenerationType.CreatedFromNumeric, Field = "TestOne" }
                },
                LoadedFields = new List<ResponseFieldDescriptor>
                {
                    GetStubbedResponseFieldDescriptor(0, "Test", SliderWithOutChoiceSet, TestSubsetOne)
                },
                ExpectedNumericFieldDefinitions = new List<NumericFieldData>(),
                TestSubsets = new List<Subset>{ TestSubsetOne }
            };
            
            private readonly NumericDefinitionCollectorTestParameters _duplicateFieldsDifferentSubsetsReturnsOne = new()
            {
                ExistingMetrics = new List<MetricConfiguration>(),
                LoadedFields = new List<ResponseFieldDescriptor>
                {
                    GetStubbedResponseFieldDescriptor(0, "Test", SliderWithOutChoiceSet, TestSubsetOne),
                    GetStubbedResponseFieldDescriptor(0, "Test", SliderWithOutChoiceSet, TestSubsetTwo)
                },
                ExpectedNumericFieldDefinitions = new List<NumericFieldData>
                {
                    GetStubbedNumericField(SliderWithOutChoiceSet, new(){TestSubsetOne, TestSubsetTwo})
                },
                TestSubsets = new List<Subset>{ TestSubsetOne, TestSubsetTwo }
            };
            
            private readonly NumericDefinitionCollectorTestParameters _differentFieldsSameSubsetsReturnsOne = new()
            {
                ExistingMetrics = new List<MetricConfiguration>(),
                LoadedFields = new List<ResponseFieldDescriptor>
                {
                    GetStubbedResponseFieldDescriptor(0, "Test", SliderWithOutChoiceSet, TestSubsetOne),
                    GetStubbedResponseFieldDescriptor(0, "Test", SliderWithOutChoiceSet, TestSubsetTwo),
                    GetStubbedResponseFieldDescriptor(0, "Test", SliderWithOutChoiceSetDifferentName, TestSubsetTwo)
                },
                ExpectedNumericFieldDefinitions = new List<NumericFieldData>
                {
                    GetStubbedNumericField(SliderWithOutChoiceSet, new(){TestSubsetOne, TestSubsetTwo}),
                    GetStubbedNumericField(SliderWithOutChoiceSetDifferentName, new(){TestSubsetTwo})
                },
                TestSubsets = new List<Subset>{ TestSubsetOne, TestSubsetTwo }
            };
            
            private readonly NumericDefinitionCollectorTestParameters _autoGeneratedNameAlreadyExistsInMetrics = new()
            {
                ExistingMetrics = new List<MetricConfiguration>
                {
                    new() { IsAutoGenerated = AutoGenerationType.CreatedFromNumeric, Field = "AutoGrouped: Test" }
                },
                LoadedFields = new List<ResponseFieldDescriptor>
                {
                    GetStubbedResponseFieldDescriptor(0, "Test", SliderWithOutChoiceSet, TestSubsetOne)
                },
                ExpectedNumericFieldDefinitions = new List<NumericFieldData>
                {
                    GetStubbedNumericField(SliderWithOutChoiceSet, new(){TestSubsetOne}, 1)
                },
                TestSubsets = new List<Subset>{ TestSubsetOne }
            };

            public IEnumerator GetEnumerator()
            {
                yield return GetTest(_singleNumericField, "Test valid numeric field returns field definition");
                yield return GetTest(_singleRadioField, "Test non numeric field returns nothing");
                yield return GetTest(_singleNumericFieldWithEntity, "Test field with entity combinations returns nothing");
                yield return GetTest(_multipleField, "Test multiple fields only returns the numeric field");
                yield return GetTest(_numericFieldAlreadyExists, "Test numeric field isn't created if numeric metric all ready exists");
                yield return GetTest(_duplicateFieldsDifferentSubsetsReturnsOne, "Testing to see if the same field appears multiple times for multi subsets only creates one numeric field data object");
                yield return GetTest(_differentFieldsSameSubsetsReturnsOne, "Testing different fields with same subset returns different numeric field objects");
            }

            private static TestCaseData GetTest(NumericDefinitionCollectorTestParameters parameters, string testName)
            {
                return new TestCaseData(parameters.ExistingMetrics, parameters.LoadedFields, parameters.ExpectedNumericFieldDefinitions, parameters.TestSubsets).SetName(testName);
            }

            private static ResponseFieldDescriptor GetStubbedResponseFieldDescriptor(int noOfEntities, string name, FieldDefinitionModel fieldDefinition, Subset subset)
            {
                var entities = new List<EntityType>();
                for (int i = 0; i < noOfEntities; i++)
                {
                    entities.Add(new EntityType());
                }

                var responseFieldDescriptor = new ResponseFieldDescriptor(name, entities.ToArray());
                responseFieldDescriptor.AddDataAccessModelForSubset(subset.Id, fieldDefinition);
                return responseFieldDescriptor;
            }

            private static FieldDefinitionModel GetStubbedFieldDefinitionModel(string name, string questionType, bool hasChoiceSet)
            {
                var question = new Question
                {
                    MasterType = questionType,
                    VarCode = name,
                    QuestionText = "This is a test question"
                };
                if (hasChoiceSet)
                {
                    question.AnswerChoiceSet = new ChoiceSet();
                }

                var fieldDefinition = new FieldDefinitionModel(name, "", "", "", "", null, name, 0.0, "", false, null, new List<EntityFieldDefinitionModel>(), null);
                fieldDefinition.QuestionModel = question;
                return fieldDefinition;
            }

            private static NumericFieldData GetStubbedNumericField(FieldDefinitionModel field, List<Subset> subsets, int duplicatedCount = 0)
            {
                NumericFieldData numericFieldData = null;
                for (int i = 0; i < subsets.Count; i++)
                {
                    if (i == 0)
                    {
                        numericFieldData = new NumericFieldData(field, subsets[i].Id);
                        numericFieldData.SetOriginalMetricName("Test");
                    }
                    else
                    {
                        numericFieldData?.AddSubset(subsets[i].Id);
                    }
                }

                if (numericFieldData != null && duplicatedCount > 0)
                {
                    numericFieldData.IsDuplicate(duplicatedCount);
                }

                return numericFieldData;
            }
        }

        [Test]
        [TestCaseSource(typeof(NumericDefinitionFieldCollectorTestParameterEnumerator))]
        [Parallelizable(ParallelScope.All)]
        public void GetAllNewNumericFields_GivenExistingFieldsAndMetrics_ReturnsExpectedNumericFields(IList<MetricConfiguration> existingMetrics, IList<ResponseFieldDescriptor> loadedFields, IList<NumericFieldData> expectedNumericFieldDefinitions, IList<Subset> testSubsets)
        {
            // setup
            var metricConfigurationRepository = Substitute.For<IMetricConfigurationRepository>();
            metricConfigurationRepository.GetAll().Returns(existingMetrics.AsReadOnly());
            var responseFieldManager = Substitute.For<IResponseFieldManager>();
            responseFieldManager.GetAllFields().Returns(loadedFields);
            var subsetRepository = Substitute.For<ISubsetRepository>();
            subsetRepository.GetEnumerator().Returns(testSubsets.GetEnumerator());
            var substitutedAnswersDbContextFactory = ConfigureAnswersDbContextFactory(loadedFields, testSubsets);

            var questionIdHasAnswersLookup = new Dictionary<int, bool>();
            questionIdHasAnswersLookup.Add(0, true);

            // action
            var numericFieldCollector = new NumericFieldDefinitionCollector(metricConfigurationRepository,
                responseFieldManager,
                subsetRepository,
                substitutedAnswersDbContextFactory);
            var numericFieldDefinitions = numericFieldCollector.GetAllNewNumericFields(questionIdHasAnswersLookup).ToList();

            //assert
            Assert.That(numericFieldDefinitions.Count, Is.EqualTo(expectedNumericFieldDefinitions.Count));
            for (int i = 0; i < expectedNumericFieldDefinitions.Count; i++)
            {
                Assert.That(numericFieldDefinitions[i].GetFieldDefinitionModel().Name, Is.EqualTo(expectedNumericFieldDefinitions[i].GetFieldDefinitionModel().Name));
                Assert.That(numericFieldDefinitions[i].GetMetricConfigurationSubsetIdList(), Is.EqualTo(expectedNumericFieldDefinitions[i].GetMetricConfigurationSubsetIdList()));
            }
        }

        private static global::BrandVue.SourceData.AnswersMetadata.IAnswerDbContextFactory ConfigureAnswersDbContextFactory(IList<ResponseFieldDescriptor> loadedFields, IList<Subset> testSubsets)
        {
            var questions = new List<Question>();
            var answers = new List<Answer>();

            foreach (var subset in testSubsets)
            {
                foreach (var field in loadedFields)
                {
                    var question = field.GetDataAccessModelOrNull(subset.Id)?.QuestionModel;
                    if(question != null)
                    {
                        questions.Add(question);
                    }
                    else
                    {
                        question = new Question()
                        {
                            VarCode = field.Name,
                            ItemNumber = field.ItemNumber,
                            QuestionId = field.ItemNumber,
                        };
                    }

                    var answer = new Answer()
                    {
                        QuestionId = question.QuestionId,
                        Question = question,
                    };
                    answers.Add(answer);
                }
            }

            var questionsDbSet = AnswersMetaDataHelper.CreateMockDbSet(questions);
            var answerDbSet = AnswersMetaDataHelper.CreateMockDbSet(answers);
            var substitutedAnswersDbContextFactory = AnswersMetaDataHelper.CreateMockAnswersDbContext(questionsDbSet, answerDbSet);
            return substitutedAnswersDbContextFactory;
        }
    }
}