apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: azure-store
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: https://bv-airflow-vault.vault.azure.net/
      serviceAccountRef:
        name: airflow