// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BrandVue.EntityFramework.Answers.Model
{
    [Table("surveySegments", Schema = "dbo")]
    public partial class SurveySegment
    {
        [Key]
        [Column("surveySegmentId")]
        public int SurveySegmentId { get; set; }
        [Column("segmentName")]
        [StringLength(100)]
        public string SegmentName { get; set; }
        public int SurveyId { get; set; }
    }
}