using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BrandVue.EntityFramework.MetaData.Page
{
    [Table("Panes")]
    public class DbPane
    {
        /// <summary>
        /// Autogenerated by SQL
        /// </summary>
        public int Id { get; set; }
        public string ProductShortCode { get; set; }
        [StringLength(SqlTypeConstants.DefaultVarcharLength)]
        public string SubProductId { get; set; }
        /// <summary>
        /// This is Id column in the map file
        /// </summary>
        public string PaneId { get; set; }
        public string PageName { get; set; }
        public int Height { get; set; }
        public string PaneType { get; set; }
        public string Spec { get; set; }
        public string Spec2 { get; set; }
        public int? View { get; set; }
        [Column(TypeName = "nvarchar(450)")]
        public string Subset { get; set; }
    }
}
