using BrandVue.EntityFramework;
using BrandVue.EntityFramework.MetaData;
using BrandVue.EntityFramework.MetaData.Weightings;
using BrandVue.Filters;
using BrandVue.Models;
using BrandVue.Services;
using BrandVue.SourceData.Entity;
using BrandVue.SourceData.LazyLoading;
using BrandVue.SourceData.Measures;
using BrandVue.SourceData.QuotaCells;
using BrandVue.SourceData.Respondents;
using BrandVue.SourceData.Subsets;
using BrandVue.SourceData.Weightings;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace BrandVue.Controllers.Api
{
    [SubProductRoutePrefix("api/meta")]
    [CacheControl(NoStore = true)]
    public class WeightingPlansController : ApiController
    {
        private readonly IProductContext _productContext;
        private readonly IWeightingPlanRepository _weightingPlanRepository;
        private readonly ISubsetRepository _subsetRepository;
        private readonly IMeasureRepository _measureRepository;
        private readonly IInvalidatableLoaderCache _invalidatableLoaderCache;
        private readonly IEntityRepository _entityRepository;
        private readonly IRespondentRepositorySource _respondentRepositorySource;
        IQuotaCellReferenceWeightingRepository _quotaCellReferenceWeightingRepository;
        private readonly IWeightingPlanService _weightingPlanService;
        private readonly IResponseWeightingRepository _responseWeightingRepository;

        public WeightingPlansController(IProductContext productContext,
            IWeightingPlanRepository weightingPlanRepository,
            ISubsetRepository subsetRepository,
            IMeasureRepository measureRepository,
            IEntityRepository entityRepository,
            IInvalidatableLoaderCache invalidatableLoaderCache,
            IRespondentRepositorySource respondentRepositorySource,
            IQuotaCellReferenceWeightingRepository quotaCellReferenceWeightingRepository,
            IWeightingPlanService weightingPlanService,
            IResponseWeightingRepository responseWeightingRepository)
        {
            _productContext = productContext;
            _weightingPlanRepository = weightingPlanRepository;
            _subsetRepository = subsetRepository;
            _measureRepository = measureRepository;
            _invalidatableLoaderCache = invalidatableLoaderCache;
            _entityRepository = entityRepository;
            _respondentRepositorySource = respondentRepositorySource;
            _quotaCellReferenceWeightingRepository = quotaCellReferenceWeightingRepository;
            _weightingPlanService = weightingPlanService;
            _responseWeightingRepository = responseWeightingRepository;
        }

        private int GetSubsetSortOrderBy(string subsetId)
        {
            return _subsetRepository.TryGet(subsetId, out var subset) ? subset.Order : 1000;
        }

        [HttpGet]
        [Route("weightingPlan")]
        public IEnumerable<UiWeightingConfigurationRoot> GetWeightingPlans()
        {
            AssertAllVue();
            var plans = _weightingPlanRepository.GetWeightingPlans(_productContext.ShortCode, _productContext.SubProductId).ToList();

            foreach (var subset in _subsetRepository)
            {
                if ((subset != null) && !plans.Any(x => x.SubsetId == subset.Id))
                {
                    if (_responseWeightingRepository.AreThereAnyRootResponseWeights(subset.Id))
                    {
                        var synthesisedPlan = new WeightingPlanConfiguration()
                        {
                            SubsetId = subset.Id,
                            ProductShortCode = _productContext.ShortCode,
                            SubProductId = _productContext.SubProductId,
                        };

                        plans.Add(synthesisedPlan);
                    }
                }
            }
            var unorderedWeightingRoots = UiWeightingConfigurationRoot.ToUIWeightingRoots(plans);
            return unorderedWeightingRoots.OrderBy(weightingRoot => GetSubsetSortOrderBy(weightingRoot.SubsetId)).ThenBy(weightingRoot => weightingRoot.SubsetId);
        }

        // ***********************************************************************************************
        // *************** THIS IS TEMPORARY CODE WHILE WE MIGRATE BRANDVUE over to being mapless ********
        // ***********************************************************************************************
        //************************** See futher down for end of temporary code ***************************
        // ***********************************************************************************************
        public record AutoGeneratedMessage(string subset, string question, string message);
        public record PlansFromConfiguration(IEnumerable<UiWeightingConfigurationRoot> roots, IEnumerable<AutoGeneratedMessage> messages);

        [HttpGet]
        [Route("weightingPlanFromCurrentWeightings")]
        public PlansFromConfiguration GetWeightingPlansFromConfiguration()
        {
            var validSubsets = _subsetRepository.Where(x => !x.Disabled).OrderBy(x => GetSubsetSortOrderBy(x.Id));
            var roots = new List<UiWeightingConfigurationRoot>();
            var messages = new List<AutoGeneratedMessage>();
            foreach (var subset in validSubsets)
            {
                var autoGeneratedWeighting = new UiWeightingConfigurationRoot(subset.Id);
                var quotaCellDefintion = _respondentRepositorySource.GetForSubset(subset).WeightedCellsGroup;
                var defintionOfWeighting = _quotaCellReferenceWeightingRepository.Get(subset);
                foreach(var quota in quotaCellDefintion.Cells)
                {
                    var weight = defintionOfWeighting.GetReferenceWeightingFor(quota);
                    InsertIntoResult(subset,autoGeneratedWeighting, quota, weight.Weight, messages);
                }
                roots.Add(autoGeneratedWeighting);
            }
            return new PlansFromConfiguration(roots, messages);
        }
        private Measure BestMatchingMeasure(string name, Subset subset)
        {
            var allMeasures = _measureRepository.GetAllForCurrentUser();
            var measuresToLookFor = new[] {
                $"{name}Weighting{subset.Id}" ,
                $"{name}Weighting",
                name,
            };
            foreach(var measureName in measuresToLookFor)
            {
                var result = allMeasures.FirstOrDefault(x => string.Compare(x.Name, measureName, true) == 0)
                    ?? allMeasures.FirstOrDefault(x => string.Compare(x.HelpText, measureName, true) == 0);
                if (result != null)
                {
                    return result;
                }
            }
            return null;
        }

        private static int EntityInstanceId(string instanceByName, TargetInstances requestedInstances)
        {
            var defaultId = instanceByName.GetHashCode();
            if (requestedInstances != null)
            {
                var instance = requestedInstances.OrderedInstances.FirstOrDefault(x => x.Name == instanceByName);
                if (instance != null)
                    return instance.Id;
                var instances = requestedInstances.OrderedInstances.Where(x => x.Name.StartsWith(instanceByName)).ToArray();
                if (instances.Count() == 1)
                {
                    return instances[0].Id;
                }
            }
            return defaultId;
        }

        private void InsertIntoResult(Subset subset, UiWeightingConfigurationRoot result, QuotaCell quota, double? weight, List<AutoGeneratedMessage> messages)
        {
            var parentPlans = result.UiWeightingPlans;
            int count = 0;
            int maxItems = quota.FieldGroupToKeyPart.Count;
            bool warnedUser = false;
            foreach (var part in quota.FieldGroupToKeyPart)
            {
                count++;
                var question = part.Key;
                var instance = part.Value;

                var entityInstanceId = instance.GetHashCode();
                var requestMeasure = BestMatchingMeasure(question, subset);
                var myQuestionName = requestMeasure?.Name ?? question;
                if (requestMeasure == null)
                {
                    if (!messages.Any(x => x.subset == subset.Id && x.question == question))
                    {
                        messages.Add(new AutoGeneratedMessage(subset.Id, question, $"Failed to find measure for {question}"));
                    }
                    warnedUser = true;
                }

                if (!parentPlans.Any(x=>x.VariableIdentifier == myQuestionName))
                {
                    parentPlans.Add(new UiWeightingPlanConfiguration()
                    {
                        VariableIdentifier = myQuestionName,
                        IsWeightingGroupRoot = false,
                        UiChildTargets = new List<UiWeightingTargetConfiguration>(),
                    });
                }

                var myPlan = parentPlans.First(x => x.VariableIdentifier == myQuestionName);

                if (requestMeasure != null)
                {
                    var requestedInstances = _entityRepository.CreateTargetInstances(subset, requestMeasure);
                    if (requestedInstances != null && requestedInstances.OrderedInstances != null)
                    {
                        entityInstanceId = EntityInstanceId(instance, requestedInstances);
                    }
                }
                if (!warnedUser && entityInstanceId == instance.GetHashCode())
                {
                    messages.Add(new AutoGeneratedMessage(subset.Id, myQuestionName, $"Failed to find instance {instance} measure for {myQuestionName}"));
                }
                if (!myPlan.UiChildTargets.Any(x=> x.EntityInstanceId == entityInstanceId))
                {
                    myPlan.UiChildTargets.Add(new UiWeightingTargetConfiguration()
                    {
                        EntityInstanceId = entityInstanceId,
                        UiChildPlans = count == maxItems ? null: new List<UiWeightingPlanConfiguration>(),
                    });
                }
                var childInstance = myPlan.UiChildTargets.First(x => x.EntityInstanceId == entityInstanceId);
                if (count == maxItems)
                {
                    childInstance.Target = Convert.ToDecimal(weight.Value);
                }
                parentPlans = childInstance.UiChildPlans;
            }
        }
        // ***********************************************************************************************
        // ************************************* END OF TEMPORARY CODE ***********************************
        // ***********************************************************************************************

        [HttpGet]
        [Route("weightingPlan/bySubsetId/{subsetId}")]
        [SubsetAuthorisation(nameof(subsetId))]
        public UiWeightingConfigurationRoot GetWeightingPlan(string subsetId)
        {
            AssertAllVue();
            var plans =  _weightingPlanRepository.GetWeightingPlansForSubset(_productContext.ShortCode,
                _productContext.SubProductId, subsetId);
            return UiWeightingConfigurationRoot.ToUIWeightingRoots(plans).FirstOrDefault()??new UiWeightingConfigurationRoot(subsetId);
        }

        [HttpGet]
        [Route("weightingPlan/bySubsetId/{subsetId}/isDefinedAndValid")]
        [SubsetAuthorisation(nameof(subsetId))]
        public DetailedPlanValidation IsWeightingPlanDefinedAndValid(string subsetId)
        {
            AssertAllVue();
            return _weightingPlanService.IsWeightingPlanDefinedAndValid(subsetId);
        }

        [HttpGet]
        [Route("weightingPlan/bySubsetId/{subsetId}/isDefinedAndValidV2")]
        [SubsetAuthorisation(nameof(subsetId))]
        public DetailedPlanValidationV2 IsWeightingPlanDefinedAndValidV2(string subsetId)
        {
            AssertAllVue();
            return _weightingPlanService.IsWeightingPlanDefinedAndValidV2(subsetId);
        }

        [HttpPost]
        [Route("weightingPlan")]
        [Authorize(Policy = FeatureRolePolicy.Weighting)]
        [InvalidateBrowserCache]
        [SubsetAuthorisation]
        public IActionResult CreateWeightingPlan(
            [Required] [FromBody] UiWeightingConfigurationRoot weightingPlanConfiguration)
        {
            AssertAllVue();
            var dbPlans = weightingPlanConfiguration.ToWeightingPlanConfiguration(_productContext.ShortCode, _productContext.SubProductId).ToList();
            _weightingPlanRepository.UpdateWeightingPlanForSubset(_productContext.ShortCode, _productContext.SubProductId, weightingPlanConfiguration.SubsetId, dbPlans);
            _invalidatableLoaderCache.InvalidateCacheEntry(_productContext.ShortCode, _productContext.SubProductId);
            return Ok();
        }

        [HttpPost]
        [Route("weightingPlans")]
        [Authorize(Policy = FeatureRolePolicy.Weighting)]
        [InvalidateBrowserCache]
        public IActionResult CreateWeightingPlans([FromBody] IReadOnlyCollection<UiWeightingConfigurationRoot> weightingPlanConfigurations)
        {
            AssertAllVue();
            var planConfigurations = new List<WeightingPlanConfiguration>();
            foreach (var rootPlan in weightingPlanConfigurations)
            {
                planConfigurations.AddRange(rootPlan.ToWeightingPlanConfiguration(_productContext.ShortCode, _productContext.SubProductId));
            }
            _weightingPlanRepository.UpdateAllWeightingPlans(_productContext.ShortCode, _productContext.SubProductId, planConfigurations);
            _invalidatableLoaderCache.InvalidateCacheEntry(_productContext.ShortCode, _productContext.SubProductId);
            return Ok();
        }

        public record CopyWeightingPlanModel(string CopyFromSubsetId, string SubsetId) : ISubsetIdProvider;
        [HttpPost]
        [Route("copyWeightingPlan")]
        [Authorize(Policy = FeatureRolePolicy.Weighting)]
        [SubsetAuthorisation]
        [InvalidateBrowserCache]
        public IActionResult CopyWeightingPlan([Required][FromBody] CopyWeightingPlanModel model)
        {
            var existingModel = GetWeightingPlan(model.CopyFromSubsetId);
            if (existingModel != null)
            {
                var newModel = existingModel.CloneTreeFor(model.SubsetId);
                return CreateWeightingPlan(newModel);
            }
            return NotFound();
        }

        private void AddMissingInstances(WeightingPlanConfiguration plan)
        {
            var requestMeasure = _measureRepository.GetAll().FirstOrDefault(x => x.VarCode == plan.VariableIdentifier);
            if (requestMeasure != null)
            {
                var subset = requestMeasure.Subset != null ? requestMeasure.Subset[0] : _subsetRepository.Where(x => !x.Disabled).OrderBy(x => x.Order).FirstOrDefault();
                if (subset != null)
                {
                    var requestedInstances = _entityRepository.CreateTargetInstances(subset, requestMeasure);
                    foreach (var instance in requestedInstances.OrderedInstances)
                    {
                        if (!plan.ChildTargets.Any(x => x.EntityInstanceId == instance.Id))
                        {
                            plan.ChildTargets.Add(new WeightingTargetConfiguration()
                            {
                                EntityInstanceId = instance.Id,
                                ParentWeightingPlan = plan,
                                ProductShortCode = plan.ProductShortCode,
                                SubProductId = plan.SubProductId,
                                SubsetId = plan.SubsetId,
                            });
                        }
                    }
                }
            }
        }

        List<WeightingPlanConfiguration> FlattenAndClonePlans(List<WeightingPlanConfiguration> plans)
        {
            var flattenedPlans = WeightingDatabaseModelsExtensions.FlattenAndClonePlans(plans);

            foreach(var flattendPlan in flattenedPlans)
            {
                AddMissingInstances(flattendPlan);
            }
            return flattenedPlans;
        }
        [HttpPost]
        [Route("weightingPlan/bySubsetId/{subsetId}/weightingTarget/{targetId}/copyWeightingPlansToSiblings")]
        [Authorize(Policy = FeatureRolePolicy.Weighting)]
        [InvalidateBrowserCache]
        [SubsetAuthorisation(nameof(subsetId))]
        public IActionResult CopyWeightingPlansToSiblings(string subsetId, int targetId, int flattenToRim, [Required][FromBody] int[] copyToTargetInstanceIds)
        {
            var rootPlanToUpdate = GetWeightingPlan(subsetId).ToWeightingPlanConfiguration(_productContext.ShortCode, _productContext.SubProductId);
            var targetParentPlan = WeightingDatabaseModelsExtensions.GetTargetParentPlan(rootPlanToUpdate, targetId);
            var selectedTarget = targetParentPlan.ChildTargets
                .Single(t => t.Id == targetId);

            var siblingTargets = targetParentPlan.ChildTargets
                .Where(t => copyToTargetInstanceIds.Contains(t.EntityInstanceId)).ToList();

            var missingSiblingTargetsInstanceIds = copyToTargetInstanceIds
                .Where(id => !siblingTargets.Any(t=> t.EntityInstanceId == id)).ToList();

            if (selectedTarget.ChildPlans?.Count > 0)
            {
                foreach (var sibling in siblingTargets)
                {
                    targetParentPlan.ChildTargets.Remove(sibling);
                    _weightingPlanRepository.DeleteWeightingChildPlansForTarget(subsetId, _productContext.ShortCode, _productContext.SubProductId, sibling.Id);

                    var newTarget = new WeightingTargetConfiguration
                    {
                        Id = sibling.Id,
                        EntityInstanceId = sibling.EntityInstanceId,
                        Target = sibling.Target,
                        TargetPopulation = sibling.TargetPopulation,
                        ParentWeightingPlanId = sibling.ParentWeightingPlanId,
                        ParentWeightingPlan = sibling.ParentWeightingPlan,
                        ChildPlans = flattenToRim ==1 ? FlattenAndClonePlans(selectedTarget.ChildPlans): WeightingDatabaseModelsExtensions.ClonePlans(selectedTarget.ChildPlans),
                        ProductShortCode = sibling.ProductShortCode,
                        SubProductId = sibling.SubProductId,
                        SubsetId = sibling.SubsetId
                    };
                    targetParentPlan.ChildTargets.Add(newTarget);
                }
                foreach (var target in missingSiblingTargetsInstanceIds)
                {
                    var newTarget = new WeightingTargetConfiguration
                    {
                        Id = 0,
                        EntityInstanceId = target,
                        Target = null,
                        TargetPopulation = null,
                        ParentWeightingPlanId = targetParentPlan.Id,
                        ParentWeightingPlan = targetParentPlan,
                        ChildPlans = flattenToRim == 1? WeightingDatabaseModelsExtensions.FlattenAndClonePlans(selectedTarget.ChildPlans): WeightingDatabaseModelsExtensions.ClonePlans(selectedTarget.ChildPlans),
                        ProductShortCode = targetParentPlan.ProductShortCode,
                        SubProductId = targetParentPlan.SubProductId,
                        SubsetId = targetParentPlan.SubsetId
                    };
                    targetParentPlan.ChildTargets.Add(newTarget);
                }
                _weightingPlanRepository.UpdateWeightingPlan(_productContext.ShortCode, _productContext.SubProductId, targetParentPlan);
                _invalidatableLoaderCache.InvalidateCacheEntry(_productContext.ShortCode, _productContext.SubProductId);
                return Ok();
            }
            return NotFound();
        }

        [HttpPost]
        [Route("weightingPlan/{planId}/weightingTarget")]
        [Authorize(Policy = FeatureRolePolicy.Weighting)]
        [InvalidateBrowserCache]
        public IActionResult CreateWeightingTarget(int planId, [Required][FromBody] UiWeightingTargetConfiguration weightingTargetConfiguration)
        {
            AssertAllVue();

            var editingPlan = _weightingPlanRepository
                .GetWeightingPlans(_productContext.ShortCode, _productContext.SubProductId)
                .Single(ws => ws.Id == planId);
            var root = new UiWeightingConfigurationRoot(editingPlan.SubsetId);
            editingPlan.ChildTargets.Add(weightingTargetConfiguration.ToWeightingTargetConfiguration(_productContext.ShortCode, _productContext.SubProductId, root, editingPlan));

            _weightingPlanRepository.UpdateWeightingPlan(_productContext.ShortCode, _productContext.SubProductId, editingPlan);
            _invalidatableLoaderCache.InvalidateCacheEntry(_productContext.ShortCode, _productContext.SubProductId);
            return Ok();
        }

        [HttpPut]
        [Route("weightingPlan/{planId}/weightingTarget/{targetId}")]
        [Authorize(Policy = FeatureRolePolicy.Weighting)]
        [InvalidateBrowserCache]
        public IActionResult UpdateWeightingTarget(int planId, int targetId, [Required][FromBody] UiWeightingTargetConfiguration weightingTargetConfiguration)
        {
            AssertAllVue();

            var editingPlan = _weightingPlanRepository
                .GetWeightingPlans(_productContext.ShortCode, _productContext.SubProductId)
                .Single(ws => ws.Id == planId);

            var originalTarget = editingPlan.ChildTargets.SingleOrDefault(w => w.Id == targetId);
            if (originalTarget is null) return NotFound("target id not found");
            editingPlan.ChildTargets.Remove(originalTarget);

            var root = new UiWeightingConfigurationRoot(editingPlan.SubsetId);
            var newTarget = weightingTargetConfiguration.ToWeightingTargetConfiguration(_productContext.ShortCode, _productContext.SubProductId, root, editingPlan);
            editingPlan.ChildTargets.Add(newTarget);

            if (originalTarget.ChildPlans != null)
            {
                foreach (var target in originalTarget.ChildPlans)
                {
                    if (newTarget.ChildPlans.SingleOrDefault(x => x.Id == target.Id) == null)
                    {
                        _weightingPlanRepository.DeleteWeightingPlan(_productContext.ShortCode, _productContext.SubProductId, target.Id);
                    }
                }
            }
            _weightingPlanRepository.UpdateWeightingPlan(_productContext.ShortCode, _productContext.SubProductId, editingPlan);
            _invalidatableLoaderCache.InvalidateCacheEntry(_productContext.ShortCode, _productContext.SubProductId);
            return Ok();
        }

        [HttpPut]
        [Route("weightingPlan/{planId}/")]
        [Authorize(Policy = FeatureRolePolicy.Weighting)]
        [InvalidateBrowserCache]
        public IActionResult UpdateWeightingPlan(int planId, [Required][FromBody] UiWeightingPlanConfiguration plan)
        {
            AssertAllVue();

            var existingPlan = _weightingPlanRepository
                .GetWeightingPlans(_productContext.ShortCode, _productContext.SubProductId)
                .Single(weightingPlan => weightingPlan.Id == planId);
            
            var root = new UiWeightingConfigurationRoot(existingPlan.SubsetId);
            var planToUpdate = plan.ToWeightingPlanConfiguration(_productContext.ShortCode, _productContext.SubProductId, root);
            planToUpdate.ParentWeightingTargetId = existingPlan.ParentWeightingTargetId;
            _weightingPlanRepository.UpdateWeightingPlan(_productContext.ShortCode, _productContext.SubProductId, planToUpdate);
            _invalidatableLoaderCache.InvalidateCacheEntry(_productContext.ShortCode, _productContext.SubProductId);
            return Ok();
        }

        [HttpDelete]
        [Route("weightingPlan/{weightingPlanId}")]
        [Authorize(Policy = FeatureRolePolicy.Weighting)]
        [InvalidateBrowserCache]
        public IActionResult DeleteWeightingPlan(int weightingPlanId)
        {
            AssertAllVue();
            _weightingPlanRepository.DeleteWeightingPlan(_productContext.ShortCode, _productContext.SubProductId, weightingPlanId);
            _invalidatableLoaderCache.InvalidateCacheEntry(_productContext.ShortCode, _productContext.SubProductId);
            return Ok();
        }
        [HttpDelete]
        [Route("weightingPlan/{weightingPlanId}/Target/{targetId}")]
        [Authorize(Policy = FeatureRolePolicy.Weighting)]
        [InvalidateBrowserCache]
        [SubsetAuthorisation(nameof(subsetId))]
        public IActionResult DeleteWeightingTarget(string subsetId, int weightingPlanId, int targetId)
        {
            AssertAllVue();
            _responseWeightingRepository.DeleteResponseWeightsForTarget(subsetId, targetId);
            _weightingPlanRepository.DeleteWeightingTarget(subsetId, _productContext.ShortCode,
                _productContext.SubProductId, targetId);

            _invalidatableLoaderCache.InvalidateCacheEntry(_productContext.ShortCode, _productContext.SubProductId);
            return Ok();
        }


        [HttpDelete]
        [Route("weightingPlan/bySubsetId/{subsetId}")]
        [Authorize(Policy = FeatureRolePolicy.Weighting)]
        [InvalidateBrowserCache]
        [SubsetAuthorisation(nameof(subsetId))]
        public IActionResult DeleteWeightingPlanForSubset(string subsetId)
        {
            AssertAllVue();
            _weightingPlanRepository.DeleteWeightingPlanForSubset(_productContext.ShortCode, _productContext.SubProductId, subsetId);
            _responseWeightingRepository.DeleteResponseWeights(subsetId);
            _invalidatableLoaderCache.InvalidateCacheEntry(_productContext.ShortCode, _productContext.SubProductId);
            return Ok();
        }

        private void AssertAllVue()
        {
            if (!_productContext.GenerateFromSurveyIds)
                throw new NotImplementedException("Custom weightings are only supported for non-map-file Vues");
        }
    }
}