import React from 'react';
import { Metric } from '../../../../metrics/metric';
import SearchInput from '../../../SearchInput';
import { getMetricDisplayName } from '../../../helpers/SurveyVueUtils';
import { CalculationType } from '../../../../BrandVueApi';
import { metricsThatMatchSearchText, separateMetricsByGenerationType } from '../../../../metrics/metricHelper';

interface IMetricSelectListProps {
    availableMetrics: Metric[];
    selectedMetrics: Metric[];
    updateSelectedMetrics(selected: Metric[]): void;
    additionalButton?: JSX.Element;
    disableSelectAll?: boolean;
}

const MetricSelectList = (props: IMetricSelectListProps) => {
    const [searchText, setSearchText] = React.useState<string>("");

    const getMetricsToShow = () => {
        return metricsThatMatchSearchText(searchText, props.availableMetrics);
    }
    const metricsToShow = getMetricsToShow();

    const toggleMetric = (metric: Metric) => {
        const index = props.selectedMetrics.findIndex(m => m.name === metric.name);
        if (index >= 0) {
            const newMetrics = [...props.selectedMetrics];
            newMetrics.splice(index, 1);
            props.updateSelectedMetrics(newMetrics);
        } else {
            props.updateSelectedMetrics([
                ...props.selectedMetrics,
                metric
            ]);
        }
    }

    const selectAll = () => {
        const newMetrics = [
            ...props.selectedMetrics,
            ...metricsToShow.filter(m => !isMetricSelected(m)),
        ];
        props.updateSelectedMetrics(newMetrics);
    }

    const selectKey = () => {
        const newMetrics = [
            ...props.selectedMetrics,
            ...metricsToShow.filter(m => m.calcType !== CalculationType.Text && m.questionShownInSurvey && !isMetricSelected(m))
        ];
        props.updateSelectedMetrics(newMetrics);
    }

    const clearSelected = () => {
        props.updateSelectedMetrics([]);
    }

    const isMetricSelected = (metric: Metric) => {
        return props.selectedMetrics.some(m => m.name === metric.name);
    }

    const [customMetrics, standardMetrics, autoGeneratedNumericMetrics] = separateMetricsByGenerationType(metricsToShow);
    const noResults = customMetrics.length + standardMetrics.length + autoGeneratedNumericMetrics.length == 0;
    return (
        <div className="metric-select-list">
            <div className="search-container">
                <SearchInput id="search-input-component" onChange={(text) => setSearchText(text)} text={searchText} className="flat-search" />
            </div>
            <div className="count-and-buttons">
                <div className="buttons">
                    {!props.disableSelectAll &&
                        <button className="modal-button secondary-button select-all" onClick={selectAll}>Select all</button>
                    }
                    {!props.disableSelectAll &&
                        <button className="modal-button secondary-button select-key" onClick={selectKey}>Select key</button>
                    }
                    <button className="modal-button secondary-button" onClick={clearSelected}>Clear all</button>
                    {props.additionalButton}
                </div>
                <div className="count">
                    <strong>{props.selectedMetrics.length}</strong> of {props.availableMetrics.length} selected
                </div>
            </div>
            <div className="valid-metrics">
                {customMetrics.length > 0 &&
                    <div className="variables">
                        <div className="section-title">
                            Custom variables
                        </div>
                        {customMetrics.map((m, i) => {
                            const key = `variable-${m.urlSafeName}-${i}`;
                            return <div className="metric" key={key}>
                                <input type="checkbox" className="checkbox" id={key} checked={isMetricSelected(m)} onChange={() => toggleMetric(m)} />
                                <label htmlFor={key}>{getMetricDisplayName(m)}</label>
                            </div>
                        })}
                    </div>
                }
                {autoGeneratedNumericMetrics.length > 0 &&
                    <div className="questions">
                        <div className="section-title">
                            Automatically generated
                        </div>
                        {autoGeneratedNumericMetrics.map((m, i) => {
                            const key = `question-${m.urlSafeName}-${i}`;
                            return <div className="metric" key={key}>
                                <input type="checkbox" className="checkbox" id={key} checked={isMetricSelected(m)} onChange={() => toggleMetric(m)} />
                                <label htmlFor={key}></label>
                                <div className="name-container" onClick={() => toggleMetric(m)}>
                                    <span className={`var-name`}>{m.displayName}</span>
                                    <span className={`title`} title={getMetricDisplayName(m)}>{getMetricDisplayName(m)}</span>
                                </div>
                            </div>
                        })}
                    </div>
                }
                {standardMetrics.length > 0 &&
                    <div className="questions">
                        <div className="section-title">
                            Questions
                        </div>
                        {standardMetrics.map((m, i) => {
                            const key = `question-${m.urlSafeName}-${i}`;
                            return <div className="metric" key={key}>
                                <input type="checkbox" className="checkbox" id={key} checked={isMetricSelected(m)} onChange={() => toggleMetric(m)} />
                                <label htmlFor={key}></label>
                                <div className="name-container" onClick={() => toggleMetric(m)}>
                                    <span className={`var-name`}>{m.displayName}</span>
                                    <span className={`title`} title={getMetricDisplayName(m)}>{getMetricDisplayName(m)}</span>
                                </div>
                            </div>
                        })}
                    </div>
                }
                {noResults &&
                    <div className="no-results">No results</div>
                }
            </div>
        </div>
    );
};

export default MetricSelectList;